

--[[-------------------------------------------------------------------
               Mega-Bomba с дистанционным управлением  v.1.0 
              разработка:    erlik(Garry_Galler)
              last edit :        17 октября 2009 
	   как всегда использован  скрипт камрада singapur'а22  для отслеживания использования предмета
--]]-------------------------------------------------------------------


local obj_id = 0 
local pos = 0 
--local flag_ex = false
local pult = nil
local start_flag = false
local time0 = 0
local flag_boom = false
local flag1 = false
local flag2 = false
local flag3 = false
local flag4 = false
local flag5 = false
local flag6 = false


function use_pult()
if pult and type(pult) == "number" then
if not level.object_by_id(pult) then
level.start_stop_menu(ui_pult.ui_pult(), true) --запускаем меню
alife():create("dist_pult", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
end
pult = nil
end
if pult and type(pult) == "userdata" then
pult = pult:id()
else
pult = nil
end
end




--функция вызываемая из дропа
function drop_pult(obj)
if obj:section() == "dist_pult" then
pult = obj --\\если наша вещь, то запомнить его userdata
end
end



function bomba_activate()
local actor = db.actor
local bomba = db.actor:object("bomba")
if not bomba and obj_id == 0 then
news_manager.send_tip(actor, "У вас нет бомбы для активации", 0, nil, 5000)
elseif not bomba and obj_id ~= 0 then
news_manager.send_tip(actor, "Идиот - бомба заложена, установи таймер!", 0, nil, 5000)
elseif bomba and obj_id == 0 then
pos = 0 
alife():release(alife():object(bomba:id()), true) --\\ удаляем из инвентаря
this.spawn_bobm() --\  спавним рядом с ГГ
elseif bomba and obj_id ~= 0 then
pos = 0 
obj_id = 0      --\ проверяем на  то, не спавнили ли уже бомбу, если да - то обнулим ее id  
alife():release(alife():object(bomba:id()), true) --\\ удаляем из инвентаря
--flag_ex = false
this.spawn_bobm() --\  спавним рядом с ГГ
end
end


function spawn_bobm()
local pos = db.actor:position()
local dir = db.actor:direction()
pos = pos:add(dir:mul(2))
local objbomb = alife():create("bomba", pos, db.actor:level_vertex_id(), db.actor:game_vertex_id())
obj_id = objbomb.id --  id объекта после создания
--flag_ex = true
end



function start_bomba()
if start_flag then
news_manager.send_tip(db.actor, "Включить таймер невозможно - ждите подрыва первой бомбы.", 0, nil, 5000) 
return
elseif not db.actor:object("bomba") and obj_id == 0 then
news_manager.send_tip(db.actor, "Включить таймер невозможно", 0, nil, 5000)
elseif not db.actor:object("bomba") and obj_id ~= 0 then
news_manager.send_tip(db.actor, "Включен отсчет таймера", 0, nil, 5000)
start_flag = true
time0 = time_global()
elseif db.actor:object("bomba") and obj_id ~= 0 then
news_manager.send_tip(db.actor, "Включен отсчет таймера", 0, nil, 5000)
start_flag = true
time0 = time_global()
elseif db.actor:object("bomba") and obj_id == 0 then
news_manager.send_tip(db.actor, "Сделайте закладку бомбы", 0, nil, 5000)
end
end


local snd_bum = xr_sound.get_safe_sound_object([[weapons\f1_explode2]])
local snd_bum2 = xr_sound.get_safe_sound_object([[weapons\f1_explode]])
local snd_bum3 = xr_sound.get_safe_sound_object([[detectors\bomb_timer]])
local snd_bum4 = xr_sound.get_safe_sound_object([[weapons\rpg7_explode]])



function bada_boom()
local boom_obj = level.object_by_id(obj_id)
if not start_flag then 
return 
else
if not flag_snd then
snd_bum3:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d) -- \играем звук таймера 
flag_snd = true
end

if not flag_boom then
if  time_global() - time0 > 10000 then
pos = boom_obj:position()

				local h = hit()
                h.direction = vector():set(0,0,0)
                h.impulse = 10
                h.draftsman = boom_obj
                h.power = 10
                h.type = hit.fire_wound 				
		        boom_obj:hit(h) -- \взрываем бомбу		
                snd_bum:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d) -- \играем звук  взрыва от позиции 
                particles_object("explosions\\explosion_01"):play_at_pos(pos)   -- \играем партиклы от позиции бомбы
                level.add_cam_effector("camera_effects\\earthquake.anm", 1975, true, "")  -- \включаем тряску
flag_boom = true
flag1 = true
time0 = time_global()
end

elseif flag1 then 
if time_global() - time0 > 3000 then
level.remove_cam_effector(1975)       -- \останавливаем тряску через 3 секунды
particles_object("explosions\\explosion_dym"):play_at_pos(pos)
snd_bum2:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d) -- \играем еще один звук взрыва
flag1 =  false
time0 = time_global()
flag2 = true
end

elseif flag2 then
if time_global() - time0 > 2000 then
particles_object("explosions\\group_items\\campfire_06_flame_big"):play_at_pos(pos)
particles_object("explosions\\expl_benzin_00"):play_at_pos(pos)    --\ и еще один партикл
snd_bum4:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d) -- \играем еще один звук взрыва
flag2 = false
time0 = time_global()
flag3 = true
end

elseif flag3 then
if time_global() - time0 > 1000 then
particles_object("explosions\\group_items\\campfire_05_vacuum"):play_at_pos(pos)
particles_object("explosions\\explosion_fuelcan"):play_at_pos(pos)
flag3 = false
time0 = time_global()
flag4 = true
end

elseif flag4 then
if time_global() - time0 > 2000 then
particles_object("explosions\\group_items\\expl_flame_02"):play_at_pos(pos)
particles_object("explosions\\group_items\\expl_smoke_big_up_00"):play_at_pos(pos)
flag4 = false
time0 = time_global()
flag5  = true
end

elseif flag5 then
if time_global() - time0 > 2000 then
particles_object("explosions\\campfire_04"):play_at_pos(pos)
particles_object("explosions\\group_items\\smoke00"):play_at_pos(pos)
particles_object("explosions\\explosion_mobiltank"):play_at_pos(pos)
flag5  = false
time0 = time_global()
flag6  = true
end

elseif flag6 then
if time_global() - time0 > 3000 then
--particles_object("anomaly\\marevo"):play_at_pos(pos)   --\ и еще один партикл
--particles_object("industrial_particles\\exhaust_isparenie_white_down"):play_at_pos(pos)   --\ и еще один партикл
flag6 = false
flag_boom = false
flag_snd = false
obj_id = 0
--flag_ex = false
start_flag = false
end
end 
end
end



--\ функции сохранения значений переменных

function save_variable(p)
p:w_u16(obj_id)
end

function load_variable(r)
obj_id  = r:r_u16()
end






























      
	  
        
	



















      
	  
        
	