-- -*- mode: lua; coding: windows-1251-dos -*-

function false_info()
  if level.name()=="l12_stancia_2" and db.actor:has_info("haron_need_stalker_start") then db.actor:give_info_portion("haron_need_stalker_spawn")
  elseif level.name()=="l11_pripyat" and db.actor:has_info("haron_doktor_start") then
    db.actor:give_info_portion("haron_doktor_pripyat_spawn")
  elseif level.name()=="l12_stancia" and db.actor:has_info("haron_doktor_have") then
    db.actor:give_info_portion("mahon_sar_finish")
  elseif level.name()=="l04_darkvalley" and db.actor:has_info("ucen_need_metka_start") then
    db.actor:give_info_portion("electro_chimera_ucen_need")
  elseif level.name()=="l06_rostok" and db.actor:has_info("ucen_need_metka_start") then
    db.actor:give_info_portion("gigant_strong_ucen_need")
   elseif level.name()=="l01_escape" and db.actor:has_info("ucen_need_metka_start") then
    db.actor:give_info_portion("bloodsucker_strong_ucen_need")
   elseif level.name()=="l04u_labx18" and db.actor:has_info("mil_klyak_lab_start") then
    db.actor:give_info_portion("mil_klyak_lab_spawn")
  end
end

function checking_use_item( obj, sobj )
  if level.name()=="l12_stancia" and obj:section()=="wpn_knife" and db.actor:has_info("haron_spy_start") then db.actor:give_info_portion("haron_spy_spawn")
  elseif level.name()=="l12_stancia_2" and obj:section()=="aes_case1" then remove_spot1()
  elseif level.name()=="l12_stancia_2" and obj:section()=="aes_case2" then remove_spot2()
  elseif level.name()=="l12_stancia_2" and obj:section()=="aes_case3" then remove_spot3()
  elseif level.name()=="l07_military" and obj:section()=="new_plan" then remove_metka_ucen()
  elseif obj:section()=="part2" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part2") alife():release(sobj)
  elseif obj:section()=="part3" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part3") alife():release(sobj)
  elseif obj:section()=="part4" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part4") alife():release(sobj)
  elseif obj:section()=="part5" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part5") alife():release(sobj)
  elseif obj:section()=="part6" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part6") alife():release(sobj)
  elseif obj:section()=="part7" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part7") alife():release(sobj)
  elseif obj:section()=="part8" and db.actor:has_info("semeckii_treasure_start") then
    db.actor:give_info_portion("semeckii_treasure_part8") alife():release(sobj)

  elseif obj:section()=="money_gg" then money_gg() alife():release(sobj)

  elseif obj:section()=="money5" then money_5() alife():release(sobj)

  elseif obj:section()=="money10" then money_10() alife():release(sobj)

  elseif obj:section()=="money15" then money_15() alife():release(sobj)

  elseif obj:section()=="money20" then money_20() alife():release(sobj)

  elseif obj:section()=="money25" then money_25() alife():release(sobj)

  elseif obj:section()=="money30" then money_30() alife():release(sobj)

  elseif obj:section()=="money50" then money_50() alife():release(sobj)

  elseif level.name()=="predbannik" and db.actor:has_info("nato_enemy") and not has_alife_info("nato_zasada") then db.actor:give_info_portion("nato_zasada")

  elseif obj:section()=="af_snake_eye" and not has_alife_info("snake_dialog_have") then
    db.actor:give_info_portion("snake_dialog_have")

  elseif obj:section()=="amulet_1" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_2") and db.actor:object("amulet_3") and db.actor:object("amulet_4") and db.actor:object("amulet_5") and db.actor:object("amulet_6") then db.actor:give_info_portion("amulet_sobral") 
    end

  elseif obj:section()=="amulet_2" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_1") and db.actor:object("amulet_3") and db.actor:object("amulet_4") and db.actor:object("amulet_5") and db.actor:object("amulet_6") then db.actor:give_info_portion("amulet_sobral")
  end

  elseif obj:section()=="amulet_3" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_2") and db.actor:object("amulet_1") and db.actor:object("amulet_4") and db.actor:object("amulet_5") and db.actor:object("amulet_6") then db.actor:give_info_portion("amulet_sobral")
  end

  elseif obj:section()=="amulet_4" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_2") and db.actor:object("amulet_3") and db.actor:object("amulet_1") and db.actor:object("amulet_5") and db.actor:object("amulet_6") then db.actor:give_info_portion("amulet_sobral") 
  end

  elseif obj:section()=="amulet_5" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_2") and db.actor:object("amulet_3") and db.actor:object("amulet_4") and db.actor:object("amulet_1") and db.actor:object("amulet_6") then db.actor:give_info_portion("amulet_sobral") 
  end

  elseif obj:section()=="amulet_6" and not has_alife_info("amulet_sobral") then
    if db.actor:object("amulet_2") and db.actor:object("amulet_3") and db.actor:object("amulet_4") and db.actor:object("amulet_5") and db.actor:object("amulet_1") then db.actor:give_info_portion("amulet_sobral") 
  end

  elseif level.name()=="l10_radar" and obj:section()=="wpn_vint" and not has_alife_info("pauk_les_spawn") then db.actor:give_info_portion("pauk_les_spawn")

  elseif level.name()=="l04_darkvalley" and obj:section()=="af_snake_eye" and 
  not has_alife_info("snake_dialog_begin") then db.actor:give_info_portion("snake_dialog_begin")

  elseif level.name()=="l03_agroprom" and obj:section()=="af_agro" and 
  not has_alife_info("pauk_agro_spawn") then db.actor:give_info_portion("pauk_agro_spawn")

  elseif level.name()=="l10u_bunker" and obj:section()=="book_zombi" and 
  not has_alife_info("pauk_x10_spawn") then db.actor:give_info_portion("pauk_x10_spawn")

  elseif obj:section()=="almaz" and not has_alife_info("amulet_kat") then db.actor:give_info_portion("amulet_kat")

  elseif level.name()=="l04_darkvalley" and obj:section()=="wpn_knife" and 
  db.actor:has_info("doronin_help_start") then db.actor:give_info_portion("doronin_help_val")
  elseif obj:section()=="flash_ban" and db.actor:has_info("voronin_nychka_jila") then remove_spot_ban() alife():release(sobj)
  elseif obj:section()=="volk_pda" and db.actor:has_info("volk_tainik_have") then remove_volk_tainik()
  elseif level.name()=="l12u_sarcofag" and obj:section()=="amk_zapiska" then
    db.actor:give_info_portion("info_amk_recipt_almaz_kolobok") alife():release(sobj)
  elseif level.name()=="l10u_bunker" and obj:section()=="amk_zapiska" then
    db.actor:give_info_portion("info_amk_recipt_sopl_dikoobraz") alife():release(sobj)
  elseif level.name()=="l04u_labx18" and obj:section()=="detector_elite_bad" then
    db.actor:give_info_portion("levsha_remont_detector")
  elseif level.name()=="aver" and obj:section()=="mandra" then antreg.remove_spot_m()
  elseif level.name()=="l11_pripyat" and obj:section()=="wpn_knife" then antreg.del_gluk2()
  elseif level.name()=="l07_military" and obj:section()=="notebook_x16" and db.actor:has_info("sidr_lab_have") and 
  not db.actor:has_info("mil_klyak_help_start") then klyak_mil_spawn()
  end
end

function dead_npc()
  if level.name()=="l11_pripyat" and has_alife_info("prizrak_help_have") and not has_alife_info("haron_sms") then
    ogse_st_mgr.start_timer("sms_new",math.random(100,120), "braad_test.sms_new")
    db.actor:give_info_portion("haron_sms")	 
  elseif level.name()=="l12_stancia" and has_alife_info("prizrak_kill_start") and 
  not has_alife_info("doctor_sms") then
    ogse_st_mgr.start_timer("sms_doc",math.random(100,120), "braad_test.sms_doc")
    db.actor:give_info_portion("doctor_sms")

  elseif level.name()=="l12_stancia_2" and has_alife_info("control_monolit_have") and not has_alife_info("keys_sms") then         db.actor:give_info_portion("keys_sms")

  elseif level.name()=="l03_agroprom" and has_alife_info("sledopyt_first_dialog_start") and 
  not has_alife_info("taynik_sms") then
    db.actor:give_info_portion("taynik_sms")


  elseif level.name()=="l05_bar" and has_alife_info("sidr_lab_start") and 
  not has_alife_info("graf_sms") then
    db.actor:give_info_portion("graf_sms")

  elseif level.name()=="l07_military" and has_alife_info("finish_put_start") and 
  not has_alife_info("klyak_sms") then
    db.actor:give_info_portion("klyak_sms")

  elseif level.name()=="l11_pripyat" and has_alife_info("ubity_mervina_done") and 
  not has_alife_info("vozvrat_sms") then
    db.actor:give_info_portion("vozvrat_sms")

  elseif level.name()=="l11_pripyat" and has_alife_info("prizrak_kill_speak") and 
  not has_alife_info("mono_prizrak_spawn") then
    ogse_st_mgr.start_timer("mono_prizrak_spawn",math.random(120,140), "braad_test.mono_prizrak_spawn")
    db.actor:give_info_portion("mono_prizrak_spawn")
	
  elseif level.name()=="l02_garbage" and has_alife_info("bes_patron_start") and 
  not has_alife_info("bes_patron_spawn") then
    ogse_st_mgr.start_timer("bes_zasada",math.random(50,60), "braad_test.bes_zasada")
    db.actor:give_info_portion("bes_patron_spawn")
	
  elseif level.name()=="l01_escape" and has_alife_info("aes_solmon_have") and 
  not has_alife_info("aes_solmon_sms") then
    ogse_st_mgr.start_timer("sms_solomon",math.random(20,30), "braad_test.sms_solomon")
    db.actor:give_info_portion("aes_solmon_sms")
	
  elseif (has_alife_info("mil_lucash_dead") or has_alife_info("mil_blockpost_leader_dead")) and has_alife_info("mil_lucash_help_start") and not has_alife_info("mil_lucash_help_done") then db.actor:give_info_portion("mil_lucash_help_fail")
  
  elseif level.name()=="l07_military"  and not has_alife_info("actor_na_scladah") then db.actor:give_info_portion("actor_na_scladah")
	
  elseif level.name()=="l03_agroprom"  and not has_alife_info("actor_na_agro") then db.actor:give_info_portion("actor_na_agro")
  
  elseif level.name()=="l10_radar"  and not has_alife_info("actor_na_radare") then db.actor:give_info_portion("actor_na_radare")
  
  elseif has_alife_info("fedya_razboinik_see") and not has_alife_info("sveeblov_predatel_vpered") then db.actor:give_info_portion("sveeblov_predatel_fail")
  
  elseif (has_alife_info("levsha_dead") or has_alife_info("bes_dead")) and has_alife_info("bes_help_levsha_start") and not has_alife_info("bes_help_levsha_done") then db.actor:give_info_portion("bes_help_levsha_fail")
	
  elseif level.name()=="l02_garbage" and has_alife_info("bes_help_levsha_start")  and 
  not has_alife_info("bes_smart_done") then db.actor:give_info_portion("bes_smart_done")
  
  elseif level.name()=="l04_darkvalley"  and not has_alife_info("actor_na_darkvalley") then db.actor:give_info_portion("actor_na_darkvalley")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("first_urok_dialog_have") and not has_alife_info("mervin22_spawn") then db.actor:give_info_portion("mervin22_spawn")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("second_urok_dialog_have") and not has_alife_info("mervin222_spawn") then db.actor:give_info_portion("mervin222_spawn")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("mervin_start_begin") and not has_alife_info("mervin1_delete") then db.actor:give_info_portion("mervin1_delete")

  elseif level.name()=="l12_stancia_2" and has_alife_info("first_urok_dialog_start") and not has_alife_info("mervin2_delete") then db.actor:give_info_portion("mervin2_delete")

  elseif level.name()=="l12_stancia_2" and has_alife_info("second_urok_dialog_start") and not has_alife_info("mervin22_delete") then db.actor:give_info_portion("mervin22_delete")

  elseif level.name()=="l12_stancia" and has_alife_info("second_urok_dialog_done") and not has_alife_info("mervin_second_delete") then db.actor:give_info_portion("mervin_second_delete")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("haron_naem_done") and not has_alife_info("mervin3_spawn") then db.actor:give_info_portion("mervin3_spawn")

  elseif level.name()=="l11_pripyat" and has_alife_info("new_urok_dialog_start") and not has_alife_info("artefact_new_spawn") then db.actor:give_info_portion("artefact_new_spawn")

  elseif level.name()=="l10_radar" and has_alife_info("graf_second_dialog_start") and not has_alife_info("prince_spawn") then db.actor:give_info_portion("prince_spawn")

  elseif level.name()=="l10_radar" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_blue_spawn") then db.actor:give_info_portion("izlom_blue_spawn")

  elseif level.name()=="l08_yantar" and has_alife_info("graf_tri_dialog_start") and not has_alife_info("tsezar_spawn") then db.actor:give_info_portion("tsezar_spawn")

  elseif level.name()=="l03u_agr_underground" and not has_alife_info("teleport_spawn") then db.actor:give_info_portion("teleport_spawn")

  elseif level.name()=="l05_bar" and has_alife_info("levsha_daet_dobro") and has_alife_info("sidr_nacalo_start") and not has_alife_info("sledopyt_spawn") then db.actor:give_info_portion("sledopyt_spawn")

  elseif level.name()=="l03u_agr_underground" and has_alife_info("sledopyt_spawn") and not has_alife_info("str_spawn") then db.actor:give_info_portion("str_spawn")

  elseif level.name()=="l05_bar" and not has_alife_info("potapov_spawn") then db.actor:give_info_portion("potapov_spawn")

  elseif level.name()=="l04_darkvalley" and has_alife_info("doronin_help_have") and not has_alife_info("naem_td_spawn") then db.actor:give_info_portion("naem_td_spawn")


  elseif level.name()=="l12_stancia" and has_alife_info("actor_poslednii_put") and not has_alife_info("pauk_final_spawn") then db.actor:give_info_portion("pauk_final_spawn")


  elseif level.name()=="l03u_agr_underground" and has_alife_info("sledopyt_first_dialog_start") and not has_alife_info("doctor_und_spawn") then db.actor:give_info_portion("doctor_und_spawn")

  elseif level.name()=="l12u_control_monolith" and has_alife_info("gromov_first_dialog_done") and not has_alife_info("gromov_del") then db.actor:give_info_portion("gromov_del")

  elseif level.name()=="aver" and has_alife_info("babka_dialog_start") and not has_alife_info("babka_del") then db.actor:give_info_portion("babka_del")

  elseif level.name()=="l06_rostok" and has_alife_info("lektor_dialog_start") and not has_alife_info("lektor_spawn") then db.actor:give_info_portion("lektor_spawn")

  elseif level.name()=="l02_garbage" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("vypolzen_boloto_spawn") then db.actor:give_info_portion("vypolzen_boloto_spawn")

  elseif level.name()=="l02_garbage" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_mini_spawn") then db.actor:give_info_portion("izlom_mini_spawn")

  elseif level.name()=="l04u_labx18" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_x18_spawn") then db.actor:give_info_portion("izlom_x18_spawn")

  elseif level.name()=="l08u_brainlab" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_x16_spawn") then db.actor:give_info_portion("izlom_x16_spawn")

  elseif level.name()=="l02_garbage" and has_alife_info("sledopyt_first_dialog_zasada") and not has_alife_info("fantom_svalka1_spawn") then db.actor:give_info_portion("fantom_svalka1_spawn")

  elseif level.name()=="l02_garbage" and has_alife_info("mayor_yarofeev_start") and not has_alife_info("fantom_svalka2_spawn") then db.actor:give_info_portion("fantom_svalka2_spawn")

  elseif level.name()=="l06_rostok" and has_alife_info("ucen_need_metka_start") and not has_alife_info("fantom_rostok_spawn") then db.actor:give_info_portion("fantom_rostok_spawn")

  elseif level.name()=="l06_rostok" and has_alife_info("doronin_help_begin") and not has_alife_info("fantom_rostok2_spawn") then db.actor:give_info_portion("fantom_rostok2_spawn")

  elseif level.name()=="l10_radar" and has_alife_info("black_box_start") and not has_alife_info("fantom_radar2_spawn") then db.actor:give_info_portion("fantom_radar2_spawn")

  elseif level.name()=="l10_radar" and has_alife_info("black_box_start") and not has_alife_info("izlom_radar_spawn") then db.actor:give_info_portion("izlom_radar_spawn")

  elseif level.name()=="l03_agroprom" and has_alife_info("lazarev_dialog_start") and not has_alife_info("vypolzen_lazarev_spawn") then db.actor:give_info_portion("vypolzen_lazarev_spawn")

  elseif level.name()=="l02_garbage" and has_alife_info("sledopyt_first_dialog_done") and not has_alife_info("doctor_und_del") then db.actor:give_info_portion("doctor_und_del")

  elseif level.name()=="l05_bar" and has_alife_info("sidor_poslanie_dialog_start") and not has_alife_info("killer_attak_start") then
    db.actor:give_info_portion("killer_attak_start")
  elseif level.name()=="l12_stancia" and has_alife_info("actor_poslednii_put") and not has_alife_info("chaes_final_spawn") then db.actor:give_info_portion("chaes_final_spawn")

  elseif level.name()=="l12_stancia_2" and has_alife_info("semecky_first_dialog_done") and not has_alife_info("semecky_delete") then db.actor:give_info_portion("semecky_delete")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("magomet_start_dialog_start") and not has_alife_info("semecky_spawn") then db.actor:give_info_portion("semecky_spawn")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("actor_poslednii_put") and not has_alife_info("lch_del") then db.actor:give_info_portion("lch_del")

  elseif level.name()=="l05_bar" and has_alife_info("dolg_attak_dialog_start") and not has_alife_info("sledopyt_delete") then db.actor:give_info_portion("sledopyt_delete")

  elseif level.name()=="l12u_sarcofag" and has_alife_info("sled_dialog_start") and not has_alife_info("vhod_new") then db.actor:give_info_portion("vhod_new")

  elseif level.name()=="l12_stancia_2" and has_alife_info("actor_poslednii_put") and not has_alife_info("sled_spawn") then db.actor:give_info_portion("sled_spawn")

  elseif level.name()=="l12u_control_monolith" and has_alife_info("actor_poslednii_put") and not has_alife_info("gromov_spawn") then db.actor:give_info_portion("gromov_spawn")

  elseif level.name()=="l12u_control_monolith" and has_alife_info("actor_poslednii_put") and not has_alife_info("actor_finish") then db.actor:give_info_portion("actor_finish")

  elseif level.name()=="l10_radar" and has_alife_info("sahar_shlem_have") and not has_alife_info("crazy_delete") then db.actor:give_info_portion("crazy_delete")

  elseif level.name()=="l11_pripyat" and has_alife_info("finish_put_start") and not has_alife_info("zombie_spawn") then db.actor:give_info_portion("zombie_spawn")

  elseif level.name()=="l10_radar" and has_alife_info("sveeblov_predatel_done") and not has_alife_info("strannik_spawn") then db.actor:give_info_portion("strannik_spawn")

  elseif level.name()=="l08u_brainlab" and has_alife_info("potapov_first_dialog_start") and not has_alife_info("restr_x16_spawn") then db.actor:give_info_portion("restr_x16_spawn")

  elseif level.name()=="l11_pripyat" and has_alife_info("five_urok_dialog_start") and not has_alife_info("mervin3_delete") then db.actor:give_info_portion("mervin3_delete")

  elseif has_alife_info("semeckii_treasure_start") and not has_alife_info("semeckii_treasure_article") then
    db.actor:give_info_portion("semeckii_treasure_article")
  elseif has_alife_info("garbage_stalker_wound_dead") and has_alife_info("knyaz_dolg_start") and not has_alife_info("knyaz_dolg_have") then
    db.actor:give_info_portion("knyaz_dolg_have")
  elseif level.name()=="l08_yantar"  and not has_alife_info("actor_na_yantar") then
    db.actor:give_info_portion("actor_na_yantar")
  elseif (has_alife_info("ucen_ohr1_see") or has_alife_info("ucen_ohr2_see") or has_alife_info("ucen_ohr3_see")) and has_alife_info("doronin_help_val") and not has_alife_info("doronin_help_have") then
    db.actor:give_info_portion("doronin_help_fail")
  elseif level.name()=="l01_escape"  and not has_alife_info("actor_na_kordon") then
    db.actor:give_info_portion("actor_na_kordon")
  elseif (has_alife_info("volk_dead") or has_alife_info("esc_fanat_new_dead")) and has_alife_info("derevna_stalker_start") and not has_alife_info("derevna_stalker_done") then
    db.actor:give_info_portion("derevna_stalker_fail")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic6_have") and has_alife_info("volk_novic4_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic4_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic6_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic6_have") and has_alife_info("volk_novic1_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic2_have") and has_alife_info("volk_novic4_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic5_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic6_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic3_have") and has_alife_info("volk_novic4_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic5_have") and has_alife_info("volk_novic6_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic5_have") and has_alife_info("volk_novic4_have")) then
    db.actor:give_info_portion("volk_can_speak")
  elseif (has_alife_info("volk_novic1_have") and has_alife_info("volk_novic2_have") and has_alife_info("volk_novic4_have") and has_alife_info("volk_novic6_have")) then
    db.actor:give_info_portion("volk_can_speak")

  elseif (has_alife_info("semeckii_treasure_part5") or has_alife_info("semeckii_treasure_part6") or has_alife_info("semeckii_treasure_part7") or has_alife_info("semeckii_treasure_part8")) then
    db.actor:give_info_portion("informator_trade_semeckii")
  elseif level.name()=="l03_agroprom" and has_alife_info("kruglov_art_have") then contr_art_spawn()
  end

  if level.name()=="l12u_sarcofag" and not db.actor:has_info("esc_serious_talk") then
    local obj = alife():create("add_military",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("add_military",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("add_military",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_ambush",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_ambush",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_ambush",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_ambush",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_specnaz",vector():set(-22.787176132202,-7.3171,-28.85),284068,1593)
    local obj = alife():create("dark_military_specnaz",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_specnaz",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_specnaz",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_sniper",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_sniper",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_sniper",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)
    local obj = alife():create("dark_military_sniper",vector():set(-7.9555635452271,-7.31456,109.538),299642,1636)

    local obj = alife():create("sar_zapiska_ruk",vector():set(-18.628143310547,52.614501953125,10.197953224182),599,2417)

    local obj = alife():create("wpn_l85_m1",vector():set(23.551015853882,54.123477935791,-29.285837173462),5303,2417)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("rad_zapiska_ruk",vector():set(-18.395393371582,-23.520460128784,-11.5154476),3777,2784)

    local obj = alife():create("gold_art",vector():set(193.80435180664,0.094538778066635,71.867),45644,1188)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)
                        
    local obj = alife():create("gold_art",vector():set(75.451988220215,16.426797866821,34.290096),215114,294)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(270.66116333008,-8.7369184494019,-126.34954),377173,405)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(-234.88185119629,8.3708419799805,177.88945007324),16236,1337)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_sig552_isg_siber",vector():set(-260.10464477539,0.27300158143044,92.179977416992),8348,1378)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_abakan_n_m2",vector():set(-116.20272827148,-1.9442112445831,122.73686218262),43368,1315)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(86.18724822998,0.054149866104126,49.022884368896),84502,1520)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_sig_m1",vector():set(105.34355926514,0.0050590336322784,89.765724182129),95144,1520)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_fuzz_kolobok",vector():set(67.825614929199,-0.37150749,-74.097778320313),69225,1516)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_dummy_glassbeads",vector():set(32.647331237793,5.5799655,-12.673707962036),4722,1538)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_abakan_n_m1",vector():set(-117.45324707031,20.803544998169,-36.93675994873),189,1529)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_sea-urchin",vector():set(-154.36480712891,-0.286359,9.8843507766724),165820,1628)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_svu",vector():set(595.62921142578,-54.139465332031,-96.708854675293),212521,1893)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_svds",vector():set(653.56958007813,-43.883968353271,179.26545715332),226824,1912)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_sea-urchin",vector():set(660.3306274414,-43.8872718,176.84335327148),227074,1914)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("wpn_svu",vector():set(422.17352294922,-48.451919555664,5.1145219802856),135460,1921)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("medkit_army",vector():set(392.71881103516,-34.139106750488,153.86260986328),120316,1865)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("medkit_army",vector():set(392.71881103516,-34.139106750488,153.86260986328),120316,1865)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_moonlight",vector():set(4.7991132736206,-6.9216456,-72.931411743164),6850,2661)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_flash",vector():set(-83.463157653809,16.93710136,102.66344451904),165695,332)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_flash",vector():set(-43.567665100098,22.385353,-104.83944702148),147517,297)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_dummy_battery",vector():set(119.39251708984,15.86196517,26.154205322266),274810,391)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(280.64120483398,-6.46071863,1.0314919948578),379939,390)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_night_star",vector():set(33.511577606201,-4.7631421089172,-361.11657714844),215278,841)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_soul",vector():set(-45.467483520508,3.7723202705383,-12.004273414612),129993,1017)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(59.396793365479,19.6898231506,156.72634887695),358866,97)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(-81.021110534668,-0.9252895116806,157.55644226074),186914,163)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    db.actor:give_info_portion("esc_serious_talk")   
  end 
end

function spawn_level_dark()
  -- создается переход из ТЕМНОЙ ДОЛИНЫ НА РАДАР
	if (not has_alife_info(	"saharov_dark_radar" )) then
    level_new.create_level_changer(31000, vector():set(157.544,-4.795,-88.7233),357929, 919,227097, 1914,
    vector():set(660.463,-43.8839,173.0097 ),
    vector():set(0,-0.281389117240906,0),"l10_radar",0)
    db.actor:give_info_portion("saharov_dark_radar")
	end
    -- создается переход с РАДАРА в ТЕМНУЮ ДОЛИНУ
	if (not has_alife_info(	"saharov_radar_dark" )) then
    level_new.create_level_changer(31050, vector():set(660.2858,-43.876,168.832),227063, 1915,359929, 919,
    vector():set(160.9338989,-4.352917,-82.83966),
    vector():set(0,0,0),"l04_darkvalley",0)
    db.actor:give_info_portion("saharov_radar_dark")
	end
end

function spawn_level_agro()
  -- создается переход с АГРОПРОМА НА ЯНТАРЬ
	if (not has_alife_info(	"levsha_agro_yan" )) then
    level_new.create_level_changer(31100, vector():set(-129.02766,14.4666,199.999),111251, 522,15229, 1487,
    vector():set(-68.1646,1.669,-357.0758 ),
    vector():set(0.219999998807907,-0.349999994039536,0.62),"l08_yantar",0)
    db.actor:give_info_portion("levsha_agro_yan")
	end
    -- создается переход с ЯНТАРЯ НА АГРОПРОМ
	if (not has_alife_info(	"levsha_yan_agro" )) then
    level_new.create_level_changer(31150, vector():set(-69.8496,3.838,-362.1278),15229, 1487,117966, 520,
    vector():set(-122.43,11.38,185.53999),
    vector():set(0,-2.6800000667572,0),"l03_agroprom",0)
    db.actor:give_info_portion("levsha_yan_agro")
	end
end

function spawn_yan_sarc()
  -- создается переход с ЯНТАРЯ В САРКОФАГ
	if (not has_alife_info(	"zombi_yan_sarc" )) then
    level_new.create_level_changer(31200, vector():set(-25.6117,-18.152,-85.55978 ),29509, 1492,643, 2417,
    vector():set(-6.636368,51.11847,25.6256),
    vector():set(0.14012610912323,0,-0.99013364315033),"l12u_sarcofag",0)
    db.actor:give_info_portion("zombi_yan_sarc")
	end
  -- создается переход с САРКОФАГА НА ЯНТАРЬ
	if (not has_alife_info(	"zombi_sarc_yan" )) then
    level_new.create_level_changer(31250, vector():set(-13.26, 47.71, 46.57 ),200, 2417,29509, 1492,
    vector():set(-25.6117,-18.152,-85.55978),
    vector():set(-0.12247440963984,0,-0.99247169494629),"l08_yantar",0)
    db.actor:give_info_portion("zombi_sarc_yan")
	end
end

function spawn_sar_chaes2()
  -- создается переход из САРКОФАГА НА ЧАЭС2
	if (not has_alife_info(	"digger_sar_chaes2" )) then
    level_new.create_level_changer(31300, vector():set(77.10116577,58.2671585,51.8668289 ),6406,2417,53648,  2537,
    vector():set( 67.8906097,5.04050731,97.7711 ),
    vector():set(  0.0,-0.5,0.0 ),"l12_stancia_2",0)
    db.actor:give_info_portion("digger_sar_chaes2")
	end
  -- создается переход с ЧАЭС2 в САРКОФАГ
	if (not has_alife_info(	"digger_chaes2_sar" )) then
    level_new.create_level_changer(31320, vector():set( 663.8462524,0.355151146,140.6202697 ),192695,  2623,6321,2417,
    vector():set(85.1118,60.11035,50.743),
    vector():set(  0.0,-2.0,0.0 ),"l12u_sarcofag",0)
    db.actor:give_info_portion("digger_chaes2_sar")
	end
end


function spawn_rad_yan()
  -- создается переход с РАДАРА НА ЯНТАРЬ
	if (not has_alife_info(	"info_rad_yan" )) then
    level_new.create_level_changer(31340, vector():set(-33.8359031677246,4.1663,-92.70242 ),469,1959,132440, 1521,
    vector():set(176.82000732,14.0399999,81.319999),
    vector():set(0.0,2.0,0.0),"l08_yantar",0)
    db.actor:give_info_portion("info_rad_yan")
	end
  -- создается переход с ЯНТАРЯ НА РАДАР
	if (not has_alife_info(	"info_yan_rad" )) then
    level_new.create_level_changer(31350, vector():set(181.97956848,19.407814,83.3477859),132440,1521,794,1959,
    vector():set(-30.9628868103027,2.09963,-91.5933761 ),
    vector():set(  0.0,-1.5,0.0 ),"l10_radar",0)
    db.actor:give_info_portion("info_yan_rad")
	end
end

function spawn_sarc_chaes()
  -- создается переход с ЧАЭС В САРКОФАГ
	if (not has_alife_info(	"info_chaes_sarc" )) then
    level_new.create_level_changer(31370, vector():set(388.24746,0.14821225,65.81998443),169331,2385,101, 2419,
    vector():set(-27.261982,0.2294,40.4672),
    vector():set(0.0,-1.5,0.0),"l12u_sarcofag",0)
    db.actor:give_info_portion("info_chaes_sarc")
	end
  -- создается переход из САРКОФАГА НА ЧАЭС
	if (not has_alife_info(	"info_sarc_chaes" )) then
    level_new.create_level_changer(31390, vector():set(-30.6271,0.232626,45.8944),40, 2403,172158,2385,
    vector():set(393.82781,-0.0035887,63.712),
    vector():set(0.0,3.0,0.0),"l12_stancia",0)
    db.actor:give_info_portion("info_sarc_chaes")
	end
end

local haronp={
    {
        position={x=23.153,y=-4.680,z=3.578},
        gv=2424,
        lv=4684
        },
    {
        position={x=18.936,y=-0.405,z=13.346},
        gv=2424,
        lv=4699
        },
    {
        position={x=20.920,y=-3.425,z=13.356},
        gv=2424,
        lv=4699
        }
}

function first_burer()
  local sobj = alife():create("burer_normal",vector():set(73.2404251098633,-0.0141735374927521,28.42),10537,2430)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer1.ltx"
  alife():assign_story_id( sobj.id, 9800 )

  local sobj = alife():create("burer_normal",vector():set(73.2404251098633,-0.0141735374927521,28.42),10537,2430)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer2.ltx"
  alife():assign_story_id( sobj.id, 9801 )

  local sobj = alife():create("burer_normal",vector():set(-1.82103800773621,-0.136824190616608,33.927),1296,2405)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer3.ltx"
  alife():assign_story_id( sobj.id, 9802 )

  local sobj = alife():create("burer_normal",vector():set(-1.82103800773621,-0.136824190616608,33.927),1296,2405)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer4.ltx"
  alife():assign_story_id( sobj.id, 9803 )

  local sobj = alife():create("burer_normal",vector():set(-1.82103800773621,-0.136824190616608,33.927),1296,2405)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer5.ltx"
  alife():assign_story_id( sobj.id, 9804 )

  local sobj = alife():create("burer_normal",vector():set(-1.82103800773621,-0.136824190616608,33.927),1296,2405)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\burer6.ltx"
  alife():assign_story_id( sobj.id, 9805 )

  local a = haronp[math.random(table.getn(haronp))]
  local obj = alife():create("pribor_haron", vector():set(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
end

function add_new_pripyat()
  add_new_lc(833,6188,"На Радар","info_way_pripyat")
end

function add_new_radar()
  add_new_lc(1007,5240,"На Припять","info_way_radar")
end

function add_new_lc(levch,levchn,levchm,info)
  local obj = alife():story_object(levch)
  if not obj then
    alife():create(levchn)
  end

  if obj then
    level.map_add_object_spot(obj.id, "level_changer",levchm)
    db.actor:give_info_portion(info)
    info_received()
  end
end

function info_received()
  amk.send_tip("", game.translate_string( "new_way" ), 0, 10, "gen_info")
end

function delete_new_lc(levch,info)
  if not db.actor:has_info(info) then
    local obj = alife():story_object(levch)
    if obj then
      alife():release(obj)
    end
  end
end

function spawn_aes()
  local obj = alife():create("chaes_master1",vector():set(628.906,-0.0335244834423065,337.13),187244,2611)
  local obj = alife():create("chaes_master2",vector():set(628.906,-0.0335244834423065,337.13),187244,2611)
  local obj = alife():create("chaes_master3",vector():set(628.906,-0.0335244834423065,337.13),187244,2611)
  local obj = alife():create("chaes_master4",vector():set(592.286865234375,-0.177,371.006),180613,2611)
  local obj = alife():create("chaes_master5",vector():set(592.286865234375,-0.177,371.006),180613,2611)
  local obj = alife():create("chaes_master6",vector():set(592.286865234375,-0.177,371.006),180613,2611)
end

function set_relation(sid)
  local npc = level_object_by_sid(9603)
  if npc == nil or npc:alive () == false then
    return 
  end    
  npc:set_character_community("monolith", 0, 0)
end	

function set_community(actor, npc)
	db.actor:set_character_community("monolith", 0, 0)
end

-- Помощь раненому гг монолитовец
function help_wounded_mono(npc)
  local snd
	if npc:name()~="esc_vagon_wounded" then
		snd = xr_sound.get_safe_sound_object("characters_voice\\human_01\\newbie\\help\\wounded_thanx\\thanx_"..math.random(1,3))
		snd:play_no_feedback(npc, sound_object.s3d, 0, npc:position(), 1.0)
	else
		db.actor:give_info_portion("tutorial_wounded_heal")
		db.actor:give_info_portion("tutorial_wounded_help")
	end
    amk.start_timer("healing_enemies_mono",math.random(20,30),amk.pack_array_to_string( {npc:id(), npc:character_community()} ))
	npc:set_character_community("monolith", 0, 0)
	npc:set_relation(game_object.friend, db.actor)
end

	local smarts = {
		l01_escape = {
			
		},
		l02_garbage = {
			
		},
		l03_agroprom = {
			
		},
		l03u_agr_underground = {
			
		},
		l04_darkvalley = {
			
		},
		l04u_labx18 = {
			
		},
		l06_rostok = {
			
		},
		l07_military = {
			
		},
		l08_yantar = {
			
		},
		l10_radar = {
--			rad2_loner_0000 = {2,3},
--			rad2_loner_0001 = {2,3},
--			rad2_loner_0002 = {2,3}
		},
		l11_pripyat = {
			monolith_baza = {0,1,2,3},
			monolith_lenin = {0,1,2,3}
		},
		l12_stancia = {
			caes_mono_lager = {0,1,2,3}
		},
		l12_stancia_2 = {
			big_mono_aes_lager = {1,2,3}
		}
	}
	
local smarts_avail = {}
--local smarts_other = {}
local wound_id
function custom_change_mono(npc)
	local obj = alife():object(npc:id())
	local packet_wounded = xrs_utils.read_stalker_params(obj)
	local level = level.name()
	local obj_rank = get_npc_rank(npc)
	if level and smarts[level] then
		for k,v in pairs(smarts) do
			for kk,vv in pairs(smarts[k]) do
				local smarts_rank_min = vv[1] 
				local smarts_rank_max = vv[2]	
				if obj_rank and obj_rank >= smarts_rank_min and obj_rank <= smarts_rank_max then
					local smart = alife():object(kk)
					if smart and smart:is_gulag_available() and smart.gulag_working then
						if string.find(level,string.sub(kk,1,3)) then
							table.insert(smarts_avail,smart)
						--else
							--table.insert(smarts_other,smart)
						end
					end
				end		
			end
		end
	end	
	wound_id = npc:id()
	if smarts_avail and npc:alive() then 
		if table.getn(smarts_avail) > 1 then
			table.sort(smarts_avail,max_comp)
		end
		if table.getn(smarts_avail) > 0 then
			packet_wounded.custom = "[smart_terrains]\n"..smarts_avail[1]:name().." = true"
			packet_wounded.health = 1
			packet_wounded.updhealth = 1
			xrs_utils.write_stalker_params(packet_wounded,obj)
		end
    npc:remove_all_restrictions()
	end
end

function get_npc_rank(obj)
	local sobj = alife():object(obj:id())
	if sobj and sobj.rank and sobj:rank()  then
		return math.floor(sobj:rank()/290)
	end
	return nil
end

function max_comp(i1,i2) -- возвращает true если i1 меньше i2
  if wound_id then
    local sobj = alife():object(wound_id)
    return i1.position:distance_to(sobj.position) < i2.position:distance_to(sobj.position)
  end
end

function spawn_case()
  local obj = alife():create("aes_case1",vector():set(355.64077,0.005,447.625),123439,2608)
  amk.add_spot_on_map(obj.id,"crlc_big","case1")

  local obj = alife():create("aes_case2",vector():set(425.37,8.510,158.4013),143120,2599)
  amk.add_spot_on_map(obj.id,"crlc_big","case2")

  local obj = alife():create("aes_case3",vector():set(243.843,50.035,133.903),89174,2574)
  amk.add_spot_on_map(obj.id,"crlc_big","case3")
end

function add_spot()
  local sim = alife()
  local actor = db.actor
  if sim then
    obj = sim:story_object(9704)
    if obj then
      level.map_add_object_spot( obj.id, "level_changer", game.translate_string( "l12u_control_monolith" ) )
    end 
  end
end		

function controller_tubeman()
  local obj = alife():create("bloodsucker_strong",vector():set(36.4134292602539,-34.488639831543,-36.8335),3787,2475)
end

function naem_baza()
  local obj = alife():create("naem_haron1",vector():set(-16.622678,-0.00429728627204895,155.8169),82500,2190)
  local obj = alife():create("naem_haron2",vector():set(-16.622678,-0.00429728627204895,155.8169),82500,2190)
  local obj = alife():create("naem_haron3",vector():set(-16.622678,-0.00429728627204895,155.8169),82500,2190)
  local obj = alife():create("naem_haron4",vector():set(-16.622678,-0.00429728627204895,155.8169),82500,2190)
  local obj = alife():create("naem_haron5",vector():set(-16.622678,-0.00429728627204895,155.8169),82500,2190)
  local obj = alife():create("naem_haron6",vector():set(24.6308517456055,5.42022,163.33),132391,2199)
  local obj = alife():create("naem_haron7",vector():set(24.6308517456055,5.42022,163.33),132391,2199)
  local obj = alife():create("naem_haron8",vector():set(24.6308517456055,5.42022,163.33),132391,2199)
  local obj = alife():create("naem_haron9",vector():set(24.6308517456055,5.42022,163.33),132391,2199)
  local obj = alife():create("naem_haron10",vector():set(24.6308517456055,5.42022,163.33),132391,2199)
  local obj = alife():create("naem_haron11",vector():set(-21.9093494415283,-0.00035557,210.188),77374,2198)
  local obj = alife():create("naem_haron12",vector():set(-21.9093494415283,-0.00035557,210.188),77374,2198)
  local obj = alife():create("naem_haron13",vector():set(-21.9093494415283,-0.00035557,210.188),77374,2198)
  local obj = alife():create("naem_haron14",vector():set(-21.9093494415283,-0.00035557,210.188),77374,2198)
  local obj = alife():create("naem_haron15",vector():set(-21.9093494415283,-0.00035557,210.188),77374,2198)
  local obj = alife():create("naem_haron16",vector():set(31.2475471496582,5.08917,192.047),141806,2201)
  local obj = alife():create("naem_haron17",vector():set(31.2475471496582,5.08917,192.047),141806,2201)
  local obj = alife():create("naem_haron18",vector():set(31.2475471496582,5.08917,192.047),141806,2201)
  local obj = alife():create("naem_haron19",vector():set(31.2475471496582,5.08917,192.047),141806,2201)
  local obj = alife():create("naem_haron20",vector():set(31.2475471496582,5.08917,192.047),141806,2201)
end

function naem_len()
  local obj = alife():create("naem_mathon1",vector():set(52.9615020751953,-1.7326,42.72),165393,2225)
  local obj = alife():create("naem_mathon2",vector():set(52.9615020751953,-1.7326,42.72),165393,2225)
  local obj = alife():create("naem_mathon3",vector():set(52.9615020751953,-1.7326,42.72),165393,2225)
  local obj = alife():create("naem_mathon4",vector():set(52.9615020751953,-1.7326,42.72),165393,2225)
  local obj = alife():create("naem_mathon5",vector():set(52.9615020751953,-1.7326,42.72),165393,2225)
  local obj = alife():create("naem_mathon6",vector():set(31.3854713439941,-2.221,45.587),141632,2247)
  local obj = alife():create("naem_mathon7",vector():set(31.3854713439941,-2.221,45.587),141632,2247)
  local obj = alife():create("naem_mathon8",vector():set(31.3854713439941,-2.221,45.587),141632,2247)
  local obj = alife():create("naem_mathon9",vector():set(31.3854713439941,-2.221,45.587),141632,2247)
  local obj = alife():create("naem_mathon10",vector():set(31.3854713439941,-2.221,45.587),141632,2247)
end

function dyak_spawn()
  local obj = alife():create("dyak_monolit1",vector():set(408.46102905273,-0.10446,-32.680702209473),178213,2306)
  local obj = alife():create("dyak_monolit1",vector():set(408.46102905273,-0.10446,-32.680702209473),178213,2306)
  local obj = alife():create("dyak_monolit2",vector():set(408.46102905273,-0.10446,-32.680702209473),178213,2306)
  local obj = alife():create("dyak_monolit2",vector():set(408.46102905273,-0.10446,-32.680702209473),178213,2306)
end

local kons={
    {
        position={x=190.320,y=-1.830,z=180.577},
        gv=2219,
        lv=260446
        },
    {
        position={x=-115.080,y=-3.450,z=97.946},
        gv=2216,
        lv=8639
        },
    {
        position={x=-121.941,y=-2.500,z=87.957},
        gv=2140,
        lv=6490
        },
    {
        position={x=200.010,y=-2.500,z=220.897},
        gv=2219,
        lv=260936
        },
    {
        position={x=206.839,y=-0.350,z=204.416},
        gv=2219,
        lv=261202
        }
}

function food_spawn()
  local a = kons[math.random(table.getn(kons))]
  local obj = alife():create("box_food", vector():set(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)

  local obj = alife():create("box_remont",vector():set(1040.902,1.530,-28.230),464796,2280)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end


function doctor_speech()
  if level.name()=="l12_stancia" and db.actor:has_info("haron_spy_have") then
    db.actor:give_info_portion("doctor_info")
    create_re_restr()  
    news_manager.send_tip(db.actor, game.translate_string( "doctor_speech" ), nil, nil, 30000)
  end
end

function sms_new()
  db.actor:give_info_portion("haron_talk_need")
  news_manager.send_tip(db.actor, game.translate_string( "sms_new" ), nil, nil, 30000) 
end

function sms_doc()
  db.actor:give_info_portion("doc_talk_need")
  news_manager.send_tip(db.actor, game.translate_string( "sms_doc" ), nil, nil, 30000) 
end

function sms_keys()
  db.actor:give_info_portion("keys_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_keys" ), nil, nil, 30000) 
end

function sms_taynik()
  db.actor:give_info_portion("taynik_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_taynik" ), nil, nil, 30000) 
end

function sms_graf()
  db.actor:give_info_portion("graf_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_graf" ), nil, nil, 30000) 
end

function sms_klyak()
  db.actor:give_info_portion("klyak_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_klyak" ), nil, nil, 30000) 
end

function sms_vozvrat()
  db.actor:give_info_portion("vozvrat_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_vozvrat" ), nil, nil, 30000) 
end

function sms_solomon()
  db.actor:give_info_portion("info_amk_recipt_shkura")
  news_manager.send_tip(db.actor, game.translate_string( "sms_solomon" ), nil, nil, 30000) 
end

function mervin_vyrubaet()
	level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
	level.add_pp_effector("yantar_underground_psi.ppe", 2007, false)
	level.add_pp_effector("total_recall.ppe", 2008, false)
	local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\human_01\stalker\states\breath\breath_2]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
	level.add_cam_effector("camera_effects\\hit_back_left.anm", 26, false, "")
end

function iuda_vyrubaet()
	level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
	level.add_pp_effector("yantar_underground_psi.ppe", 2007, false)
	level.add_pp_effector("total_recall.ppe", 2008, false)
	local snd_obj = xr_sound.get_safe_sound_object([[affects\hit_fist]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
	level.add_cam_effector("camera_effects\\hit_back_left.anm", 26, false, "")
end

function good_shlem()
	level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
	level.add_pp_effector("yantar_underground_psi.ppe", 2007, false)
	level.add_pp_effector("total_recall.ppe", 2008, false)
	local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\human_01\stalker\states\breath\breath_2]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
	level.add_cam_effector("camera_effects\\hit_back_left.anm", 26, false, "")
	new_dialog.create_items(db.actor,"good_psy_helmet",1) 
end

function mono_prizrak_spawn()
  local obj = alife():create("mono_prizrak6",vector():set(80.449264526367,-2.22214,-20.570148468018),191808,2144)
  local obj = alife():create("mono_prizrak1",vector():set(83.398750305176,-2.39423,-7.9892024993896),194761,2144)
  local obj = alife():create("mono_prizrak2",vector():set(94.49609375,-2.39215,-6.1620998382568),205465,2144)
  local obj = alife():create("mono_prizrak3",vector():set(132.78782653809,-2.394,-65.896942138672),235486,2241)
  local obj = alife():create("mono_prizrak4",vector():set(125.62390136719,-2.39256,-64.209358215332),230995,2241)
  local obj = alife():create("mono_prizrak5",vector():set(119.00871276855,-2.4050,-68.360877990723),227330,2241)
end

function mono_patrol()
  local obj = alife():create("mono_patrol1",vector():set(-28.220415115356,-2.256,-136.57357788086),71287,2133)
  local obj = alife():create("mono_patrol2",vector():set(-31.98370552063,-2.395,-134.47309875488),66861,2133)
  local obj = alife():create("mono_patrol3",vector():set(-36.671649932861,-2.39,-130.03471374512),62154,2133)
  local obj = alife():create("mono_patrol4",vector():set(-17.674057006836,-2.302,-133.24459838867),81429,2133)
  local obj = alife():create("mono_patrol5",vector():set(-0.28423526883125,-2.3923,-108.29730224609),101987,2125)
  local obj = alife():create("mono_patrol6",vector():set(9.1660976409912,-1.8119,-79.970878601074),112798,2131)
  local obj = alife():create("mono_patrol7",vector():set(18.495990753174,-2.22009,-38.524749755859),124041,2131)
  local obj = alife():create("mono_patrol8",vector():set(50.08512878418,-2.2202,-38.656524658203),161629,2137)
end

function sheme_bunker_spawn()
  local obj = alife():create("shceme_document_ruk",vector():set(-32.461,-34.430,-21.971),609,2479)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function solomon_grabs()
  local sobj = alife():create("solomon_mono1",vector():set(-0.875,5.010,66.200),23984,2660)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\solomon_mono1.ltx"
  alife():assign_story_id( sobj.id, 30216 )
end

function solomon_mono_spawn()
  local obj = alife():create("solomon_mono2",vector():set(2.7715966701508,4.90849,88.047088623047),25216,2530)
  local obj = alife():create("solomon_mono3",vector():set(25.721918106079,5.06846,83.836639404297),36376,2530)
  local obj = alife():create("solomon_mono4",vector():set(33.805053710938,4.9988,103.37216186523),39952,2529)
  local obj = alife():create("solomon_mono5",vector():set(-3.7105083465576,4.10073,121.14627838135),22428,2519)
end

function prip_atp_spawn()
  -- создается переход с ПРИПЯТИ НА БОЛОТА
	if (not has_alife_info( "info_prip_atp" )) then
    level_new.create_level_changer(31980, vector():set( -33.3158,-2.4126,-184.56288 ),65184, 2134,
        1778027,
        3011,
        vector():set( 290.082,6.804,67.704 ),
        vector():set( 0.0,1.5,0.0 ),"swamp",0)
        db.actor:give_info_portion("info_prip_atp")
	end
end	

function remove_spot1()
  for a, obj in alife():objects() do
    if obj:name() == "aes_case2" then 
      level.map_remove_object_spot(obj.id,"crlc_big")
      break
    end
  end
end

function remove_spot2()
  for a, obj in alife():objects() do
    if obj:name() == "aes_case2" then 
      level.map_remove_object_spot(obj.id,"crlc_big")
      break
    end
  end
end

function remove_spot3()
  for a, obj in alife():objects() do
    if obj:name() == "aes_case3" then 
      level.map_remove_object_spot(obj.id,"crlc_big")
      break
    end
  end
end

function aes_tele( actor, npc)
  level.add_pp_effector ("blink.ppe", 234, false)       
  level.add_pp_effector("teleport.ppe", 2006, false) 
  db.actor:set_actor_position(patrol("aes_actor_tele_walk"):point(0))
  local dir = patrol("aes_actor_tele_look"):point(0):sub(patrol("aes_actor_tele_look"):point(0))
  db.actor:set_actor_direction(-dir:getH())
end

function rost_tele( actor, npc)
  level.add_pp_effector ("blink.ppe", 234, false)       
  level.add_pp_effector("teleport.ppe", 2006, false) 
  db.actor:set_actor_position(patrol("rost_actor_tele_walk"):point(0))
  local dir = patrol("rost_actor_tele_look"):point(0):sub(patrol("rost_actor_tele_look"):point(0))
  db.actor:set_actor_direction(-dir:getH())
end

local out_object
local in_object

function ograblen(actor,npc)
  local inv_box_1 = level_object_by_sid(30216)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end

function bandit_vzal(actor,npc)
  local inv_box_1 = level_object_by_sid(9651)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end

function bandit_otdal(actor,npc)
  local inv_box_1 = level_object_by_sid(9651)
  in_object = db.actor
  out_object = inv_box_1
  out_object:inventory_for_each(transfer_object_item)
end

function peredacha(actor,npc)
  local inv_box_1 = level_object_by_sid(9638)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end

function vozvrat(actor,npc)
  local inv_box_1 = level_object_by_sid(9638)
  in_object = db.actor
  out_object = inv_box_1
  out_object:inventory_for_each(transfer_object_item)
end

function transfer_object_items(item)
  local sect = item:section() 
  if sect == "detector_simple"
  or sect == "matras" 
  or sect == "bioradar"
  or sect == "detector_kruglov" 
  or sect == "device_torch"
  or sect == "wpn_knife"
  or sect == "wpn_binoc"   
  then
    return
  end
  out_object:transfer_item(item, in_object)
end 

function transfer_object_item(item)
  out_object:transfer_item(item, in_object)
end 

function mervin_vzyal(actor,npc)
  local inv_box_1 = level_object_by_sid(9608)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end

function pripyat_pustoy(actor,npc)
  local inv_box_1 = level_object_by_sid(30174)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end

function money_out(t1,t2) 
  local npc=t1
  if npc:id()==db.actor:id() then
    npc=t2
  end
  dialogs.relocate_money(npc,db.actor:money(),"out")
end

function mervin_otdal(actor,npc)
  local inv_box_1 = level_object_by_sid(9608)
  in_object = db.actor
  out_object = inv_box_1
  out_object:inventory_for_each(transfer_object_item)
end

-----------------------------maroder_ograblenie------------------------------
function maroder_grab(actor,npc)
  local inv_box_1 = level_object_by_sid(30213)
  out_object = db.actor
  in_object = inv_box_1
  db.actor:inventory_for_each(transfer_object_items)
end 

function maroder_money()
  local money_actor = db.actor:money()
  ogse.save_var( "money_actor", money_actor, "u8" )
  db.actor:give_money(-money_actor)
end

function mervin_money()
  local money_actor = db.actor:money()
  db.actor:give_money(-money_actor)
end

------------------------------------money------------------------------------

function money_gg()
  local money_actor = ogse.load_var( "money_actor", 0 )
  db.actor:give_money(money_actor)
end

function money_5()
  db.actor:give_money(5000)
end

function money_10()
  db.actor:give_money(10000)
end

function money_15()
  db.actor:give_money(15000)
end

function money_20()
  db.actor:give_money(20000)
end

function money_25()
  db.actor:give_money(25000)
end

function money_30()
  db.actor:give_money(30000)
end

function money_50()
  db.actor:give_money(50000)
end

function set_solomon(sid)
  local npc = level_object_by_sid(9611)
  if npc == nil or npc:alive () == false then
    return 
  end    
  npc:set_character_community("stalker", 0, 0)
end	

function set_community_solomon(actor, npc)
	db.actor:set_character_community("stalker", 0, 0)
end

function friendactor(community1, community2)
  relation_registry.set_community_goodwill ("monolith", "actor", 2500)
end

function enemyactor(community1, community2)
  relation_registry.set_community_goodwill ("monolith", "actor", -5000)
end

----------
-- чтение формы из нет-пакета
----------
function r_shape(packet)
	local s
	local st = {}
	st.count = packet:r_u8()
	st.shapes = {}
	for i=1, st.count do
		s = {}
		s.type = packet:r_u8()
		if s.type == 0 then
			s.center = packet:r_vec3()
			s.radius = packet:r_float()
		else
			s.axis_x = packet:r_vec3()
			s.axis_y = packet:r_vec3()
			s.axis_z = packet:r_vec3()
			s.offset = packet:r_vec3()
		end
		st.shapes[i] = s
	end
	return st
end

----------
-- запись формы в нет-пакет
----------
function w_shape(packet, st)
	local s
	packet:w_u8(st.count)
	for i=1, st.count do
		s = st.shapes[i]
		packet:w_u8(s.type)
		if s.type == 0 then
			packet:w_vec3(s.center)
			packet:w_float(s.radius)
		else
			packet:w_vec3(s.axis_x)
			packet:w_vec3(s.axis_y)
			packet:w_vec3(s.axis_z)
			packet:w_vec3(s.offset)
		end
	end
end

----------
-- перепаковка нет-пакета созданного скриптом рестрикта
----------
function rewrite_restrictor(se_obj, custom, radius)
	local packet = net_packet()
	se_obj:STATE_Write(packet)
	local game_vertex_id	= packet:r_u16()
	local distance		= packet:r_float()
	local direct_control	= packet:r_s32()
	local level_vertex_id	= packet:r_s32()
	local object_flags		= packet:r_s32()
	local custom_data		= packet:r_stringZ()
	local story_id		= packet:r_s32()
	local spawn_story_id	= packet:r_s32()
	local shape		= r_shape(packet)
	local restrictor_type	= packet:r_u8()

	custom_data = custom
	shape = {}
	shape.count = 1
	shape.shapes = {}
	shape.shapes[1] = {}
	shape.shapes[1].type = 0
	shape.shapes[1].center = vector():set(0,0,0)
	shape.shapes[1].radius = radius

	packet:w_u16(game_vertex_id)
	packet:w_float(distance)
	packet:w_s32(direct_control)
	packet:w_s32(level_vertex_id)
	packet:w_s32(object_flags)
	packet:w_stringZ(custom_data)
	packet:w_s32(story_id)
	packet:w_s32(spawn_story_id)
	w_shape(packet, shape)
	packet:w_u8(restrictor_type)
	se_obj:STATE_Read(packet, packet:w_tell() - packet:r_tell())
end

function friendsvoboda(community1, community2)
  relation_registry.set_community_goodwill ("freedom", "actor", 700)
end

function friendbratva(community1, community2)
  relation_registry.set_community_goodwill ("bratok", "actor", 50)
end

function actor_has_money_2000()
  return db.actor:money()>=2000
end

function actor_not_money_2000()
  return db.actor:money()<2000
end

function actor_has_money_3000()
  return db.actor:money()>=3000
end

function actor_not_money_3000()
  return db.actor:money()<3000
end

function actor_has_money_100000()
  return db.actor:money()>=100000
end

function actor_not_money_100000()
  return db.actor:money()<100000
end

function give_money_2000(t1,t2)
  local npc = t1
  if npc:id() == db.actor:id() then
    npc = t2
  end
  dialogs.relocate_money(npc,2000,"out")
end

function give_money_3000(t1,t2)
  local npc = t1
  if npc:id() == db.actor:id() then
    npc = t2
  end
  dialogs.relocate_money(npc,3000,"out")
end

function give_money_100000(t1,t2)
  local npc = t1
  if npc:id() == db.actor:id() then
    npc = t2
  end
  dialogs.relocate_money(npc,100000,"out")
end

function bratva_vrag(actor, npc)
  xr_gulag.setGulagEnemy ("bar_bratok", actor)
end

function bratva_zlitsa(actor, npc)
  if db.actor and db.actor:has_info("bratva_spokoina") then
    braad_test.friendbratva()
    db.actor:disable_info_portion("bratva_spokoina")
  end
  news_manager.send_tip(db.actor, game.translate_string( "bratva_zlitsa" ), nil, nil, 30000)	
end

function winchester_knyaz()
  local obj = alife():create("wpn_winchester_knyaz",vector():set(112,5,-11),297909,984)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)

  local obj = alife():create("af_dummy_spring",vector():set(37.87,1.65,-219.83),221298,856)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

local docs={
    {
        position={x=-82.109,y=-12.900,z=55.553},
        gv=1610,
        lv=230182
        },
    {
        position={x=80.545,y=-12.490,z=61.700},
        gv=1558,
        lv=377701
        },
    {
        position={x=-9.516,y=-11.670,z=47.759},
        gv=1579,
        lv=297300
        },
    {
        position={x=115.012,y=-9.170,z=46.951},
        gv=1558,
        lv=401225
        },
    {
        position={x=97.952,y=-4.300,z=46.210},
        gv=1554,
        lv=393278
        }
}

function informator_doc_spawn()
  local a = docs[math.random(table.getn(docs))]
  local obj = alife():create("informator_doc", vector():set(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
	local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function lab_doc_spawn()
  local obj = alife():create("labx10_doc_ruk",vector():set(20.045,-23.500,16.228),8656,2772)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)

  local obj = alife():create("labx10_computer",vector():set(6.570677280426,-7.800,-15.11957),7638,2693)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end


function actor_has_money_10000()
  return db.actor:money()>=10000
end

function give_money_10000(t1,t2)
  local npc = t1
  if npc:id() == db.actor:id() then
    npc = t2
  end
  dialogs.relocate_money(npc,10000,"out")
end

function actor_na_mest()
  db.actor:give_info_portion("sveeblov_predatel_begin")
  news_manager.send_tip(db.actor, game.translate_string( "actor_na_mest" ), nil, nil, 30000) 
end

function fedya_na_mest()
  db.actor:give_info_portion("fedya_razboinik_est")
  news_manager.send_tip(db.actor, game.translate_string( "fedya_na_mest" ), nil, nil, 30000) 
end

function voronin_help()
  if level.name()=="l04_darkvalley" and not db.actor:has_info("dolg_leader_help_start") then
    local obj = alife():create("val_atak_bandit1",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit2",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit3",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit4",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit5",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit6",vector():set(-158.63682556152,0.983818,-399.34375),7360,838)
    local obj = alife():create("val_atak_bandit7",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit8",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit9",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit10",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit11",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit12",vector():set(-113.79043579102,2.84767842,-416.207611),43833,827)
    local obj = alife():create("val_atak_bandit13",vector():set(-74.135551452637,0.4473641,-430.18548),87132,826)
    local obj = alife():create("val_atak_bandit14",vector():set(-74.135551452637,0.4473641,-430.18548),87132,826)
    local obj = alife():create("val_atak_bandit15",vector():set(-74.135551452637,0.4473641,-430.18548),87132,826)
    local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\scenario\bar\dolg_megafon\megaphone_duty_alarm]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
    db.actor:give_info_portion("dolg_leader_help_start")   
  end
  news_manager.send_tip(db.actor, game.translate_string( "voronin_help" ), nil, nil, 30000) 
end

function frienddolg(community1, community2)
  relation_registry.set_community_goodwill ("dolg", "actor", 250)
end

function add_semeckii_treasure()
	treasure_manager.get_treasure_manager():give_treasure("rad_semeckii_treasure_box")
end

function set_jeka(sid)
  local npc = level_object_by_sid(9634)
  if npc == nil or npc:alive () == false then
    return 
  end    
  npc:set_relation (game_object.enemy, db.actor)
end	


function actor_has_money_15000()
  return db.actor:money()>=15000
end

function give_money_15000(t1,t2)
  local npc = t1
  if npc:id() == db.actor:id() then
    npc = t2
  end
  dialogs.relocate_money(npc,15000,"out")
end

local points={
    {
        position={x=-284.4497,y=-18.2044,z=193.8524},
        gv=1789,
        lv=56319
        },
    {
        position={x=-244.72052,y=-18.2133,z=228.4244},
        gv=1764,
        lv=88765
        },
	{
        position={x=-297.0713,y=-18.0289,z=291.957},
        gv=1833,
        lv=45227
        },
    {
        position={x=-266.4625,y=-5.94375,z=409.4007},
        gv=1851,
        lv=71146
        },
    {
        position={x=-356.2475,y=-13.421,z=391.9168},
        gv=1848,
        lv=4177
        },
    {
        position={x=-359.2898,y=-17.07724,z=206.545},
        gv=1837,
        lv=3174
        },		
    {
        position={x=-355.6864,y=-3.100588,z=151.18237},
        gv=1793,
        lv=4240
        }
}

function spawn_plan()
  local a = points[math.random(table.getn(points))]
  local obj = alife():create("new_plan", vector():set(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function set_metka_ucen()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name() == "new_plan" then
      amk.add_spot_on_map( obj.id,"red_location", game.translate_string( "set_metka_ucen" ) )
      break
    end
  end
end

function remove_metka_ucen()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name() == "new_plan" then
      level.map_remove_object_spot(obj.id,"red_location")
      break
    end
  end
end

function check_actor_weapon()
  weapon_present = true
  db.actor:inventory_for_each(checks_item)
  return weapon_present
end

function checks_item(item)
  if isWeapon(item)  then
    weapon_present = false
  end
end
--------------------------------------------new_check-------------------------------------------

function check_weapon() --функция проверки слотов на наличие оружия
  if db.actor and db.actor:has_info("agro_varayg_one_start") 
  and not db.actor:has_info("agro_varayg_four_done") then 
    local slot = db.actor:active_slot()
    if slot == 1 or slot == 2 or slot == 3 then
      db.actor:give_info_portion("agro_varayg_fail")
    end
  end
end

------------------------------------------------------------------------------------------------

function seredina_est()
  news_manager.send_tip( db.actor, game.translate_string( "seredina_est" ), nil, nil, 20000) 
end

function krugone_spawn()
  local obj = alife():create("zombie_strong_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("zombie_strong_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("zombie_strong_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("zombie_strong_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("zombie_strong_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("zombie_strong_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("zombie_strong_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("zombie_strong_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("zombie_strong_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  local obj = alife():create("zombie_strong_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  aptec_spawn()
end

function krugtwo_spawn()
  local obj = alife():create("snork_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("snork_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("snork_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("snork_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("snork_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("snork_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("snork_normal_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("snork_normal_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("snork_normal_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  local obj = alife():create("snork_normal_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  aptec_spawn()
end

function krugtri_spawn()
  local obj = alife():create("bloodsucker_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("bloodsucker_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("bloodsucker_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("bloodsucker_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("bloodsucker_normal_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("bloodsucker_normal_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  aptec_spawn()
end

function krugfour_spawn()
  local obj = alife():create("burer_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("burer_normal_und4",vector():set(-69.267166137695,-4.018285,-134.7328),3478,800)
  local obj = alife():create("burer_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("burer_normal_und3",vector():set(-88.083045959473,-16.4498,-101.61918),2278,784)
  local obj = alife():create("burer_normal_und2",vector():set(-101.89008331299,-16.47135,-46.4786),1397,755)
  local obj = alife():create("burer_normal_und1",vector():set(-98.369873046875,-16.463289260864,-9.4),1780,761)
  aptec_spawn()
end

function aptec_spawn()
  local obj = alife():create("medkit_army",vector():set(-102.13842773438,-4.4736680984497,-143.7165),1368,808)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
  local obj = alife():create("bandage",vector():set(-102.13842773438,-4.4736680984497,-143.7165),1368,808)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function bes_zasada()
  local sobj = alife():create("bes_zasada1",vector():set(124.11454772949,-1.5249103307724,176.197),286161,374)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada1.ltx"
  alife():assign_story_id( sobj.id, 9811 )

  local sobj = alife():create("bes_zasada2",vector():set(122.42546844482,-0.6895968914032,183.353),284599,374)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada2.ltx"
  alife():assign_story_id( sobj.id, 9812 )

  local sobj = alife():create("bes_zasada3",vector():set(174.68170166016,0.36053732037544,171.268),326120,375)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada3.ltx"
  alife():assign_story_id( sobj.id, 9813 )

  local sobj = alife():create("bes_zasada4",vector():set(169.69607543945,-2.9353070259094,133.623),322282,375)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada4.ltx"
  alife():assign_story_id( sobj.id, 9814 )

  local sobj = alife():create("bes_zasada5",vector():set(181.30242919922,0.36302152276039,153.8099),330686,375)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada5.ltx"
  alife():assign_story_id( sobj.id, 9815 )

  local sobj = alife():create("bes_zasada6",vector():set(181.72718811035,0.39258113503456,155.7977),331183,375)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada6.ltx"
  alife():assign_story_id( sobj.id, 9816 )
end

function set_chimera_ucen_prov()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section() == "electro_chimera" then
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_chimera_ucen" )) 
      break
    end
  end
end

function set_chimera_ucen()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj and obj:name() == "electro_chimera_ucen" then 
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_chimera_ucen" )) 
      break
    end
  end
end

function set_gigant_ucen()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj and obj:name() == "gigant_strong_ucen" then 
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_gigant_ucen" )) 
      break
    end
  end
end

function set_bloodsucker_ucen()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj and obj:name() == "bloodsucker_strong_ucen" then 
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_bloodsucker_ucen" )) 
      break
    end
  end
end

function chimera_est()
  db.actor:give_info_portion("ucen_need_metka_chimera_have")
  set_chimera_ucen()
  news_manager.send_tip(db.actor, game.translate_string( "chimera_est" ), nil, nil, 30000) 
end

function gigant_est()
  db.actor:give_info_portion("ucen_need_metka_gigant_have")
  set_gigant_ucen()
  news_manager.send_tip(db.actor, game.translate_string( "gigant_est" ), nil, nil, 30000) 
end

function bloodsucker_est()
  db.actor:give_info_portion("ucen_need_metka_bloodsucker_have")
  set_bloodsucker_ucen()
  news_manager.send_tip(db.actor, game.translate_string( "bloodsucker_est" ), nil, nil, 30000) 
end

function controler_zasada()
  if level.name()=="l06_rostok" and not db.actor:has_info("controler_zasada_spawn") then
    local obj = alife():create("snork_jumper",vector():set(-89.0649261474609,-0.0018038153,122.017),46676,1421)
    local obj = alife():create("snork_jumper",vector():set(-89.689453125,-0.00023889,146.79014),46573,1422)
    local snd_obj = xr_sound.get_safe_sound_object([[monsters\burer\burer_scan_affect_1]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
    db.actor:give_info_portion("controler_zasada_spawn")   
  end
end

function ecolog_new()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "ecolog_new" then 
      obj = alife():object(npc:id())
      npc:set_relation (game_object.enemy, db.actor) 
    end
  end
end

function yan_wound_ucen()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "yan_wound_ucen" then 
      obj = alife():object(npc:id())
      npc:set_relation (game_object.enemy, db.actor) 
    end
  end
end

function naem_sahar_spawn()
  if level.name()=="l04_darkvalley" and not db.actor:has_info("doronin_help_spawn") then
    local sobj = alife():create("naem_sahar5",vector():set(147.125,5.834,-242.918),346009,967)
    local sobj = alife():create("naem_sahar6",vector():set(146.869,5.833,-250.677),345992,967)
    db.actor:give_info_portion("doronin_help_spawn")   
  end
  yan_wound_ucen()
  ecolog_new()
  news_manager.send_tip(db.actor, game.translate_string( "naem_sahar_spawn" ), nil, nil, 30000) 
end

function nychka_spawn()
  local obj = alife():create("new_box_inv",vector():set(34.903102874756,9.980658531189,-64.443084716797),218595,1077)
  set_spot_ban()
end

function dan_zombi()
  local obj = alife():create("dan_zombied1",vector():set(1.89261031150818,0.316928297281265,2.56956),40443,1525)
  local obj = alife():create("dan_zombied2",vector():set(1.89261031150818,0.316928297281265,2.56956),40443,1525)
  local obj = alife():create("dan_zombied3",vector():set(1.89261031150818,0.316928297281265,2.56956),40443,1525)
  local obj = alife():create("dan_zombied4",vector():set(-2.76496338844299,9.35279846191406,-15.01173),37920,1525)
  local obj = alife():create("dan_zombied5",vector():set(-2.76496338844299,9.35279846191406,-15.01173),37920,1525)
end

function voronin_snork()
  local obj = alife():create("snork_voronin1",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin2",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin3",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin4",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin5",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin6",vector():set(130.00415039063,0.2329753,-237.7590637207),327388,957)
  local obj = alife():create("snork_voronin7",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
  local obj = alife():create("snork_voronin8",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
  local obj = alife():create("snork_voronin9",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
  local obj = alife():create("snork_voronin10",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
  local obj = alife():create("snork_voronin11",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
  local obj = alife():create("snork_voronin12",vector():set(156.37007141113,5.8319,-259.7184753418),355922,964)
end

function set_spot_ban()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name()=="flash_ban" then
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_spot_ban" ))
      break
    end
  end
end

function remove_spot_ban()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name()=="flash_ban" then
      level.map_remove_object_spot(obj.id,"blue_location")
      break
    end
  end
end

function set_relation_jila(sid)
  local npc = level_object_by_sid(9642)
  if npc == nil or npc:alive () == false then
    return 
  end    
  npc:set_character_community("stalker", 0, 0)
end	

function set_community_jila(actor, npc)
	db.actor:set_character_community("stalker", 0, 0)
end

------------------------------------------------------------------------------------------------------------------------------------------------------СПАВН АРТОВ-------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
function spawn_caterpillar()
    local position = db.actor:position(x,y,z)
    position.x = position.x + 10
    position.y = position.y + 4
    position.z = position.z
    news_manager.send_tip(db.actor, game.translate_string( "check_caterpillar" ), nil, nil, 30000)
    if db.actor and db.actor:dont_has_info("kruglov_art_spawn") then
      local obj = alife():create("af_caterpillar_new", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
    else
      local obj = alife():create("af_caterpillar", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
    end
end

function check_caterpillar_new()
  if db.actor and db.actor:dont_has_info("kruglov_art_spawn") then
    spawn_caterpillar()
    db.actor:give_info_portion("kruglov_art_spawn")
  end	
end

function check_caterpillar1()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info1") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info1")
  end
end

function check_caterpillar2()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info2") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info2")
  end
end

function check_caterpillar3()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info3") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info3")
  end
end

function check_caterpillar4()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info4") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info4")
  end
end

function check_caterpillar5()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info5") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info5")
  end
end

function check_caterpillar6()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info6") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info6")
  end
end

function check_caterpillar7()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info7") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info7")
  end
end

function check_caterpillar8()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info8") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info8")
  end
end

function check_caterpillar9()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info9") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info9")
  end
end

function check_caterpillar10()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info10") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info10")
  end
end

function check_caterpillar11()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info11") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info11")
  end
end

function check_caterpillar12()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info12") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info12")
  end
end

function check_caterpillar13()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info13") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info13")
  end
end

function check_caterpillar14()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info14") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info14")
  end
end

function check_caterpillar15()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info15") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info15")
  end
end

function check_caterpillar16()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info16") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info16")
  end
end

function check_caterpillar17()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info17") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info17")
  end
end

function check_caterpillar18()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info18") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info18")
  end
end

function check_caterpillar19()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info19") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info19")
  end	
end

function check_caterpillar20()
  if db.actor and db.actor:dont_has_info("spawn_caterpillar_info20") then
    spawn_caterpillar()
    db.actor:give_info_portion("spawn_caterpillar_info20")
  end	
end
----------------------------------------------------------------------------------------------------------------------------------------------------????? ?????-------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
function contr_art_spawn()
  if level.name()=="l03_agroprom" and db.actor:dont_has_info("kruglov_art_contr") then
    local obj = alife():create("pseudodog_normal",vector():set(-179.50202941895,13.36301612,149.71054077148),57889,524)
    local snd_obj = xr_sound.get_safe_sound_object([[monsters\burer\burer_scan_affect_1]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
    db.actor:give_info_portion("kruglov_art_contr")
  end
end


function volk_ban_spawn()
  local obj = alife():create("volk_ban1",vector():set(-203.49998474121,-19.899839401245,-157.83840942383),49107,53)
  local obj = alife():create("volk_ban2",vector():set(-220.39071655273,-19.930147171021,-158.34483337402),33448,47)
  local obj = alife():create("volk_ban3",vector():set(-225.10313415527,-19.688373565674,-131.26571655273),29758,63)
  local obj = alife():create("volk_ban4",vector():set(-175.64656066895,-20.016550064087,-131.22229003906),78664,55)
end

function volk_tainik_spawn()
  local obj = alife():create("volk_inv",vector():set(142.15008544922,3.3007357120514,339.77737426758),447128,232)
  amk.add_spot_on_map(obj.id,"blue_location",game.translate_string( "set_volk_tainik" ))
  local obj = alife():create("pseudodog_volk",vector():set(135.34928894043,0.19664749,347.77938842773),439897,233)
  local obj = alife():create("pseudodog_volk",vector():set(135.34928894043,0.19664749,347.77938842773),439897,233)
  local obj = alife():create("pseudodog_volk",vector():set(135.34928894043,0.19664749,347.77938842773),439897,233)
  local obj = alife():create("pseudodog_volk",vector():set(135.34928894043,0.19664749,347.77938842773),439897,233)
  local obj = alife():create("psy_dog_volk",vector():set(138.53645324707,-0.22224108874798,331.59295654297),443529,235)
  local obj = alife():create("psy_dog_volk",vector():set(138.53645324707,-0.22224108874798,331.59295654297),443529,235)
  set_volk_tainik()
end

function remove_volk_tainik()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name() == "volk_pda" then
      level.map_remove_object_spot(obj.id,"blue_location")
      break
    end
  end
end

function knyaz_razborka()
  db.actor:give_info_portion("krest_razborka_speech")
  news_manager.send_tip(db.actor, game.translate_string( "knyaz_razborka" ), nil, nil, 30000) 
end

function knyaz_set1()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:alive() and npc:name() == "razbor_ban1" then
      obj = alife():object(npc:id())
      npc:set_character_community("killer", 0, 0)
    end 
  end
end

function knyaz_set2()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:alive() and npc:name() == "razbor_ban2" then
      obj = alife():object(npc:id())
      npc:set_character_community("killer", 0, 0)
    end 
  end
end

function knyaz_set3()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:alive() and npc:name() == "razbor_ban3" then
      obj = alife():object(npc:id())
      npc:set_character_community("killer", 0, 0)
    end 
  end
end

function knyaz_set4()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:alive() and npc:name() == "razbor_ban4" then
      obj = alife():object(npc:id())
      npc:set_character_community("killer", 0, 0)
    end 
  end
end

function knyaz_set5()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:alive() and npc:name() == "razbor_ban5" then
      obj = alife():object(npc:id())
      npc:set_character_community("killer", 0, 0)
    end 
  end
end

function razborka_begin()
  db.actor:give_info_portion("krest_razborka_speech2")
  news_manager.send_tip(db.actor, game.translate_string( "razborka_begin" ), nil, nil, 30000) 
end

function knyaz_set_nazad1()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "esc_krest_bratok" then 
      npc:set_character_community("bratok", 0, 0)
      db.actor:give_info_portion("krest_razborka_set")			
    end
  end 
end

function knyaz_set_nazad2()
  local npc,obj
  for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "esc_krest_ohr1" then 
      npc:set_character_community("bratok", 0, 0) 
    end
  end 
end		

function create_sr_psy()
  local se_obj = alife():create("space_restrictor",vector():set(24.538877487183,14.674140930176,651.58270263672),304037,205)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vehicle_niva1.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)

  local se_obj = alife():create("space_restrictor",vector():set(20.246423721313,14.412837982178,648.74908447266),299198,205)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vehicle_niva2.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)

  local se_obj = alife():create("space_restrictor",vector():set(13.680048942566,14.867101669312,651.64483642578),291989,205)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vehicle_niva3.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end 

function spawn_check_kontr()
  local position = db.actor:position()
  position.x = position.x + 20
  local obj = alife():create("m_controller_old", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function spawn_check_krovosos()
  local position = db.actor:position()
  position.x = position.x + 50
  local obj = alife():create("bloodsucker_strong", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function spawn_check_burer()
  local position = db.actor:position()
  position.x = position.x + 50
  local obj = alife():create("burer_strong", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function new_logic()
  for a, obj in alife():objects() do
    if obj:name() == "agr_und_zombi" then
      alife():release(obj , true)
      level.add_cam_effector( "camera_effects\\prison_1.anm", 25, false, "" )
      level.add_pp_effector( "black.ppe", 2506, false, "" )
      local sobj = alife():create( "agr_und_zombi", db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id() )
      sobj.custom_data = "[logic]\ncfg = scripts\\new\\agr_und_zombi_new.ltx"
      alife():assign_story_id( sobj.id, 9810 )
      break
    end
  end
end

function mayor_yarofeev_spawn()
  local obj = alife():create("krevoshaev_specnaz1",vector():set(-164.44715881,-30.12526,-358.953),85056,31)
  local obj = alife():create("krevoshaev_specnaz2",vector():set(-164.44715881,-30.12526,-358.953),85056,31)
  local obj = alife():create("krevoshaev_specnaz3",vector():set(-172.62121,-25.4351692,-349.704),77072,31)
  local obj = alife():create("krevoshaev_specnaz4",vector():set(-172.62121,-25.4351692,-349.704),77072,31)
  local obj = alife():create("krevoshaev_specnaz5",vector():set(-172.62121,-25.4351692,-349.704),77072,31)
end

function sms_sidr()
  db.actor:give_info_portion("mayor_yarofeev_vrag")
  news_manager.send_tip(db.actor, game.translate_string( "sms_sidr" ), nil, nil, 30000) 
end

function sidr_lab_spawn()
  local obj = alife():create("notebook_x16",vector():set(-57.764,19.210,-0.122),1817,1530)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function ohranik_spawn()
  local obj = alife():create("wpn_rg6_m1",vector():set(-24.94743,-5.650,-21.90315),22,1545)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function klyak_lab_spawn()
  local obj = alife():create("lab_zasada1",vector():set(11.875677108765,-16.34425163269,51.680675506592),4470,1161)
  local obj = alife():create("lab_zasada2",vector():set(7.2743148803711,-16.343746185303,63.114601135254),3811,1162)
  local obj = alife():create("lab_zasada3",vector():set(16.78125,-16.343832015991,72.062187194824),5416,1163)
  local obj = alife():create("lab_zasada4",vector():set(0.094684213399887,-16.343086242676,37.941307067871),3472,1160)
  local obj = alife():create("lab_zasada5",vector():set(22.169794082642,-16.344854354858,36.643878936768),5708,1160)
  local obj = alife():create("lab_zasada6",vector():set(2.7485866546631,-16.343587875366,47.253498077393),3224,1162)
  local obj = alife():create("lab_zasada7",vector():set(21.188512802124,-16.343347549438,61.879402160645),5906,1161)
  local obj = alife():create("lab_zasada8",vector():set(12.884053230286,-16.3480052948,60.849411010742),4961,1161)
end

function ban_kogot_spawn()
  local obj = alife():create("ban_kogot1",vector():set(48.235336303711,-2.498167514801,-30.495162963867),235663,1093)
  local obj = alife():create("ban_kogot2",vector():set(49.248931884766,-2.498295545578,-49.610511779785),236513,1092)
  local obj = alife():create("ban_kogot3",vector():set(32.045829772949,1.0196729898453,-36.969398498535),213840,1091)
  local obj = alife():create("ban_kogot4",vector():set(37.592697143555,1.0220354795456,-25.274175643921),220721,1090)
  local obj = alife():create("ban_kogot5",vector():set(37.592697143555,1.0220354795456,-25.274175643921),220721,1090)
  local obj = alife():create("ban_kogot6",vector():set(37.592697143555,1.0220354795456,-25.274175643921),220721,1090)
  local obj = alife():create("ban_kogot7",vector():set(49.248931884766,-2.498295545578,-49.610511779785),236513,1092)
  local obj = alife():create("ban_kogot8",vector():set(49.248931884766,-2.498295545578,-49.610511779785),236513,1092)
end

function klyak_mil_spawn()
  if level.name()=="l07_military" and not db.actor:has_info("mil_klyak_help_start") then
    local obj = alife():create("mil_naem1",vector():set(-210.11305236816,-12.52025604248,62.831470489502),117814,1657)
    local obj = alife():create("mil_naem2",vector():set(-190.0546875,-12.653781890869,66.782318115234),134296,1657)
    local obj = alife():create("mil_naem3",vector():set(-234.45559692383,-12.654229164124,42.454696655273),97222,1680)
    local obj = alife():create("mil_naem4",vector():set(-234.45559692383,-12.654229164124,42.454696655273),97222,1680)
    local obj = alife():create("mil_naem5",vector():set(-231.55117797852,-12.658710479736,56.839199066162),99652,1679)
    local obj = alife():create("mil_naem6",vector():set(-231.55117797852,-12.658710479736,56.839199066162),99652,1679)
    local obj = alife():create("mil_naem7",vector():set(-231.55117797852,-12.658710479736,56.839199066162),99652,1679)
    local obj = alife():create("mil_naem8",vector():set(-193.74069213867,-12.718461990356,52.728500366211),131372,1657)
    db.actor:give_info_portion("mil_klyak_help_start")
  end
end

--НЕ ЗАБУДЬ!!!!
function zahar_atp_pripyat()
  -- создается переход с БОЛОТ В ПРИПЯТЬ
	if (not has_alife_info( "zahar_atp_pripyat_pereh" )) then
    level_new.create_level_changer(32010, vector():set(290.643,6.939,66.954),1779505,3011,65184,2134,
    vector():set(-33.3158,-2.4126,-184.56288),
    vector():set(0,0,0),"l11_pripyat",0)
    db.actor:give_info_portion("zahar_atp_pripyat_pereh")
  end
end	
--НЕ ЗАБУДЬ!!!!

function spawn_ammo_shilo()
  local obj = alife():create("ammo_12x70_buck",vector():set(-254.211,1.375,10.877),8265,1424)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function clear_npc_inventory(npc)
  npc:iterate_inventory(__del_item, npc)
end

function __del_item(npc, item)
  local section = item:section()
  if section == "bolt" or section == "device_torch" then
    return false
  end
  alife():release(alife():object(item:id()), true)
end

function set_fedya(sid)
  local npc = level_object_by_sid(9628)
  if npc == nil or npc:alive () == false then
    return 
  end    
  npc:set_relation (game_object.enemy, db.actor)
end	

function friendall(community1, community2)
  relation_registry.set_community_goodwill ("dolg", "actor", 300)
  relation_registry.set_community_goodwill ("stalker", "actor", 100)
  relation_registry.set_community_goodwill ("freedom", "actor", 300)
  relation_registry.set_community_goodwill ("nebo", "actor", 100)
  relation_registry.set_community_goodwill ("bratok", "actor", 100)
  relation_registry.set_community_goodwill ("stranger", "actor", 100)
  relation_registry.set_community_goodwill ("trader", "actor", 100)
  relation_registry.set_community_goodwill ("ecolog", "actor", 100)
  relation_registry.set_community_goodwill ("military", "actor", -300)
  relation_registry.set_community_goodwill ("bandit", "actor", -300)
  relation_registry.set_community_goodwill ("monolith", "actor", -300)
  relation_registry.set_community_goodwill ("killer", "actor", -300)
end

function levsha_naem()
  local obj = alife():create("levsha_naem1",vector():set(-149.54443359375,1.1022896766663,-178.35478210449),88077,669)
  local obj = alife():create("levsha_naem2",vector():set(-156.42997741699,1.1016038656235,-169.67868041992),81230,669)
  local obj = alife():create("levsha_naem3",vector():set(-149.31867980957,1.097753405571,-163.98892211914),88088,669)
end

function levsha_bioradar()
  local obj = alife():create("bioradar",vector():set(-260.860,0.015,26.480),6331,1395)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function mina_band(obj)
  for a=1,65534 do
    local obj = level.object_by_id(a)
    if obj then
      if obj:section()=="prov_ruk" then
        amk_particle.amk_particle({
				  particle="explosions\\explosion_fuelcan",
				  pos=obj:position(),
				  sound=[[weapons\t_rgd5_explosion]]
			  })
        local dist = db.actor:position():distance_to(obj:position())
        if dist < 30 then	
          local h = hit()
          h.draftsman = db.actor
          h.direction = vector():set(0,0,0)
          h:bone("bip01_spine")
          h.type = hit.explosion
          h.power = 0.6
          h.impulse = 500
          db.actor:hit(h)
        end
        level.add_pp_effector("amk_shoot.ppe", 2011, false)
        alife():release(alife():object(obj:id()))
        return
		  end
    end
  end
end
----------------------------------------------------------РАДИАЦИЯ ARC-----------------------------------------------
local inv_arts_radiation = 0

local time_previous = time_global()
local time_step = 287

function change_inv_arts_radiation(delta)
  inv_arts_radiation = inv_arts_radiation + delta
end

function apply_radiation()
  local time_current = time_global()+ 5500
  local time_delta = time_current - time_previous
  
  if time_delta >= time_step then
    local delta_radiation = inv_arts_radiation*math.min(5, time_delta/time_step)
    
    --прибавляем чуть-чуть радиации от box_black
    if db.actor:object("box_black") then
      delta_radiation =  delta_radiation + 0.004 -- подобрать экспериментальным путем
    end

    if delta_radiation>0 then
      db.actor.radiation = delta_radiation
    end
    time_previous = time_current
  end
   if level.name()=="l01_escape" and has_alife_info("mayor_yarofeev_start") and not has_alife_info("mayor_yarofeev_spawn") then
    db.actor:give_info_portion("mayor_yarofeev_spawn")

   elseif level.name()=="l01_escape" and has_alife_info("mayor_yarofeev_done") and 
not has_alife_info("sidr_sms_info") then
    ogse_st_mgr.start_timer("sms_sidr",math.random(10,20), "braad_test.sms_sidr")
    db.actor:give_info_portion("sidr_sms_info")
	
   elseif has_alife_info("krest_work_begin") and not has_alife_info("krest_work_sms") then
    ogse_st_mgr.start_timer("spawn_military_tech",math.random(60,70), "braad_test.spawn_military_tech")
    db.actor:give_info_portion("krest_work_sms")

   elseif has_alife_info("valet_dead") and has_alife_info("krest_work_start") and not has_alife_info("krest_work_have") then
    db.actor:give_info_portion("krest_work_fail")
	
   elseif level.name()=="l02_garbage" and has_alife_info("krest_razborka_start")  and 
  not has_alife_info("krest_razborka_spawn") then
    db.actor:give_info_portion("krest_razborka_spawn")
	
   elseif has_alife_info("krest_dead") and has_alife_info("krest_razborka_spawn") and not has_alife_info("krest_razborka_done") then
    db.actor:give_info_portion("krest_razborka_fail")
	
   elseif (has_alife_info("razbor_ban1_see") or has_alife_info("razbor_ban2_see") or has_alife_info("razbor_ban3_see") or has_alife_info("razbor_ban4_see") or has_alife_info("razbor_ban5_see")) and has_alife_info("krest_razborka_spawn") and not has_alife_info("krest_razborka_begin") then
    db.actor:give_info_portion("krest_razborka_fail") 
   end
   
   if level.name()=="l11_pripyat" and not has_alife_info("my_spawn_est") then 
    spawn_mervin()
    db.actor:give_info_portion("my_spawn_est")
   end
end

function spawn_mervin()
  local sobj = alife():create("esc_mervin",vector():set(-161.866,-1.748,67.668),634,2141)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\esc_mervin.ltx"
  alife():assign_story_id( sobj.id, 30135 )
end

---------------------------------------------------------РАДИАЦИЯ ARC-----------------------------------------------

function kogot_rukzak_spawn()
  local obj = alife():create("prov_ruk",vector():set(142.93045043945,5.8323435783386,-245.087890625),341121,966)
end

function pda_priz_spawn()
  local obj = alife():create("pda_priz",vector():set(-304.193,-27.575,205.831),39356,1788)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function mina_sclad()
  local apos = db.actor:position()
  local h = hit()
  h.draftsman = db.actor
  h.direction = vector():set(0,0,0)
  h:bone("bip01_spine")
  h.type = hit.explosion
  h.power = 0.6
  h.impulse = 500
  db.actor:hit(h)          
  amk_particle.amk_particle({
    particle="explosions\\explosion_fuelcan",
    pos=apos,
    sound=[[weapons\t_rgd5_explosion]]
  })
  level.add_pp_effector("amk_shoot.ppe", 2011, false)
end

function spawn_military_tech()
  if level.name()=="l01_escape" and not db.actor:has_info("krest_work_spawn") then
    spawn_military_tech_new( alife():create("helicopter",vector():set(-160.0,-40.0,-610.0),128298,11 ) ,"helicopter1")
    db.actor:give_info_portion("krest_work_spawn")
  end
end

function spawn_military_tech_new(obj, spawn_item)	
  local packet = net_packet()
  obj:STATE_Write(packet)

	-- свойства cse_alife_object
	local game_vertex_id = packet:r_u16()
	local cse_alife_object__unk1_f32 = packet:r_float()
	local cse_alife_object__unk2_s32 = packet:r_s32()
	local level_vertex_id = packet:r_s32()
	local object_flags = packet:r_s32()
	local custom_data = packet:r_stringZ()
	local story_id = packet:r_s32()
	local cse_alife_object__unk3_s32 = packet:r_s32()

	-- свойства cse_visual
	local model_visual = packet:r_stringZ()
	local cse_visual__unk1_u8 = packet:r_u8()
	local motion_name
	if spawn_item == "helicopter" or "helicopter1" or "helicopter2"  then
		-- свойства cse_motion
		motion_name = packet:r_stringZ()
	end

	-- свойства cse_ph_skeleton
	local skeleton_name = packet:r_stringZ()
	local cse_ph_skeleton__unk1_u8 = packet:r_u8()
	local cse_ph_skeleton__unk2_u16 = packet:r_u16()
	local health 
	local cse_alife_helicopter__unk1_sz 
	local engine_sound 
		
	if spawn_item =="helicopter" or  "helicopter1" or "helicopter2"  then
		-- свойства cse_alife_helicopter
		cse_alife_helicopter__unk1_sz = packet:r_stringZ()
		engine_sound = packet:r_stringZ()
	elseif	spawn_item == "vehicle_btr" then
		health = packet:r_float()
	end
	
	-- теперь заполняем нужные параметры
	-- свойства cse_alife_object
	packet:w_begin(game_vertex_id)
	packet:w_float(cse_alife_object__unk1_f32)
	packet:w_s32(cse_alife_object__unk2_s32)
	packet:w_s32(level_vertex_id)
	object_flags = bit_not(5)	-- ~5 = 0xfffffffa
	packet:w_s32(object_flags)
	if spawn_item == "helicopter1" then
		packet:w_stringZ("[logic]\ncfg = scripts\\new\\helicopter1.ltx")
	elseif spawn_item == "helicopter" then
		packet:w_stringZ("[logic]\ncfg = scripts\\esc\\esc_blockpost_heli.ltx")	
	elseif spawn_item == "helicopter2" then
		packet:w_stringZ("[logic]\ncfg = scripts\\new\\helicopter2.ltx")
    elseif	spawn_item == "vehicle_btr" then
		packet:w_stringZ("[logic]\ncfg = scripts\\new\\vehicle_btr.ltx") 		
	end
	packet:w_s32(-1)
	packet:w_s32(cse_alife_object__unk3_s32)

	-- свойства cse_visual
	packet:w_stringZ(model_visual)
	packet:w_u8(cse_visual__unk1_u8)
	
	if spawn_item =="helicopter" or  "helicopter1" or "helicopter2"  then
		packet:w_stringZ(motion_name)		
	end 
	
	-- свойства cse_ph_skeleton
	skeleton_name = "idle"
	packet:w_stringZ(skeleton_name)
	packet:w_u8(cse_ph_skeleton__unk1_u8)
	packet:w_u16(cse_ph_skeleton__unk2_u16)

	if spawn_item =="helicopter" or  "helicopter1" or "helicopter2"  then
		-- свойства cse_alife_helicopter
		cse_alife_helicopter__unk1_sz = "idle"
		engine_sound = "alexmx\\helicopter"
		packet:w_stringZ(cse_alife_helicopter__unk1_sz)
		packet:w_stringZ(engine_sound)
	elseif  spawn_item == "vehicle_btr" then
		health = 1
		packet:w_float(health)
	end	
	-- считываем скорректированные параметры
	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
	
  news_manager.send_tip(db.actor, "Пипец мужики, Вертолёт", nil, nil, 30000)
end

function create_car_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-302.76281738281,-22.185157775879,211.21),40497,1788)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\monach_restr.ltx"
  rewrite_restrictor(se_obj, custom, 12.0)
end

function spawn_desant()
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil_master",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil_master",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil_master",vector():set(-122.6116,-9.454,-150.264),130421,44)
  local obj = alife():create("valet_mil_master",vector():set(-122.6116,-9.454,-150.264),130421,44)
end

function quest_info()
  local time_current = time_global()+ 5500
  if level.name()=="l04_darkvalley" and has_alife_info("electro_chimera_ucen_need") and has_alife_info("electro_chimera_ucen_dead") and not has_alife_info("ucen_need_metka_chimera_have") then
    db.actor:give_info_portion("ucen_need_metka_fail")
  elseif level.name()=="l06_rostok" and has_alife_info("gigant_strong_ucen_need") and has_alife_info("gigant_strong_ucen_dead") and not has_alife_info("ucen_need_metka_gigant_have") then
    db.actor:give_info_portion("ucen_need_metka_fail")
  elseif level.name()=="l01_escape" and has_alife_info("bloodsucker_strong_ucen_need") and has_alife_info("bloodsucker_strong_ucen_dead") and not has_alife_info("ucen_need_metka_bloodsucker_have") then
    db.actor:give_info_portion("ucen_need_metka_fail")
  elseif level.name()=="l05_bar" and db.actor:has_info("barman_work_have")  and not db.actor:has_info("barman_speech_start") then
    db.actor:give_info_portion("barman_speech_start")
  elseif level.name()=="l07_military" and has_alife_info("black_box_done") and 
  not has_alife_info("prizrak_about_pda_sms") then
    ogse_st_mgr.start_timer("prizrak_pda",math.random(20,30), "braad_test.prizrak_pda")
    db.actor:give_info_portion("prizrak_about_pda_sms")
  end

  if level.name()=="l02_garbage" and not db.actor:has_info("art_garbage_spawn") then
    local obj = alife():create("af_electra_flash",vector():set(-12.316145896912,18.28110504,117.60050964355),170444,354)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_flash",vector():set(-75.99243927002,20.78828811,112.10626220703),170444,354)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(-195.3737487793,3.43506217,208.96646118164),32824,345)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_ameba_slug",vector():set(-255.01333618164,2.5012269020081,97.402565002441),7662,339)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_sea-urchin",vector():set(-182.67608642578,1.77206,-321.47311401367),53729,689)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)
    db.actor:give_info_portion("art_garbage_spawn") 
  end 

  if level.name()=="l05_bar" and db.actor:has_info("fanat_recept_start")  and not db.actor:has_info("art_escape_spawn") then
    local obj = alife():create("gold_art",vector():set(75.451988220215,16.426797866821,34.290096),215114,294)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(270.66116333008,-8.7369184494019,-126.34954),377173,405)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("gold_art",vector():set(-234.88185119629,8.3708419799805,177.88945007324),16236,1337)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(-195.3737487793,3.43506217,208.96646118164),32824,345)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_ameba_slug",vector():set(-255.01333618164,2.5012269020081,97.402565002441),7662,339)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_sea-urchin",vector():set(-182.67608642578,1.77206,-321.47311401367),53729,689)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_moonlight",vector():set(4.7991132736206,-6.9216456,-72.931411743164),6850,2661)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_flash",vector():set(-83.463157653809,16.93710136,102.66344451904),165695,332)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_electra_flash",vector():set(-43.567665100098,22.385353,-104.83944702148),147517,297)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_dummy_battery",vector():set(119.39251708984,15.86196517,26.154205322266),274810,391)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(280.64120483398,-6.46071863,1.0314919948578),379939,390)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_night_star",vector():set(33.511577606201,-4.7631421089172,-361.11657714844),215278,841)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_soul",vector():set(-45.467483520508,3.7723202705383,-12.004273414612),129993,1017)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    local obj = alife():create("af_rusty_kristall",vector():set(59.396793365479,19.6898231506,156.72634887695),358866,97)
    local sobj = alife():object( obj.id )
    alife():use_ai_locations(sobj, false)

    db.actor:give_info_portion("art_escape_spawn") 
  end    
end

function ucen_electro()
  local sobj = alife():create("electro_chimera",vector():set(-56.7896347045898,0.25009277,57.5432243347168),108090,899)
  sobj.custom_data = "[logic]\ncfg = scripts\\new\\electro_chimera_ucen.ltx"
  alife():assign_story_id( sobj.id, 9820 )
end

function mini_time (actor, npc)
  return level.get_time_hours() >= 3 and level.get_time_hours() < 5
end 

function is_night (actor, npc)
  return level.get_time_hours() >= 0 and level.get_time_hours() < 6
end 

function is_day (actor, npc)
  return level.get_time_hours() >= 6 and level.get_time_hours() < 21
end   

function monach_tele( actor, npc)
  level.add_pp_effector ("blink.ppe", 234, false)       
  level.add_pp_effector("teleport.ppe", 2006, false) 
  db.actor:set_actor_position(patrol("monach_restr_actor_walk"):point(0))
  local dir = patrol("monach_restr_actor_look"):point(0):sub(patrol("monach_restr_actor_look"):point(0))
  db.actor:set_actor_direction(-dir:getH())
end

function drink_vodka()
	db.actor:eat(db.actor:object("vodka"))
end

function drink_adulin()
	db.actor:eat(db.actor:object("adulin"))
end

function set_lapsha()
  local npc,obj
	for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "atp_barman" then 
      npc:set_relation (game_object.enemy, db.actor)
    end	
  end 
end  
  
function monach_spawn()
  local obj = alife():create("monach_flame1",vector():set(-323.86444091797,-22.3211765289,215.06326293945),23717,1795)
  local obj = alife():create("monach_flame2",vector():set(-303.80130004883,-22.5906143188,223.89811706543),39952,1787)
  local obj = alife():create("monach_flame3",vector():set(-303.80130004883,-22.5906143188,223.89811706543),39952,1787)
  local obj = alife():create("monach_flame4",vector():set(-307.34295654297,-22.393926620483,201.0061340332),37061,1795)
  local obj = alife():create("monach_tele1",vector():set(-307.34295654297,-22.393926620483,201.0061340332),37061,1795)
  local obj = alife():create("monach_tele2",vector():set(-303.80130004883,-22.590614318848,223.89811706543),39952,1787)
  local obj = alife():create("monach_tele3",vector():set(-323.86444091797,-22.321176528931,215.06326293945),23717,1795)
  local obj = alife():create("monach_tele4",vector():set(-323.86444091797,-22.321176528931,215.06326293945),23717,1795)
end

function black_box_spawn()
  local obj = alife():create("box_black",vector():set(352.86376953125,-45.480,-196.2610168457),94349,2081)
  local sobj = alife():object( obj.id )
  alife():use_ai_locations(sobj, false)
end

function prizrak_pda()
  db.actor:give_info_portion("prizrak_about_pda_start")
end

function krest_info()
  db.actor:give_info_portion("krest_work_have")
end

function mad_npc()
  if level.name()=="l10u_bunker" and has_alife_info("kruglov_case_done") and 
  not has_alife_info("actor_v_bunker") then
    db.actor:give_info_portion("actor_v_bunker")
  end
end

function set_pri_priz()
  local npc,obj
	for i=0,65534 do 
    npc = level.object_by_id(i)
    if npc and npc:name() == "new_prizrak" then 
      npc:set_relation(game_object.friend, db.actor)
    end	
  end 
end 

function create_re_restr()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj then
      if obj and obj:name() == "pri_prizrak_restr" then
        obj.custom_data = "[logic]\ncfg = scripts\\new\\restr\\pri_prizrak_restr_new.ltx"
      end	
    end 
  end 
end

function sms_amulet()
  db.actor:give_info_portion("almaz_talk")
  news_manager.send_tip(db.actor, game.translate_string( "sms_amulet" ), nil, nil, 30000) 
end

function amulet_effect()
  level.add_pp_effector("teleport.ppe", 2006, false)
end

function create_final_restr()
  local se_obj = alife():create("space_restrictor",vector():set(0.054,-34.355,17.672),1757,2512)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\final_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_x16_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-66.073,-19.088,-158.844),15672,1490)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\x16_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

----------------------------------------new---------------------------------------------

function set_povodyr()
  local sim = alife()
  for a, obj in alife():objects() do
    if obj:section_name()=="dog_povodyr" then
      amk.add_spot_on_map(obj.id,"blue_location", game.translate_string( "set_povodyr" ))
      return
    end
  end
end

function create_lesnik_restr()
  local sr = alife():create("space_restrictor",vector():set(136.250,1.228,-123.958),475965,3085)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30159|]]..sr:name()..[[|nil %+lesnik_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_lesnik2_restr()
  local sr = alife():create("space_restrictor",vector():set(-347.986,-9.399,-8.740),271297,2978)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30160|]]..sr:name()..[[|nil %+lesnik2_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_vasil_restr()
  local sr = alife():create("space_restrictor",vector():set(-356.713,51.555,388.227),255773,2976)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30148|]]..sr:name()..[[|nil %+vasil_mesto1%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_vasil_restr1()
  local sr = alife():create("space_restrictor",vector():set(61.101,-7.051,-123.551),974192,2986)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30148|]]..sr:name()..[[|nil %+vasil_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_vasil_restr2()
  local sr = alife():create("space_restrictor",vector():set(61.362,-9.923,-182.203),975372,2986)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30148|]]..sr:name()..[[|nil %+vasil_mesto2%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_vasil2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-48.543,-13.200,-269.102),22468,1454)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vasil2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_zombi_restr()
  local sr = alife():create("space_restrictor",vector():set(-11.410,-11.880,-274.345),34615,1482)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30161|]]..sr:name()..[[|nil %+pomog_zombi%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_vasil2_restr1()
  local sr = alife():create("space_restrictor",vector():set(0.710,-11.748,-263.896),39537,1448)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30161|]]..sr:name()..[[|nil %+vasil_dovel%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function yantar_exit_restr()
  local se_obj = alife():create("space_restrictor",vector():set(174.770,-7.747,-90.987),133593,1451)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\yantar_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_skit_restr()
  local sr = alife():create("space_restrictor",vector():set(-66.298,6.267,-36.346),280800,3051)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30162|]]..sr:name()..[[|nil %+skit_prishli%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_postovoy_restr()
  local sr = alife():create("space_restrictor",vector():set(135.243,1.228,-126.111),474965,3085)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30162|]]..sr:name()..[[|nil %+postovoy_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_pripyat_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-163.414,-1.770,63.461),581,2141)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\pripyat_restr.ltx"
  rewrite_restrictor(se_obj, custom, 12.0)
end

------------------------------------bar_attak--------------------------------

function bar_attak_restr()
  local se_obj = alife():create("space_restrictor",vector():set(40.715,-0.001,238.610),23433,1244)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\bar_attak.ltx"
  rewrite_restrictor(se_obj, custom, 8.0)
end


function create_plichko_restr()
  local sr = alife():create("space_restrictor",vector():set(224.667,-5.448,125.996),56632,1198)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30176|]]..sr:name()..[[|nil %+plichko_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_attak7_restr()
  local sr = alife():create("space_restrictor",vector():set(136.671,-4.825,21.034),36897,1237)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30177|]]..sr:name()..[[|nil %+dolg_attak7_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_attak8_restr()
  local sr = alife():create("space_restrictor",vector():set(221.044,-0.011,-7.659),55112,1261)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30178|]]..sr:name()..[[|nil %+dolg_attak8_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_voronin_restr()
  local sr = alife():create("space_restrictor",vector():set(225.696,-5.248,131.531),56941,1198)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30179|]]..sr:name()..[[|nil %+voronin_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_mg_restr1()
  local se_obj = alife():create("space_restrictor",vector():set(-139.311,1.409,29.914),199578,3043)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mg_restr1.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_mg_restr2()
  local se_obj = alife():create("space_restrictor",vector():set(-91.460,-1.824,-24.650),194994,3043)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mg_restr2.ltx"
  rewrite_restrictor(se_obj, custom, 1.0)
end

function create_mg_restr3()
  local se_obj = alife():create("space_restrictor",vector():set(-167.624,-1.977,105.768),170409,3030)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mg_restr3.ltx"
  rewrite_restrictor(se_obj, custom, 1.0)
end

function create_mg_restr4()
  local se_obj = alife():create("space_restrictor",vector():set(31.439,-1.654,106.582),215372,3043)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mg_restr4.ltx"
  rewrite_restrictor(se_obj, custom, 1.0)
end

function create_vstrecha_restr()
  local sr = alife():create("space_restrictor",vector():set(-29.943,1.811,-3.966),896057,2926)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30190|]]..sr:name()..[[|nil %+barman_strelka_prishel%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_grek_restr()
  local sr = alife():create("space_restrictor",vector():set(93.115,-5.264,-132.060),1032152,2986)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30188|]]..sr:name()..[[|nil %+grek_mesto%]] 
  rewrite_restrictor(sr, custom, 2.0) 
end

function create_zahar_restr()
  local sr = alife():create("space_restrictor",vector():set(-398.245,57.244,375.462),183792,2976)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30195|]]..sr:name()..[[|nil %+zahar_mesto%]] 
  rewrite_restrictor(sr, custom, 2.0) 
end

function create_podmoga_restr()
  local sr = alife():create("space_restrictor",vector():set(-17.474,2.480,64.866),259615,88)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30197|]]..sr:name()..[[|nil %+podmoga_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_tolik_restr()
  local sr = alife():create("space_restrictor",vector():set(6.284,2.381,63.295),283083,89)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 9644|]]..sr:name()..[[|nil %+esc_tolik_help_have%]] 
  rewrite_restrictor(sr, custom, 10.0) 
end

function create_kapral_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-227.092,16.793,237.678),591550,2889)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\kapral_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_foster_restr()
  local sr = alife():create("space_restrictor",vector():set(-447.132,-0.948,-176.802),257369,2848)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30186|]]..sr:name()..[[|nil %+kapral_mesto%]] 
  rewrite_restrictor(sr, custom, 5.0) 
end

function create_brown_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-467.794,0.790,-153.783),227472,2839)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\brown_zvuk.ltx"
  rewrite_restrictor(se_obj, custom, 4.0)
end

function foster_zvuk_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-270.069,10.707,220.042),523335,2873)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\foster_zvuk.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_rostok_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-83.083,-15.536,-201.172),47811,1408)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\rostok_restr.ltx"
  rewrite_restrictor(se_obj, custom, 3.0)
end

function create_karina1_restr()
  local sr = alife():create("space_restrictor",vector():set(-27.499,-9.033,-173.841),820635,2986)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30189|]]..sr:name()..[[|nil %+karina_mesto%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_karina2_restr()
  local sr = alife():create("space_restrictor",vector():set(-411.336,0.687,58.455),160037,2978)
  local custom = [[[logic] 
  active = sr_idle 
  [sr_idle] 
  on_npc_in_zone = 30189|]]..sr:name()..[[|nil %+karina_prishli%]] 
  rewrite_restrictor(sr, custom, 1.0) 
end

function create_povodyr_restr()
  local se_obj = alife():create("space_restrictor",vector():set(193.017,2.700,-29.807),1568901,3007)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\povodyr_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

----------------------------------zvuki----------------------------------

function create_skit_trader_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-66.447,2.017,-44.366),280793,3059)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\skit_trader_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.1)
end

function create_antikvar_restr()
  local se_obj = alife():create("space_restrictor",vector():set(207.609,0.430,60.231),50435,1203)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\antikvar_restr.ltx"
  rewrite_restrictor(se_obj, custom, 4.0)
end

function create_cezar_restr()
  local se_obj = alife():create("space_restrictor",vector():set(29.068,-11.688,-280.074),54978,1480)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\cezar_restr.ltx"
  rewrite_restrictor(se_obj, custom, 4.0)
end

function create_graf_restr()
  local se_obj = alife():create("space_restrictor",vector():set(149.237,0.428,68.958),39928,1180)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\graf_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.1)
end

function create_mervin1_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-162.525,-1.755,66.612),581,2141)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin1_restr.ltx"
  rewrite_restrictor(se_obj, custom, 12.0)
end

function create_mervin2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(9.693,56.273,48.022),5205,2417)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_mervin3_restr()
  local se_obj = alife():create("space_restrictor",vector():set(101.323,4.003,123.453),215814,2182)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin3_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_prince_restr()
  local se_obj = alife():create("space_restrictor",vector():set(659.836,-43.877,168.970),227063,1915)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\prince_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_pekar_restr()
  local se_obj = alife():create("space_restrictor",vector():set(109.822,-19.864,-269.886),1115781,2961)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\pekar_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_monolit_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-25.688,0.001,691.280),178968,2618)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\monolit_restr.ltx"
  rewrite_restrictor(se_obj, custom, 30.0)
end

function create_dialog_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-25.688,0.001,691.280),178968,2618)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\dialog_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_chaes2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(116.323,-0.080,523.742),178968,2618)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\chaes2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 180.0)
end

function create_sled2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(4.635,5.119,70.967),26518,2659)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\sled2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_kristall_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-31.369,20.150,646.914),178968,2618)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\kristall_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_strelok_restr()
  local se_obj = alife():create("space_restrictor",vector():set(405.769,36.877,122.832),138164,2600)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\strelok_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_ugroza_restr()
  local se_obj = alife():create("space_restrictor",vector():set(105.086,38.402,144.396),60577,2563)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\ugroza_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_tele9_restr()
  local se_obj = alife():create("space_restrictor",vector():set(578.559,18.205,294.443),174619,2613)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\tele9_restr.ltx"
  rewrite_restrictor(se_obj, custom, 8.0)
end

function create_end_restr()
  local se_obj = alife():create("space_restrictor",vector():set(444.978,10.149,152.687),147677,2599)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\end_restr.ltx"
  rewrite_restrictor(se_obj, custom, 8.0)
end

------------------------------rule_end---------------------------------

function create_rule_restr()
  local se_obj = alife():create("space_restrictor",vector():set(554.277,150.700,202.080),227423,2635)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\rule_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_sarfinal_restr()
  local se_obj = alife():create("space_restrictor",vector():set(11.325,55.594,28.993),3729,2464)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\sarfinal_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_vano_restr()
  local se_obj = alife():create("space_restrictor",vector():set(84.903,-1.135,74.312),1076579,2948)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vano_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_superfinal_restr()
  local se_obj = alife():create("space_restrictor",vector():set(885.711,15.099,123.097),231729,2635)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\superfinal_restr.ltx"
  rewrite_restrictor(se_obj, custom, 3.0)
end

function create_vhod_restr()
  local se_obj = alife():create("space_restrictor",vector():set(49.777,3.935,76.576),1021308,2947)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\vhod_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_maroder_restr()
  local se_obj = alife():create("space_restrictor",vector():set(2.004,10.026,42.733),946230,2939)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\maroder_restr.ltx"
  rewrite_restrictor(se_obj, custom, 3.0)
end

function create_maroder2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(49.777,3.935,76.576),1021308,2947)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\maroder2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_nato_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-448.229,1.730,-117.823),256382,2844)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_nato1_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-525.222,1.256,-139.308),140364,2829)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato1_restr.ltx"
  rewrite_restrictor(se_obj, custom, 10.0)
end

function create_nato2_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-460.865,0.784,-148.654),237565,2839)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato2_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_nato3_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-460.584,5.152,-139.673),237584,2841)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato3_restr.ltx"
  rewrite_restrictor(se_obj, custom, 4.0)
end

function create_nato4_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-520.037,0.415,-158.050),147640,2828)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato4_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_nato5_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-528.454,2.805,-170.965),135158,2828)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato5_restr.ltx"
  rewrite_restrictor(se_obj, custom, 2.0)
end

function create_nato6_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-517.255,0.124,-202.396),151632,2830)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato6_restr.ltx"
  rewrite_restrictor(se_obj, custom, 3.0)
end

function create_nato7_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-518.862,-0.783,-186.421),149622,2830)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\nato7_restr.ltx"
  rewrite_restrictor(se_obj, custom, 8.0)
end

function create_antirostok_restr()
  local se_obj = alife():create("space_restrictor",vector():set(40.096,-0.567,140.467),21496,1247)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\antirostok_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_antiagro_restr()
  local se_obj = alife():create("space_restrictor",vector():set(-128.391,-3.960,-139.923),12,719)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\antiagro_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function create_iuda_restr()
  local se_obj = alife():create("space_restrictor",vector():set(59.567,12.359,7.120),9808,2437)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\iuda_restr.ltx"
  rewrite_restrictor(se_obj, custom, 1.0)
end

function create_solomonchik_restr()
  local se_obj = alife():create("space_restrictor",vector():set(67.891,5.041,97.771),53648,2537)
  local custom = "[logic]\ncfg = scripts\\new\\solomonchik_restr.ltx"
  rewrite_restrictor(se_obj, custom, 3.0)
end

function create_noweapons_restr1()
  local se_obj = alife():create("space_restrictor",vector():set(-100.936,-16.466,-46.323),1544,755)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\agr_noweapon_newrestr1.ltx"
  rewrite_restrictor(se_obj, custom, 80.0)
end

function create_noweapons_restr2()
  local se_obj = alife():create("space_restrictor",vector():set(-71.541,-4.001,-121.858),3323,798)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\agr_noweapon_newrestr2.ltx"
  rewrite_restrictor(se_obj, custom, 80.0)
end

function create_mon5_restr()
  local se_obj = alife():create("space_restrictor",vector():set(34.138,13.215,-18.271),6620,2453)
  local custom = "[logic]\ncfg = scripts\\new\\restr\\mon5_restr.ltx"
  rewrite_restrictor(se_obj, custom, 5.0)
end

function assing_cd_and_sid( sobj, cd, sid )
  sobj.custom_data = cd
  if sid then
    alife():assign_story_id( sobj.id, sid )
  end
end