
local function on_take(obj, sobj)
    if obj:section() == "part2" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part2")
        alife():release(sobj)
    elseif obj:section() == "part3" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part3")
        alife():release(sobj)
    elseif obj:section() == "part4" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part4")
        alife():release(sobj)
    elseif obj:section() == "part5" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part5")
        alife():release(sobj)
    elseif obj:section() == "part6" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part6")
        alife():release(sobj)
    elseif obj:section() == "part7" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part7")
        alife():release(sobj)
    elseif obj:section() == "part8" and db.actor:has_info("semeckii_treasure_start") then
        db.actor:give_info_portion("semeckii_treasure_part8")
        alife():release(sobj)
    elseif obj:section() == "money_gg" then
        local money_actor = ogse.load_var("money_actor", 0)
        db.actor:give_money(money_actor)
        alife():release(sobj)
    elseif obj:section() == "money5" then
        db.actor:give_money(5000)
        alife():release(sobj)
    elseif obj:section() == "money10" then
        db.actor:give_money(10000)
        alife():release(sobj)
    elseif obj:section() == "money15" then
        db.actor:give_money(15000)
        alife():release(sobj)
    elseif obj:section() == "money20" then
        db.actor:give_money(20000)
        alife():release(sobj)
    elseif obj:section() == "money25" then
        db.actor:give_money(25000)
        alife():release(sobj)
    elseif obj:section() == "money30" then
        db.actor:give_money(30000)
        alife():release(sobj)
    elseif obj:section() == "money50" then
        db.actor:give_money(50000)
        alife():release(sobj)
    elseif obj:section() == "af_snake_eye" and not has_alife_info("snake_dialog_have") then
        db.actor:give_info_portion("snake_dialog_have")
    elseif obj:section() == "amulet_1" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_2") and db.actor:object("amulet_3") and db.actor:object("amulet_4")
        and db.actor:object("amulet_5") and db.actor:object("amulet_6") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif obj:section() == "amulet_2" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_1") and db.actor:object("amulet_3") and db.actor:object("amulet_4")
        and db.actor:object("amulet_5") and db.actor:object("amulet_6") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif obj:section() == "amulet_3" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_1") and db.actor:object("amulet_2") and db.actor:object("amulet_4")
        and db.actor:object("amulet_5") and db.actor:object("amulet_6") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif obj:section() == "amulet_4" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_1") and db.actor:object("amulet_2") and db.actor:object("amulet_3")
        and db.actor:object("amulet_5") and db.actor:object("amulet_6") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif obj:section() == "amulet_5" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_1") and db.actor:object("amulet_2") and db.actor:object("amulet_3") and
            db.actor:object("amulet_4") and db.actor:object("amulet_6") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif obj:section() == "amulet_6" and not has_alife_info("amulet_sobral") then
        if db.actor:object("amulet_1") and db.actor:object("amulet_2") and db.actor:object("amulet_3")
        and db.actor:object("amulet_4") and db.actor:object("amulet_5") then
            db.actor:give_info_portion("amulet_sobral")
        end
    elseif level.name() == "l10_red_forest" then
        if obj:section() == "mandra" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        elseif obj:section() == "zahar_box" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        end
    elseif level.name() == "l13_deep" then
        if db.actor:has_info("nato_enemy") and not has_alife_info("nato_zasada") then
            db.actor:give_info_portion("nato_zasada")
        elseif obj:section() == "box_vano" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        end
    elseif level.name() == "l03_agroprom" then
        if obj:section() == "af_agro" and not has_alife_info("pauk_agro_spawn") then
            db.actor:give_info_portion("pauk_agro_spawn")
        end
    elseif level.name() == "l04_darkvalley" then
        if obj:section() == "af_snake_eye" and not has_alife_info("snake_dialog_begin") then
            db.actor:give_info_portion("snake_dialog_begin")
        elseif obj:section() == "wpn_knife" and db.actor:has_info("doronin_help_start") then
            db.actor:give_info_portion("doronin_help_val")
        end
    elseif level.name() == "l04u_labx18" then
        if obj:section() == "detector_elite_bad" then
            db.actor:give_info_portion("levsha_remont_detector")
        end
    elseif level.name() == "l07_military" then
        if obj:section() == "notebook_x16" and db.actor:has_info("sidr_lab_have") and
            not db.actor:has_info("mil_klyak_help_start") then
            klyak_mil_spawn()
        elseif obj:section() == "new_plan" then
            level_tasks.remove_location_by_id(obj:id(), "red_location")
        end
    elseif level.name() == "l10_radar" then
        if obj:section() == "amulet_5" and not has_alife_info("pauk_les_spawn") then
            db.actor:give_info_portion("pauk_les_spawn")
        end
    elseif level.name() == "l10u_bunker" then
        if obj:section() == "book_zombi" and not has_alife_info("pauk_x10_spawn") then
            db.actor:give_info_portion("pauk_x10_spawn")
        elseif obj:section() == "amk_zapiska" then
            db.actor:give_info_portion("info_amk_recipt_sopl_dikoobraz")
            alife():release(sobj)
        end
    elseif level.name() == "l12_stancia" then
        if obj:section() == "wpn_knife" and db.actor:has_info("haron_spy_start") then
            db.actor:give_info_portion("haron_spy_spawn")
        end
    elseif level.name() == "l12_stancia_2" then
        if obj:section() == "aes_case1" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        elseif obj:section() == "aes_case2" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        elseif obj:section() == "aes_case3" then
            level_tasks.remove_location_by_id(obj:id(), "crlc_big")
        end
    elseif level.name() == "l12u_sarcofag" then
        if obj:section() == "amk_zapiska" then
            db.actor:give_info_portion("info_amk_recipt_almaz_kolobok")
            alife():release(sobj)
        end
    elseif obj:section() == "flash_ban" and db.actor:has_info("voronin_nychka_jila") then
        level_tasks.remove_location_by_id(obj:id(), "blue_location")
        alife():release(sobj)
    elseif obj:section() == "doc_peredatchik" then
        level_tasks.remove_location_by_id(obj:id(), "crlc_big")
    end
end

local function on_first_update()

    if level.name() == "l01_escape" then
        if not has_alife_info("actor_na_kordon") then
            db.actor:give_info_portion("actor_na_kordon")
        end

        if db.actor:has_info("ucen_need_metka_start") then
            db.actor:give_info_portion("bloodsucker_strong_ucen_need")
        end
    end

    if level.name() == "l02_garbage" then
        if not db.actor:has_info("art_garbage_spawn") then
            spawn_ai_location("af_electra_flash", vector():set(-12.316145896912, 18.28110504, 117.60050964355), "l02_garbage")
            spawn_ai_location("af_rusty_sea-urchin", vector():set(-75.99243927002, 20.78828811, 112.10626220703), "l02_garbage")
            spawn_ai_location("af_rusty_kristall", vector():set(-195.3737487793, 3.43506217, 208.96646118164), "l02_garbage")
            spawn_ai_location("af_ameba_slug", vector():set(-255.01333618164, 2.5012269020081, 97.402565002441), "l02_garbage")
            db.actor:give_info_portion("art_garbage_spawn")
        end

        if has_alife_info("krest_razborka_start") and not has_alife_info("krest_razborka_spawn") then
            db.actor:give_info_portion("krest_razborka_spawn")
        end

        if has_alife_info("bes_help_levsha_start") and not has_alife_info("bes_smart_done") then
            db.actor:give_info_portion("bes_smart_done")
        end

        if has_alife_info("sledopyt_first_dialog_zasada") and not has_alife_info("fantom_svalka1_spawn") then
            db.actor:give_info_portion("fantom_svalka1_spawn")
        end

        if has_alife_info("mayor_yarofeev_start") and not has_alife_info("fantom_svalka2_spawn") then
            db.actor:give_info_portion("fantom_svalka2_spawn")
        end

        if has_alife_info("potapov_first_dialog_start") and not has_alife_info("vypolzen_boloto_spawn") then
            db.actor:give_info_portion("vypolzen_boloto_spawn")
        end

        if has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_mini_spawn") then
            db.actor:give_info_portion("izlom_mini_spawn")
        end

        if has_alife_info("sledopyt_first_dialog_done") and not has_alife_info("doctor_und_del") then
            db.actor:give_info_portion("doctor_und_del")
        end

        if has_alife_info("bes_patron_start") and not has_alife_info("bes_patron_spawn") then
            ogse_st_mgr.start_timer("bes_zasada", math.random(500, 600), "braad_test.bes_zasada")
            db.actor:give_info_portion("bes_patron_spawn")
        end
    end

    if level.name() == "l03_agroprom" then
        if has_alife_info("sledopyt_first_dialog_start") and not has_alife_info("taynik_sms") then
            db.actor:give_info_portion("taynik_sms")
        end

        if not has_alife_info("actor_na_agro") then
            db.actor:give_info_portion("actor_na_agro")
        end

        if has_alife_info("lazarev_dialog_start") and not has_alife_info("vypolzen_lazarev_spawn") then
            db.actor:give_info_portion("vypolzen_lazarev_spawn")
        end
    end

    if level.name() == "l03u_agr_underground" then
        if not has_alife_info("teleport_spawn") then
            db.actor:give_info_portion("teleport_spawn")
        end

        if has_alife_info("sledopyt_first_dialog_start") and not has_alife_info("doctor_und_spawn") then
            db.actor:give_info_portion("doctor_und_spawn")
        end

        if has_alife_info("sledopyt_spawn") and not has_alife_info("str_spawn") then
            db.actor:give_info_portion("str_spawn")
        end
    end

    if level.name() == "l04_darkvalley" then
        if not has_alife_info("actor_na_darkvalley") then
            db.actor:give_info_portion("actor_na_darkvalley")
        end

        if db.actor:has_info("ucen_need_metka_start") and db.actor:dont_has_info("electro_chimera_ucen_need") then
            ucen_electro()
            db.actor:give_info_portion("electro_chimera_ucen_need")
        end
    end

    if level.name() == "l04u_labx18" then
        if db.actor:has_info("mil_klyak_lab_start") and not has_alife_info("mil_klyak_lab_spawn") then
            db.actor:give_info_portion("mil_klyak_lab_spawn")
        end
    end

    if level.name() == "l05_bar" then
        if not has_alife_info("potapov_spawn") then
            db.actor:give_info_portion("potapov_spawn")
        end

        if has_alife_info("sidr_lab_start") and not has_alife_info("graf_sms") then
            db.actor:give_info_portion("graf_sms")
        end

        if db.actor:has_info("barman_work_have") and not db.actor:has_info("barman_speech_start") then
            db.actor:give_info_portion("barman_speech_start")
        end

        if has_alife_info("levsha_daet_dobro") and has_alife_info("sidr_nacalo_start") and
            not has_alife_info("sledopyt_spawn") then
            db.actor:give_info_portion("sledopyt_spawn")
        end

        if has_alife_info("sidor_poslanie_dialog_start") and not has_alife_info("killer_attak_start") then
            db.actor:give_info_portion("killer_attak_start")
        end
    end

    if level.name() == "l06_rostok" then
        if db.actor:has_info("ucen_need_metka_start") then
            db.actor:give_info_portion("gigant_strong_ucen_need")
        end

        if has_alife_info("lektor_dialog_start") and not has_alife_info("lektor_spawn") then
            db.actor:give_info_portion("lektor_spawn")
        end

        if level.name() == "l06_rostok" and has_alife_info("ucen_need_metka_start") and
            not has_alife_info("fantom_rostok_spawn") then
            db.actor:give_info_portion("fantom_rostok_spawn")
        end

        if has_alife_info("doronin_help_begin") and not has_alife_info("fantom_rostok2_spawn") then
            db.actor:give_info_portion("fantom_rostok2_spawn")
        end
    end

    if level.name() == "l07_military" then
        if not has_alife_info("actor_na_scladah") then
            spawn_patrol("add_military", "mil_voen_lager_voen17_walk")
            spawn_patrol("add_military", "mil_voen_lager_voen17_walk")
            spawn_patrol("add_military", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_ambush", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_ambush", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_ambush", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_ambush", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_specnaz", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_specnaz", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_specnaz", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_specnaz", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_sniper", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_sniper", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_sniper", "mil_voen_lager_voen17_walk")
            spawn_patrol("dark_military_sniper", "mil_voen_lager_voen17_walk")
            db.actor:give_info_portion("actor_na_scladah")
        end

        if has_alife_info("finish_put_start") and not has_alife_info("klyak_sms") then
            db.actor:give_info_portion("klyak_sms")
        end
    end

    if level.name() == "l08_yantar" then
        if not has_alife_info("vasil2_yantar") then
            db.actor:give_info_portion("vasil2_yantar")
        end

        if not has_alife_info("actor_na_yantar") then
            db.actor:give_info_portion("actor_na_yantar")
        end

        if has_alife_info("graf_tri_dialog_start") and not has_alife_info("tsezar_spawn") then
            db.actor:give_info_portion("tsezar_spawn")
        end
    end

    if level.name() == "l08u_brainlab" then
        if has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_x16_spawn") then
            db.actor:give_info_portion("izlom_x16_spawn")
        end

        if has_alife_info("potapov_first_dialog_start") and not has_alife_info("restr_x16_spawn") then
            db.actor:give_info_portion("restr_x16_spawn")
        end
    end

    if level.name() == "l10_radar" then
        if not has_alife_info("actor_na_radare") then
            db.actor:give_info_portion("actor_na_radare")
        end

        if has_alife_info("sahar_shlem_have") and not has_alife_info("crazy_delete") then
            db.actor:give_info_portion("crazy_delete")
        end

        if has_alife_info("graf_second_dialog_start") and not has_alife_info("prince_spawn") then
            db.actor:give_info_portion("prince_spawn")
        end

        if has_alife_info("potapov_first_dialog_start") and not has_alife_info("izlom_blue_spawn") then
            db.actor:give_info_portion("izlom_blue_spawn")
        end

        if has_alife_info("black_box_start") and not has_alife_info("izlom_radar_spawn") then
            db.actor:give_info_portion("izlom_radar_spawn")
        end

        if has_alife_info("black_box_start") and not has_alife_info("fantom_radar2_spawn") then
            db.actor:give_info_portion("fantom_radar2_spawn")
        end
    end

    if level.name() == "l10_red_forest" then
        if not has_alife_info("lesnik2_mesto") then
            db.actor:give_info_portion("lesnik2_mesto")
        end
    end

    if level.name() == "l10u_bunker" then
        if has_alife_info("kruglov_case_done") and not has_alife_info("actor_v_bunker") then
            db.actor:give_info_portion("actor_v_bunker")
        end
    end

    if level.name() == "l11_pripyat" then
        if not has_alife_info("my_spawn_est") then
            spawn_mervin()
            db.actor:give_info_portion("my_spawn_est")
        end

        if db.actor:has_info("haron_doktor_start") then
            db.actor:give_info_portion("haron_doktor_pripyat_spawn")
        end

        if has_alife_info("finish_put_start") and not has_alife_info("zombie_spawn") then
            db.actor:give_info_portion("zombie_spawn")
        end

        if has_alife_info("new_urok_dialog_start") and not has_alife_info("artefact_new_spawn") then
            db.actor:give_info_portion("artefact_new_spawn")
        end
    end

    if level.name() == "l12_stancia" then
        if has_alife_info("prizrak_kill_start") and not has_alife_info("doctor_sms") then
            ogse_st_mgr.start_timer("sms_doc", math.random(100, 120), "braad_test.sms_doc")
            db.actor:give_info_portion("doctor_sms")
        end

        if db.actor:has_info("haron_doktor_have") then
            db.actor:give_info_portion("mahon_sar_finish")
        end

        if has_alife_info("actor_poslednii_put") and not has_alife_info("chaes_final_spawn") then
            db.actor:give_info_portion("chaes_final_spawn")
        end

        if has_alife_info("actor_poslednii_put") and not has_alife_info("pauk_final_spawn") then
            db.actor:give_info_portion("pauk_final_spawn")
        end

        if has_alife_info("second_urok_dialog_done") and not has_alife_info("mervin2_delete") then
            db.actor:give_info_portion("mervin2_delete")
        end
    end

    if level.name() == "l12_stancia_2" then
        if has_alife_info("actor_poslednii_put") and not has_alife_info("sled_spawn") then
            db.actor:give_info_portion("sled_spawn")
        end

        if db.actor:has_info("haron_need_stalker_start") then
            db.actor:give_info_portion("haron_need_stalker_spawn")
        end

        if has_alife_info("semecky_first_dialog_done") and not has_alife_info("semecky_delete") then
            db.actor:give_info_portion("semecky_delete")
        end

        if has_alife_info("monolit_bunker_doc_start") and not has_alife_info("monolit_bunker_doc_spawn") then
            solomon_grabs()
            ograblen()
            z_teleport.aes_tele()
            db.actor:give_info_portion("monolit_bunker_doc_spawn")
        end
    end

    if level.name() == "l12u_sarcofag" then

        if has_alife_info("magomet_start_dialog_start") and not has_alife_info("semecky_spawn") then
            db.actor:give_info_portion("semecky_spawn")
        end

        if has_alife_info("sled_dialog_start") and not has_alife_info("vhod_new") then
            db.actor:give_info_portion("vhod_new")
        end

        if has_alife_info("mervin_start_begin") and not has_alife_info("mervin1_delete") then
            db.actor:give_info_portion("mervin1_delete")
        end

        if not db.actor:has_info("esc_serious_talk") then
            alife_create("sar_zapiska_ruk", "l12u_sarcofag", vector():set(-18.311, 52.612, 10.153))
            alife_create("rad_zapiska_ruk", "l10u_bunker", vector():set(-18.195, -23.519, -11.307))

            spawn_ai_location("gold_art", vector():set(-234.881, 8.371, 177.889), "l06_rostok")
            spawn_ai_location("gold_art", vector():set(-234.881, 8.371, 177.889), "l06_rostok")
            spawn_ai_location("gold_art", vector():set(193.804, 0.0945, 71.867), "l05_bar")
            spawn_ai_location("gold_art", vector():set(75.452, 16.427, 34.290), "l02_garbage")
            spawn_ai_location("gold_art", vector():set(270.661, -8.737, -126.349), "l02_garbage")
            spawn_ai_location("gold_art", vector():set(86.187, 0.054, 49.023), "l08_yantar")
            spawn_ai_location("gold_art", vector():set(-81.021, -0.925, 157.556), "l01_escape")

            spawn_ai_location("af_fuzz_kolobok", vector():set(67.825, -0.371, -74.097), "l08_yantar")
            spawn_ai_location("af_dummy_glassbeads", vector():set(32.647, 5.580, -12.673), "l08u_brainlab")
            spawn_ai_location("af_rusty_sea-urchin", vector():set(-154.364, -0.286, 9.884), "l07_military")
            spawn_ai_location("af_rusty_sea-urchin", vector():set(660.325, -43.885, 176.851), "l10_radar")
            spawn_ai_location("af_electra_flash", vector():set(-83.562, 17.036, 102.596), "l02_garbage")
            spawn_ai_location("af_electra_flash", vector():set(-43.371, 24.142, -104.865), "l02_garbage")
            spawn_ai_location("af_dummy_battery", vector():set(119.392, 15.862, 26.154), "l02_garbage")
            spawn_ai_location("af_rusty_kristall", vector():set(280.641, -6.460, 1.031), "l02_garbage")
            spawn_ai_location("af_night_star", vector():set(33.511, -4.763, -361.116), "l04_darkvalley")
            spawn_ai_location("af_soul", vector():set(-45.467, 3.772, -12.004), "l04_darkvalley")
            spawn_ai_location("af_rusty_kristall", vector():set(59.396, 19.689, 156.726), "l01_escape")

            db.actor:give_info_portion("esc_serious_talk")
        end
    end

    if level.name() == "l12u_control_monolith" then
        if has_alife_info("actor_poslednii_put") and not has_alife_info("gromov_spawn") then
            db.actor:give_info_portion("gromov_spawn")
        end

        if has_alife_info("actor_poslednii_put") and not has_alife_info("actor_finish") then
            db.actor:give_info_portion("actor_finish")
        end
    end
end

local function on_info(npc, info_id)

    if level.name() == "l10_red_forest" then
        if has_alife_info("babka_dialog_start") and not has_alife_info("babka_del") then
            db.actor:give_info_portion("babka_del")
        end
    end

    if level.name() == "l01_escape" then
        if has_alife_info("mayor_yarofeev_start") and not has_alife_info("mayor_yarofeev_spawn") then
            db.actor:give_info_portion("mayor_yarofeev_spawn")
        end

        if has_alife_info("mayor_yarofeev_done") and not has_alife_info("sidr_sms_info") then
            ogse_st_mgr.start_timer("sms_sidr", math.random(10, 20), "braad_test.sms_sidr")
            db.actor:give_info_portion("sidr_sms_info")
        end
    end

    if level.name() == "l03_agroprom" then
        if has_alife_info("kruglov_art_have") then
            contr_art_spawn()
        end
    end

    if level.name() == "l04_darkvalley" then
        if has_alife_info("doronin_help_have") and not has_alife_info("naem_td_spawn") then
            db.actor:give_info_portion("naem_td_spawn")
        end
    end

    if level.name() == "l05_bar" then
        if has_alife_info("dolg_attak_dialog_start") and not has_alife_info("sledopyt_delete") then
            db.actor:give_info_portion("sledopyt_delete")
        end
    end

    if level.name() == "l11_pripyat" then
        if has_alife_info("prizrak_kill_speak") and not has_alife_info("mono_prizrak_spawn") then
            ogse_st_mgr.start_timer("mono_prizrak_spawn", math.random(70, 80), "braad_test.mono_prizrak_spawn")
            db.actor:give_info_portion("mono_prizrak_spawn")
        end

        if has_alife_info("ubity_mervina_done") and not has_alife_info("vozvrat_sms") then
            db.actor:give_info_portion("vozvrat_sms")
        end

        if has_alife_info("prizrak_help_have") and not has_alife_info("haron_sms") then
            ogse_st_mgr.start_timer("sms_new", math.random(100, 120), "braad_test.sms_new")
            db.actor:give_info_portion("haron_sms")
        end
    end

    if level.name() == "l12_stancia_2" then
        if has_alife_info("control_monolit_have") and not has_alife_info("keys_sms") then
            db.actor:give_info_portion("keys_sms")
        end
    end

    if level.name() == "l12u_sarcofag" then
        if has_alife_info("haron_naem_done") and not has_alife_info("mervin3_spawn") then
            db.actor:give_info_portion("mervin3_spawn")
        end
    end

    if level.name() == "l12u_control_monolith" then
        if has_alife_info("gromov_first_dialog_done") and not has_alife_info("gromov_del") then
            db.actor:give_info_portion("gromov_del")
        end
    end

    if has_alife_info("semeckii_treasure_start") and not has_alife_info("semeckii_treasure_article") then
        db.actor:give_info_portion("semeckii_treasure_article")
    end

    if has_alife_info("black_box_done") and not has_alife_info("prizrak_about_pda_sms") then
        ogse_st_mgr.start_timer("prizrak_pda", math.random(20, 30), "braad_test.prizrak_pda")
        db.actor:give_info_portion("prizrak_about_pda_sms")
    end

    if (has_alife_info("mil_lucash_dead") or has_alife_info("mil_blockpost_leader_dead"))
    and has_alife_info("mil_lucash_help_start") and not has_alife_info("mil_lucash_help_done") then
        db.actor:give_info_portion("mil_lucash_help_fail")
    end

    if (has_alife_info("levsha_dead") or has_alife_info("bes_dead")) and has_alife_info("bes_help_levsha_start")
    and not has_alife_info("bes_help_levsha_done") then
        db.actor:give_info_portion("bes_help_levsha_fail")
    end

    if has_alife_info("fedya_razboinik_see") and not has_alife_info("sveeblov_predatel_vpered") then -- Тут глянуть почему он не видит
        db.actor:give_info_portion("sveeblov_predatel_fail")
    end

    if has_alife_info("aes_solmon_have") and not has_alife_info("aes_solmon_sms") then
        ogse_st_mgr.start_timer("sms_solomon", math.random(20, 30), "braad_test.sms_solomon")
        db.actor:give_info_portion("aes_solmon_sms")
    end

    if db.actor:has_info("fanat_recept_start") and not db.actor:has_info("art_escape_spawn") then
        spawn_ai_location("gold_art", vector():set(75.451988220215, 16.426797866821, 34.290096), "l02_garbage")
        spawn_ai_location("gold_art", vector():set(270.66116333008, -8.7369184494019, -126.34954), "l02_garbage")
        spawn_ai_location("gold_art", vector():set(-234.88185119629, 8.3708419799805, 177.88945007324), "l06_rostok")
        spawn_ai_location("af_rusty_kristall", vector():set(-195.3737487793, 3.43506217, 208.96646118164), "l02_garbage")
        spawn_ai_location("af_ameba_slug", vector():set(-255.01333618164, 2.5012269020081, 97.402565002441), "l02_garbage")
        spawn_ai_location("af_rusty_sea-urchin", vector():set(-182.67608642578, 1.77206, -321.47311401367), "l03_agroprom")
        spawn_ai_location("af_electra_moonlight", vector():set(4.7991132736206, -6.9216456, -72.931411743164), "l10u_bunker")
        spawn_ai_location("af_electra_flash", vector():set(-83.463157653809, 16.93710136, 102.66344451904), "l02_garbage")
        spawn_ai_location("af_electra_flash", vector():set(-43.567665100098, 22.385353, -104.83944702148), "l02_garbage")
        spawn_ai_location("af_dummy_battery", vector():set(119.39251708984, 15.86196517, 26.154205322266), "l01_escape")
        spawn_ai_location("af_rusty_kristall", vector():set(280.64120483398, -6.46071863, 1.0314919948578), "l02_garbage")
        spawn_ai_location("af_night_star", vector():set(33.511577606201, -4.7631421089172, -361.11657714844), "l04_darkvalley")
        spawn_ai_location("af_soul", vector():set(-45.467483520508, 3.7723202705383, -12.004273414612), "l04_darkvalley")
        spawn_ai_location("af_rusty_kristall", vector():set(59.396793365479, 19.6898231506, 156.72634887695), "l01_escape")

        db.actor:give_info_portion("art_escape_spawn")
    end

    if has_alife_info("garbage_stalker_wound_dead") and has_alife_info("knyaz_dolg_start")
    and not has_alife_info("knyaz_dolg_have") then
        db.actor:give_info_portion("knyaz_dolg_have")
    end

    if has_alife_info("valet_dead") and has_alife_info("krest_work_start") and not has_alife_info("krest_work_have") then
        db.actor:give_info_portion("krest_work_fail")
    end

    if (has_alife_info("krest_dead") and has_alife_info("krest_razborka_spawn")
    and not has_alife_info("krest_razborka_done")) or ((has_alife_info("razbor_ban1_see") or has_alife_info("razbor_ban2_see") or has_alife_info("razbor_ban3_see") 
    or has_alife_info("razbor_ban4_see") or has_alife_info("razbor_ban5_see"))
    and has_alife_info("krest_razborka_spawn") and not has_alife_info("krest_razborka_begin")) then
        db.actor:give_info_portion("krest_razborka_fail")
    end

    if (has_alife_info("volk_dead") or has_alife_info("esc_fanat_new_dead")) and has_alife_info("derevna_stalker_start")
    and not has_alife_info("derevna_stalker_done") then
        db.actor:give_info_portion("derevna_stalker_fail")
    end

    if (has_alife_info("ucen_ohr1_see") or has_alife_info("ucen_ohr2_see") or has_alife_info("ucen_ohr3_see")) 
    and has_alife_info("doronin_help_val") and not has_alife_info("doronin_help_have") then
        db.actor:give_info_portion("doronin_help_fail")
    end

    if has_alife_info("electro_chimera_ucen_need") and has_alife_info("electro_chimera_ucen_dead")
    and not has_alife_info("ucen_need_metka_chimera_have") then
        db.actor:give_info_portion("ucen_need_metka_fail")
    end

    if has_alife_info("gigant_strong_ucen_need") and has_alife_info("gigant_strong_ucen_dead")
    and not has_alife_info("ucen_need_metka_gigant_have") then
        db.actor:give_info_portion("ucen_need_metka_fail")
    end

    if has_alife_info("bloodsucker_strong_ucen_need") and has_alife_info("bloodsucker_strong_ucen_dead")
    and not has_alife_info("ucen_need_metka_bloodsucker_have") then
        db.actor:give_info_portion("ucen_need_metka_fail")
    end
end

local haronp = {
    [1] = {x = 23.153, y = -4.680, z = 3.578},
    [2] = {x = 18.936, y = -0.405, z = 13.346},
    [3] = {x = 20.920, y = -3.425, z = 13.356}
}

function first_burer()
    local obj = spawn_patrol("burer_normal", "sar_krovosos_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer1.ltx"

    local obj = spawn_patrol("burer_normal", "sar_krovosos_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer2.ltx"

    local obj = spawn_patrol("burer_normal", "sar_burer2_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer3.ltx"

    local obj = spawn_patrol("burer_normal", "sar_burer2_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer4.ltx"

    local obj = spawn_patrol("burer_normal", "sar_burer2_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer5.ltx"

    local obj = spawn_patrol("burer_normal", "sar_burer2_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\burer6.ltx"

    local a = haronp[math.random(1, 3)]
    spawn_ai_location("pribor_haron", vector():set(a.x, a.y, a.z), "l12u_sarcofag")
end

function foster_controller()
    alife_create("contr_art1", "l13_deep", vector():set(177.26, 1.738, 590.68))
end

function spawn_aes()
    spawn_patrol("chaes_master1", "aes_master1_walk")
    spawn_patrol("chaes_master2", "aes_master2_walk")
    spawn_patrol("chaes_master3", "aes_master3_walk")
    spawn_patrol("chaes_master4", "aes_master4_walk")
    spawn_patrol("chaes_master5", "aes_master5_walk")
    spawn_patrol("chaes_master6", "aes_master6_walk")
end

function set_relation(sid)
    local obj = level_object_by_sid(story_ids.chaes_mamai_master)
    if obj and obj:alive() then
        npc:set_character_community("monolith", 0, 0)
    end
end

function set_community(actor, npc)
    db.actor:set_character_community("monolith", 0, 0)
end

function get_npc_rank(obj)
    local sobj = alife():object(obj:id())
    if sobj and sobj.rank and sobj:rank() then
        return math.floor(sobj:rank() / 290)
    end
    return nil
end

function max_comp(i1, i2) -- возвращает true если i1 меньше i2
    if wound_id then
        local sobj = alife():object(wound_id)
        return i1.position:distance_to(sobj.position) < i2.position:distance_to(sobj.position)
    end
end

function spawn_case()
    local obj = alife_create("aes_case1", "l12_stancia_2", vector():set(376.254, 0.005, 383.164))
    level_tasks.add_location_by_id(obj.id, "crlc_big", "case1")

    local obj = alife_create("aes_case2", "l12_stancia_2", vector():set(429.707, 10.132, 152.705))
    level_tasks.add_location_by_id(obj.id, "crlc_big", "case2")

    local obj = alife_create("aes_case3", "l12_stancia_2", vector():set(228.192, 50.010, 134.980))
    level_tasks.add_location_by_id(obj.id, "crlc_big", "case3")
end

function controller_tubeman()
    spawn_patrol("bloodsucker_strong", "kon_kontr_strong1_walk")
end

function naem_baza()
    spawn_patrol("naem_haron1", "naem_haron1_walk")
    spawn_patrol("naem_haron2", "naem_haron2_walk")
    spawn_patrol("naem_haron3", "naem_haron3_walk")
    spawn_patrol("naem_haron4", "naem_haron4_walk")
    spawn_patrol("naem_haron5", "naem_haron5_walk")
    spawn_patrol("naem_haron6", "naem_haron6_walk")
    spawn_patrol("naem_haron7", "naem_haron7_walk")
    spawn_patrol("naem_haron8", "naem_haron8_walk")
    spawn_patrol("naem_haron9", "naem_haron9_walk")
    spawn_patrol("naem_haron10", "naem_haron10_walk")
    spawn_patrol("naem_haron11", "naem_haron11_walk")
    spawn_patrol("naem_haron12", "naem_haron12_walk")
    spawn_patrol("naem_haron13", "naem_haron13_walk")
    spawn_patrol("naem_haron14", "naem_haron14_walk")
    spawn_patrol("naem_haron15", "naem_haron15_walk")
    spawn_patrol("naem_haron16", "naem_haron_big")
    spawn_patrol("naem_haron17", "naem_haron_big")
    spawn_patrol("naem_haron18", "naem_haron_big")
    spawn_patrol("naem_haron19", "naem_haron_small")
    spawn_patrol("naem_haron20", "naem_haron_small")
end

function naem_len()
    spawn_patrol("naem_mathon1", "naem_mathon1_walk")
    spawn_patrol("naem_mathon2", "naem_mathon2_walk")
    spawn_patrol("naem_mathon3", "naem_mathon3_walk")
    spawn_patrol("naem_mathon4", "naem_mathon4_walk")
    spawn_patrol("naem_mathon5", "naem_mathon5_walk")
    spawn_patrol("naem_mathon6", "naem_mathon6_walk")
    spawn_patrol("naem_mathon7", "naem_mathon7_walk")
    spawn_patrol("naem_mathon8", "naem_mathon8_walk")
    spawn_patrol("naem_mathon9", "naem_mathon9_walk")
    spawn_patrol("naem_mathon10", "naem_mathon10_walk")
end

function dyak_spawn()
    spawn_patrol("dyak_monolit1", "dyak_aes_lager_aesmon1_camp_walk")
    spawn_patrol("dyak_monolit1", "dyak_aes_lager_aesmon1_camp_walk")
    spawn_patrol("dyak_monolit2", "dyak_aes_lager_aesmon1_camp_walk")
    spawn_patrol("dyak_monolit2", "dyak_aes_lager_aesmon1_camp_walk")
end

local kons = {
    [1] = {x = 190.320, y = -1.830, z = 180.577},
    [2] = {x = -115.080, y = -3.450, z = 97.946},
    [3] = {x = -121.941, y = -2.500, z = 87.957},
    [4] = {x = 200.010, y = -2.500, z = 220.897},
    [5] = {x = 206.839, y = -0.350, z = 204.416}
}

function food_spawn()
    local a = kons[math.random(1, 5)]
    spawn_ai_location("box_food", vector():set(a.x, a.y, a.z), "l11_pripyat")
    spawn_ai_location("box_remont", vector():set(1040.902, 1.530, -28.230), "l12_stancia")
end

function doctor_speech()
    if level.name() == "l12_stancia" and db.actor:has_info("haron_spy_have") then
        db.actor:give_info_portion("doctor_info")
        create_re_restr()
        news_manager.send_tip(db.actor, game.translate_string("doctor_speech"))
    end
end

function sms_new()
    db.actor:give_info_portion("haron_talk_need")
    news_manager.send_tip(db.actor, game.translate_string("sms_new"))
end

function sms_doc()
    db.actor:give_info_portion("doc_talk_need")
    news_manager.send_tip(db.actor, game.translate_string("sms_doc"))
end

function sms_keys()
    db.actor:give_info_portion("keys_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_keys"))
end

function sms_taynik()
    db.actor:give_info_portion("taynik_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_taynik"))
end

function sms_graf()
    db.actor:give_info_portion("graf_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_graf"))
end

function sms_klyak()
    db.actor:give_info_portion("klyak_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_klyak"))
end

function sms_vozvrat()
    db.actor:give_info_portion("vozvrat_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_vozvrat"))
end

function sms_solomon()
    db.actor:give_info_portion("info_amk_recipt_shkura")
    news_manager.send_tip(db.actor, game.translate_string("sms_solomon"))
end

function cam_virubaet()
    level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
    level.add_pp_effector("yantar_underground_psi.ppe", 2007, false)
    level.add_pp_effector("total_recall.ppe", 2008, false)
    level.add_cam_effector("camera_effects\\hit_back_left.anm", 26, false, "")
end

function mervin_vyrubaet()
    local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\human_01\stalker\states\breath\breath_2]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
    cam_virubaet()
end

function iuda_vyrubaet()
    local snd_obj = xr_sound.get_safe_sound_object([[affects\hit_fist]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
    cam_virubaet()
end

function good_shlem()
    cam_virubaet()
    local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\human_01\stalker\states\breath\breath_2]])
    snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
    alife():create("good_psy_helmet", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
end

function mono_prizrak_spawn()
    spawn_patrol("mono_prizrak1", "mono_prizrak1_walk")
    spawn_patrol("mono_prizrak2", "mono_prizrak2_walk")
    spawn_patrol("mono_prizrak3", "mono_prizrak3_walk")
    spawn_patrol("mono_prizrak4", "mono_prizrak4_walk")
    spawn_patrol("mono_prizrak5", "mono_prizrak5_walk")
    spawn_patrol("mono_prizrak6", "mono_prizrak6_walk")
end

function mono_patrol()
    spawn_patrol("mono_patrol1", "mono_patrol1_walk")
    spawn_patrol("mono_patrol2", "mono_patrol2_walk")
    spawn_patrol("mono_patrol3", "mono_patrol3_walk")
    spawn_patrol("mono_patrol4", "mono_patrol4_walk")
    spawn_patrol("mono_patrol5", "mono_patrol5_walk")
    spawn_patrol("mono_patrol6", "mono_patrol6_walk")
    spawn_patrol("mono_patrol7", "mono_patrol7_walk")
    spawn_patrol("mono_patrol8", "mono_patrol8_walk")
end

function sheme_bunker_spawn()
    spawn_ai_location("shceme_document_ruk", vector():set(-32.461, -34.430, -21.971), "l12u_control_monolith")
end

function solomon_grabs()
    local obj = spawn_patrol("solomon_mono1", "solomon_mono1_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\solomon_mono1.ltx"
    alife():assign_story_id(obj.id, story_ids.solomon_mono1)
end

function solomon_mono_spawn()
    spawn_patrol("solomon_mono2", "solomon_mono2_walk")
    spawn_patrol("solomon_mono3", "solomon_mono3_walk")
    spawn_patrol("solomon_mono4", "solomon_mono4_walk")
    spawn_patrol("solomon_mono5", "solomon_mono5_walk")
end

local out_object
local in_object

function ograblen(actor, npc)
    local inv_box_1 = level_object_by_sid(story_ids.solomon_mono1)
    out_object = db.actor
    in_object = inv_box_1
    db.actor:inventory_for_each(transfer_object_items)
end

function bandit_vzal(actor, npc)
    local inv_box_1 = level_object_by_sid(story_ids.esc_shilo_band)
    out_object = db.actor
    in_object = inv_box_1
    db.actor:inventory_for_each(transfer_object_items)
end

function bandit_otdal(actor, npc)
    local inv_box_1 = level_object_by_sid(story_ids.esc_shilo_band)
    in_object = db.actor
    out_object = inv_box_1
    out_object:inventory_for_each(transfer_object_item)
end

function peredacha(actor, npc)
    local inv_box_1 = level_object_by_sid(story_ids.agr_u_secret_0000)
    out_object = db.actor
    in_object = inv_box_1
    db.actor:inventory_for_each(transfer_object_items)
end

function vozvrat(actor, npc)
    local box = level_object_by_sid(story_ids.agr_u_secret_0000)
    for _, obj in pairs(enum_box_items(box)) do
        box:transfer_item(obj, db.actor)
    end
end

function enum_box_items(box)
    local res = {}
    for i = 0, box:inv_box_count() - 1 do
        table.insert(res, box:object_from_inv_box(i))
    end
    return res
end

function transfer_object_items(item)
    local sect = item:section()
    if sect == "detector_simple" or sect == "matras" or sect == "bioradar" or sect == "detector_kruglov" 
    or sect == "device_torch" or sect == "wpn_knife" or sect == "wpn_binoc" then
        return
    end
    out_object:transfer_item(item, in_object)
end

function transfer_object_item(item)
    out_object:transfer_item(item, in_object)
end

function switch_online(id)
    if id == -1 then
        return
    end
    if alife() then
        alife():set_switch_online(id, true)
        alife():set_switch_offline(id, false)
    end
end

function mervin_vzyal(actor, npc)
    local obj = alife_create("mervin_taynik", "l11_pripyat", vector():set(107.665, 3.997, 130.162))
    alife():use_ai_locations(obj, false)
    alife():assign_story_id(obj.id, story_ids.mervin_taynik)
    dsh.wait_condition(function() return level_object_by_sid(story_ids.mervin_taynik) end, 
    function()
        local inv_box_1 = level_object_by_sid(story_ids.mervin_taynik)
        out_object = db.actor
        in_object = inv_box_1
        db.actor:inventory_for_each(transfer_object_items)
    end)
end

function pripyat_pustoy(actor, npc)
    ogse.clear_npc_inventory()
end

function money_out(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, db.actor:money(), "out")
end

function maroder_grab(actor, npc)
    local obj = alife_create("mervin_taynik", "l13_deep", vector():set(5.66, 17.42, 521.82))
    alife():assign_story_id(obj.id, story_ids.razuvaev_taynik)
    dsh.wait_condition(function() return level_object_by_sid(story_ids.razuvaev_taynik) end, 
    function()
        local inv_box_1 = level_object_by_sid(story_ids.razuvaev_taynik)
        out_object = db.actor
        in_object = inv_box_1
        db.actor:inventory_for_each(transfer_object_items)
    end)
end

function maroder_grab2(actor, npc)
    local inv_box_1 = level_object_by_sid(story_ids.ros_simulation_box_2)
    out_object = db.actor
    in_object = inv_box_1
    db.actor:inventory_for_each(transfer_object_items)
    news_manager.send_tip(db.actor, game.translate_string("maroder_grab2"))
end

function maroder_money()
    local money_actor = db.actor:money()
    ogse.save_var("money_actor", money_actor)
    db.actor:give_money(-money_actor)
end

function mervin_money()
    local money_actor = db.actor:money()
    db.actor:give_money(-money_actor)
end

function set_solomon(sid)
    local npc = level_object_by_sid(story_ids.aes_solomon)
    if not npc or not npc:alive() then
        return
    end
    npc:set_character_community("stalker", 0, 0)
end

function set_community_solomon(actor, npc)
    db.actor:set_character_community("stalker", 0, 0)
end

function friendactor(community1, community2)
    relation_registry.set_community_goodwill("monolith", "actor", 2500)
end

function enemyactor(community1, community2)
    relation_registry.set_community_goodwill("monolith", "actor", -5000)
end

-- перепаковка нет-пакета созданного скриптом рестрикта
function rewrite_restrictor(obj, custom_data, radius)
    local pk = get_netpk(obj, 1)
    ASSERT((pk and pk:isOk()), "can't read netpacket of %s", obj:name())
    local data = pk:get()
    data.shapes:addSphere(radius, vector():set(0, 0, 0))
    data.custom_data:setString(custom_data)
    pk:set(data)
end

function friendsvoboda(community1, community2)
    relation_registry.set_community_goodwill("freedom", "actor", 700)
end

function friendbratva(community1, community2)
    relation_registry.set_community_goodwill("bratok", "actor", 50)
end

function bratva_vrag(actor, npc)
    xr_gulag.setGulagEnemy("bar_bratok", actor)
end

function bratva_zlitsa(actor, npc)
    if db.actor and db.actor:has_info("bratva_spokoina") then
        braad_test.friendbratva()
        db.actor:disable_info_portion("bratva_spokoina")
    end
    news_manager.send_tip(db.actor, game.translate_string("bratva_zlitsa"))
end

function winchester_knyaz()
    spawn_ai_location("wpn_winchester_knyaz", vector():set(112, 5, -11), "l04_darkvalley")
    spawn_ai_location("af_dummy_spring", vector():set(37.87, 1.65, -219.83), "l04_darkvalley")
end

local docs = {
    [1] = {x = -82.109, y = -12.900, z = 55.553},
    [2] = {x = 80.545, y = -12.490, z = 61.700},
    [3] = {x = -9.516, y = -11.670, z = 47.759},
    [4] = {x = 115.012, y = -9.170,z = 46.951},
    [5] = {x = 97.952, y = -4.300, z = 46.210}
}

function informator_doc_spawn()
    local a = docs[math.random(1, 5)]
    spawn_ai_location("informator_doc", vector():set(a.x, a.y, a.z), "l07_military")
end

function lab_doc_spawn()
    spawn_ai_location("labx10_doc_ruk", vector():set(20.045, -23.500, 16.228), "l10u_bunker")
    spawn_ai_location("labx10_computer", vector():set(6.570677280426, -7.800, -15.11957), "l10u_bunker")
end

function actor_na_mest()
    db.actor:give_info_portion("sveeblov_predatel_begin") -- работает
    news_manager.send_tip(db.actor, game.translate_string("actor_na_mest"))
end

function fedya_na_mest()
    db.actor:give_info_portion("fedya_razboinik_est")
    news_manager.send_tip(db.actor, game.translate_string("fedya_na_mest"))
end

function voronin_help()
    if level.name() == "l04_darkvalley" and not db.actor:has_info("dolg_leader_help_start") then
        spawn_patrol("val_atak_bandit1", "dark_knyaz_larger_dark_knyaz_look")
        spawn_patrol("val_atak_bandit2", "dark_knyaz_larger_dark_knyaz_look")
        spawn_patrol("val_atak_bandit3", "dark_knyaz_larger_dark_knyaz_look")
        spawn_patrol("val_atak_bandit4", "dark_knyaz_larger_dark_knyaz_look")
        spawn_patrol("val_atak_bandit5", "dark_knyaz_larger_dark_knyaz_look")
        spawn_patrol("val_atak_bandit6", "dark_random5")
        spawn_patrol("val_atak_bandit7", "dark_random5")
        spawn_patrol("val_atak_bandit8", "dark_random5")
        spawn_patrol("val_atak_bandit9", "dark_random5")
        spawn_patrol("val_atak_bandit10", "dark_random5")
        spawn_patrol("val_atak_bandit11", "dark_random5")
        spawn_patrol("val_atak_bandit12", "dark_random5")
        spawn_patrol("val_atak_bandit13", "dark_random5")
        spawn_patrol("val_atak_bandit14", "dark_random5")
        spawn_patrol("val_atak_bandit15", "dark_random5")
        local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\scenario\bar\dolg_megafon\megaphone_duty_alarm]])
        snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
        db.actor:give_info_portion("dolg_leader_help_start")
    end
    news_manager.send_tip(db.actor, game.translate_string("voronin_help"))
end

function frienddolg(community1, community2)
    relation_registry.set_community_goodwill("dolg", "actor", 250)
end

function add_semeckii_treasure()
    treasure_manager.get_treasure_manager():give_treasure("rad_semeckii_treasure_box")
end

function set_jeka(sid)
    local obj = level_object_by_sid(story_ids.garbage_stalker_wound)
    if obj and obj:alive() then
        obj:set_relation(game_object.enemy, db.actor)
    end
end

local plan_points = 
{
    [1] = {x = -284.4497, y = -18.2044, z = 193.8524},
    [2] = {x = -244.72052, y = -18.2133, z = 228.4244},
    [3] = {x = -297.0713, y = -18.0289, z = 291.957},
    [4] = {x = -266.4625, y = -5.94375, z = 409.4007},
    [5] = {x = -356.2475, y = -13.421, z = 391.9168},
    [6] = {x = -359.2898, y = -17.07724, z = 206.545},
    [7] = {x = -355.6864, y = -3.100588, z = 151.18237}
}

function spawn_plan()
    local a = plan_points[math.random(1, 7)]
    spawn_ai_location("new_plan", vector():set(a.x, a.y, a.z), "l07_military")
end

function set_metka_ucen()
    local sim = alife()
    for a, obj in alife():objects() do
        if obj:section_name() == "new_plan" then
            level_tasks.add_location_by_id(obj.id, "red_location", game.translate_string("set_metka_ucen"))
            break
        end
    end
end

function check_actor_weapon()
    weapon_present = true
    db.actor:inventory_for_each(checks_item)
    return weapon_present
end

function checks_item(item)
    if isWeapon(item) then
        weapon_present = false
    end
end

function seredina_est()
    news_manager.send_tip(db.actor, game.translate_string("seredina_est"))
end

function krugone_spawn()
    spawn_patrol("zombie_strong_und4", "agr_und_monster1_walk")
    spawn_patrol("zombie_strong_und4", "agr_und_monster1_walk")
    spawn_patrol("zombie_strong_und4", "agr_und_monster1_walk")
    spawn_patrol("zombie_strong_und3", "agr_und_monster2_walk")
    spawn_patrol("zombie_strong_und3", "agr_und_monster2_walk")
    spawn_patrol("zombie_strong_und3", "agr_und_monster2_walk")
    spawn_patrol("zombie_strong_und2", "agr_und_monster3_walk")
    spawn_patrol("zombie_strong_und2", "agr_und_monster3_walk")
    spawn_patrol("zombie_strong_und1", "agr_und_monster4_walk")
    spawn_patrol("zombie_strong_und1", "agr_und_monster4_walk")
    aptec_spawn()
end

function krugtwo_spawn()
    spawn_patrol("snork_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("snork_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("snork_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("snork_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("snork_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("snork_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("snork_normal_und2", "agr_und_monster3_walk")
    spawn_patrol("snork_normal_und2", "agr_und_monster3_walk")
    spawn_patrol("snork_normal_und1", "agr_und_monster4_walk")
    spawn_patrol("snork_normal_und1", "agr_und_monster4_walk")
    aptec_spawn()
end

function krugtri_spawn()
    spawn_patrol("bloodsucker_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("bloodsucker_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("bloodsucker_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("bloodsucker_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("bloodsucker_normal_und2", "agr_und_monster3_walk")
    spawn_patrol("bloodsucker_normal_und1", "agr_und_monster4_walk")
    aptec_spawn()
end

function krugfour_spawn()
    spawn_patrol("burer_normal_und4", "agr_und_monster1_walk")
    spawn_patrol("burer_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("burer_normal_und3", "agr_und_monster2_walk")
    spawn_patrol("burer_normal_und2", "agr_und_monster3_walk")
    spawn_patrol("burer_normal_und1", "agr_und_monster4_walk")
    aptec_spawn()
end

function aptec_spawn()
    spawn_ai_location("medkit_army", vector():set(-102.1484, -4.4490, -143.855), "l03u_agr_underground")
    spawn_ai_location("bandage", vector():set(-102.1384, -4.4736, -143.7165), "l03u_agr_underground")
end

function bes_zasada()
    local obj = spawn_patrol("bes_zasada1", "bes_zasada1_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada1.ltx"

    local obj = spawn_patrol("bes_zasada2", "bes_zasada2_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada2.ltx"

    local obj = spawn_patrol("bes_zasada3", "bes_zasada3_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada3.ltx"

    local obj = spawn_patrol("bes_zasada4", "bes_zasada4_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada4.ltx"

    local obj = spawn_patrol("bes_zasada5", "bes_zasada5_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada5.ltx"

    local obj = spawn_patrol("bes_zasada6", "bes_zasada6_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\bes_zasada6.ltx"
end

function set_chimera_ucen_prov()
    for a, obj in alife():objects() do
        if obj:section() == "electro_chimera" then
            level_tasks.add_location_by_id(obj.id, "blue_location", game.translate_string("set_chimera_ucen"))
            break
        end
    end
end

function set_chimera_ucen()
    for a, obj in alife():objects() do
        if obj and obj:name() == "electro_chimera_ucen" then
            level_tasks.add_location_by_id(obj.id, "blue_location", game.translate_string("set_chimera_ucen"))
            break
        end
    end
end

function set_gigant_ucen()
    for a, obj in alife():objects() do
        if obj and obj:name() == "gigant_strong_ucen" then
            level_tasks.add_location_by_id(obj.id, "blue_location", game.translate_string("set_gigant_ucen"))
            break
        end
    end
end

function set_bloodsucker_ucen()
    for a, obj in alife():objects() do
        if obj and obj:name() == "bloodsucker_strong_ucen" then
            level_tasks.add_location_by_id(obj.id, "blue_location", game.translate_string("set_bloodsucker_ucen"))
            break
        end
    end
end

function chimera_est()
    db.actor:give_info_portion("ucen_need_metka_chimera_have")
    set_chimera_ucen()
    news_manager.send_tip(db.actor, game.translate_string("chimera_est"))
end

function gigant_est()
    db.actor:give_info_portion("ucen_need_metka_gigant_have")
    set_gigant_ucen()
    news_manager.send_tip(db.actor, game.translate_string("gigant_est"))
end

function bloodsucker_est()
    db.actor:give_info_portion("ucen_need_metka_bloodsucker_have")
    set_bloodsucker_ucen()
    news_manager.send_tip(db.actor, game.translate_string("bloodsucker_est"))
end

function controler_zasada()
    if level.name() == "l06_rostok" and not db.actor:has_info("controler_zasada_spawn") then
        alife_create("snork_jumper", "l08_yantar", vector():set(-89.0649261474609, -0.0018038153, 122.017))
        alife_create("snork_jumper", "l08_yantar", vector():set(-89.689453125, -0.00023889, 146.79014))
        local snd_obj = xr_sound.get_safe_sound_object([[monsters\burer\burer_scan_affect_1]])
        snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
        db.actor:give_info_portion("controler_zasada_spawn")
    end
end

function ecolog_new()
    local obj = level_object_by_sid(story_ids.ecolog_new)
    if obj then
        obj:set_relation(game_object.enemy, db.actor)
    end
end

function yan_wound_ucen()
    local obj = level_object_by_sid(story_ids.yan_wound_ucen)
    if obj then
        obj:set_relation(game_object.enemy, db.actor)
    end
end

function naem_sahar_spawn()
    if level.name() == "l04_darkvalley" and not db.actor:has_info("doronin_help_spawn") then
        spawn_patrol("naem_sahar5", "naem_sahar1_walk")
        spawn_patrol("naem_sahar6", "naem_sahar2_walk")
        db.actor:give_info_portion("doronin_help_spawn")
    end
    yan_wound_ucen()
    ecolog_new()
    news_manager.send_tip(db.actor, game.translate_string("naem_sahar_spawn"))
end

function nychka_spawn()
    local obj = level_object_by_sid(story_ids.val_secret_0024)
    ogse.spawn_item_in_inv("wpn_abakan_n", obj, 10)
    ogse.spawn_item_in_inv("ammo_5.45x39_ap", obj, 15)
    ogse.spawn_item_in_inv("ammo_vog-25", obj, 15)
    ogse.spawn_item_in_inv("flash_ban", obj, 1)
    level_tasks.add_location_by_id(obj:id(), "blue_location", game.translate_string("set_spot_ban"))
end

function dan_zombi()
    spawn_patrol("dan_zombied1", "dan_zombied1_walk")
    spawn_patrol("dan_zombied2", "dan_zombied2_walk")
    spawn_patrol("dan_zombied3", "dan_zombied3_walk")
    spawn_patrol("dan_zombied4", "dan_zombied4_walk")
    spawn_patrol("dan_zombied5", "dan_zombied5_walk")
end

function voronin_snork()
    spawn_patrol("snork_voronin1", "snork_voronin1_home")
    spawn_patrol("snork_voronin2", "snork_voronin1_home")
    spawn_patrol("snork_voronin3", "snork_voronin1_home")
    spawn_patrol("snork_voronin4", "snork_voronin2_home")
    spawn_patrol("snork_voronin5", "snork_voronin2_home")
    spawn_patrol("snork_voronin6", "snork_voronin2_home")
    spawn_patrol("snork_voronin7", "snork_voronin3_home")
    spawn_patrol("snork_voronin8", "snork_voronin3_home")
    spawn_patrol("snork_voronin9", "snork_voronin3_home")
    spawn_patrol("snork_voronin10", "snork_voronin4_home")
    spawn_patrol("snork_voronin11", "snork_voronin4_home")
    spawn_patrol("snork_voronin12", "snork_voronin4_home")
end

function set_relation_jila(sid)
    local obj = level_object_by_sid(story_ids.val_gila)
    if obj and obj:alive() then
        obj:set_character_community("stalker", 0, 0)
    end
end

function set_community_jila(actor, npc)
    db.actor:set_character_community("stalker", 0, 0)
end

function spawn_caterpillar()
    local position = db.actor:position()
    position.x = position.x
    position.y = position.y + 5
    position.z = position.z
    news_manager.send_tip(db.actor, game.translate_string("check_caterpillar"))
    alife():create("af_caterpillar", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function check_caterpillar(actor, npc, info)
    if db.actor and db.actor:dont_has_info(info[1]) then
        spawn_caterpillar()
        db.actor:give_info_portion(info[1])
    end
end

function contr_art_spawn()
    if level.name() == "l03_agroprom" and db.actor:dont_has_info("kruglov_art_contr") then
        alife_create("pseudodog_normal", "l03_agroprom", vector():set(-179.50202941895, 13.36301612, 149.71054077148))
        local snd_obj = xr_sound.get_safe_sound_object([[monsters\burer\burer_scan_affect_1]])
        snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
        db.actor:give_info_portion("kruglov_art_contr")
    end
end

function volk_ban_spawn()
    spawn_patrol("volk_ban1", "volk_ban1_walk")
    spawn_patrol("volk_ban2", "volk_ban2_walk")
    spawn_patrol("volk_ban3", "volk_ban3_walk")
    spawn_patrol("volk_ban4", "volk_ban4_walk")
end

function knyaz_razborka()
    db.actor:give_info_portion("krest_razborka_speech")
    news_manager.send_tip(db.actor, game.translate_string("knyaz_razborka"))
end

function knyaz_set()
    for a, obj in alife():objects() do
        local sobj = level.object_by_id(obj.id)
	    if sobj and sobj:alive() and string.find(sobj:name(), "razbor_ban") then
            sobj:set_character_community("killer", 0, 0)
        end
    end
end

function razborka_begin()
    db.actor:give_info_portion("krest_razborka_speech2")
    news_manager.send_tip(db.actor, game.translate_string("razborka_begin"))
end

function knyaz_set_nazad()
    for a, obj in alife():objects() do
        local sobj = level.object_by_id(obj)
        if sobj and sobj:alive() and string.find(sobj:name(), "esc_krest_ohr") then
            obj:set_character_community("bratok", 0, 0)
        end
    end
end

function spawn_check_kontr()
    local position = db.actor:position()
    position.x = position.y + 10
    alife():create("m_controller_old", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function spawn_check_krovosos()
    local position = db.actor:position()
    position.x = position.x + 10
    alife():create("bloodsucker_strong", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function spawn_check_burer()
    local position = db.actor:position()
    position.x = position.x + 10
    alife():create("burer_strong", position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function new_logic()
    for a, obj in alife():objects() do
        if obj and string.find(obj:name(), "agr_und_zombi") then
            alife():release(obj, true)
            level.add_cam_effector("camera_effects\\prison_1.anm", 25, false, "")
            level.add_pp_effector("black.ppe", 2506, false, "")
            local obj = alife():create("agr_und_zombi", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id())
            local npc = alife():assign_story_id(obj.id, story_ids.agr_und_zombi)
            ogse.reset_npc_logic(npc)
            break
        end
    end
end

function mayor_yarofeev_spawn()
    spawn_patrol("krevoshaev_specnaz1", "commander_krevoshaev_specnaz1_walk")
    spawn_patrol("krevoshaev_specnaz2", "commander_krevoshaev_specnaz2_walk")
    spawn_patrol("krevoshaev_specnaz3", "commander_krevoshaev_specnaz2_walk")
    spawn_patrol("krevoshaev_specnaz4", "commander_krevoshaev_specnaz2_walk")
    spawn_patrol("krevoshaev_specnaz5", "commander_krevoshaev_specnaz2_walk")
end

function sms_sidr()
    db.actor:give_info_portion("mayor_yarofeev_vrag")
    news_manager.send_tip(db.actor, game.translate_string("sms_sidr"))
end

function sidr_lab_spawn()
    spawn_ai_location("notebook_x16", vector():set(-57.764, 19.210, -0.122), "l08u_brainlab")
end

function ohranik_spawn()
    spawn_ai_location("wpn_m32_mgl", vector():set(-24.94743, -5.650, -21.90315), "l07_military")
end

function klyak_lab_spawn()
    spawn_patrol("lab_zasada1", "lab_zasada1_walk")
    spawn_patrol("lab_zasada2", "lab_zasada2_walk")
    spawn_patrol("lab_zasada3", "lab_zasada3_walk")
    spawn_patrol("lab_zasada4", "lab_zasada4_walk")
    spawn_patrol("lab_zasada5", "lab_zasada5_walk")
    spawn_patrol("lab_zasada6", "lab_zasada6_walk")
    spawn_patrol("lab_zasada7", "lab_zasada7_walk")
    spawn_patrol("lab_zasada8", "lab_zasada8_walk")
end

function ban_kogot_spawn()
    spawn_patrol("ban_kogot1", "ban_kogot1_walk")
    spawn_patrol("ban_kogot2", "ban_kogot2_walk")
    spawn_patrol("ban_kogot3", "ban_kogot3_walk")
    spawn_patrol("ban_kogot4", "ban_kogot4_walk")
    spawn_patrol("ban_kogot5", "ban_kogot5_walk")
    spawn_patrol("ban_kogot6", "ban_kogot6_walk")
    spawn_patrol("ban_kogot7", "ban_kogot_centr")
    spawn_patrol("ban_kogot8", "ban_kogot_centr")
end

function klyak_mil_spawn()
    if level.name() == "l07_military" and not db.actor:has_info("mil_klyak_help_start") then
        spawn_patrol("mil_naem1", "mil_naem1_walk")
        spawn_patrol("mil_naem2", "mil_naem2_walk")
        spawn_patrol("mil_naem3", "mil_naem3_walk")
        spawn_patrol("mil_naem4", "mil_naem4_walk")
        spawn_patrol("mil_naem5", "mil_naem5_walk")
        spawn_patrol("mil_naem6", "mil_naem6_walk")
        spawn_patrol("mil_naem7", "mil_naem7_walk")
        spawn_patrol("mil_naem8", "mil_naem8_walk")
        db.actor:give_info_portion("mil_klyak_help_start")
    end
end

function spawn_ammo_shilo()
    spawn_ai_location("ammo_12x70_buck", vector():set(-254.211, 1.375, 10.877), "l06_rostok")
end

function clear_npc_inventory(npc)
    npc:iterate_inventory(del_item, npc)
end

function del_item(npc, item)
    local section = item:section()
    if section == "bolt" or section == "device_torch" then
        return false
    end
    alife():release(alife():object(item:id()), true)
end

function set_fedya(sid)
    local obj = level_object_by_sid(story_ids.fedya_razboinik)
    if obj and obj:alive() then
        obj:set_relation(game_object.enemy, db.actor)
    end
end

function friendall(community1, community2)
    relation_registry.set_community_goodwill("dolg", "actor", 300)
    relation_registry.set_community_goodwill("stalker", "actor", 100)
    relation_registry.set_community_goodwill("freedom", "actor", 300)
    relation_registry.set_community_goodwill("nebo", "actor", 100)
    relation_registry.set_community_goodwill("bratok", "actor", 100)
    relation_registry.set_community_goodwill("stranger", "actor", 100)
    relation_registry.set_community_goodwill("trader", "actor", 100)
    relation_registry.set_community_goodwill("ecolog", "actor", 100)
    relation_registry.set_community_goodwill("military", "actor", -300)
    relation_registry.set_community_goodwill("bandit", "actor", -300)
    relation_registry.set_community_goodwill("monolith", "actor", -300)
    relation_registry.set_community_goodwill("killer", "actor", -300)
end

function levsha_naem()
    spawn_patrol("levsha_naem1", "levsha_naem1_walk")
    spawn_patrol("levsha_naem2", "levsha_naem2_walk")
    spawn_patrol("levsha_naem3", "levsha_naem3_walk")
end

function levsha_bioradar()
    spawn_ai_location("bioradar", vector():set(-260.860, 0.015, 26.480), "l06_rostok")
end

function mina_band()
    local h = hit()
    local pos = db.actor:position()
    local mina_band_particle = particles_object("explosions\\explosion_fuelcan")
    local mina_band_sound = sound_object([[weapons\t_rgd5_explosion]])
    mina_band_particle:play_at_pos(pos)
    mina_band_sound:play_at_pos(db.actor, pos, 0)
    h.draftsman = db.actor
    h.direction = vector():set(0, 0, 0)
    h:bone("bip01_spine")
    h.type = hit.explosion
    h.power = 0.6
    h.impulse = 500
    db.actor:hit(h)
    level.add_pp_effector("amk_shoot.ppe", 2011, false)
end

----------------------------------------------------------РАДИАЦИЯ ARC-----------------------------------------------
local inv_arts_radiation = 0

local time_previous = time_global()
local time_step = 287

local function on_update()
    if not db.actor:object("box_black") then return end

    local time_current = time_global() + 5500
    local time_delta = time_current - time_previous

    if time_delta >= time_step then
        local delta_radiation = inv_arts_radiation * math.min(5, time_delta / time_step)
        delta_radiation = delta_radiation + 0.004

        if delta_radiation > 0 then
            db.actor.radiation = delta_radiation
        end
        time_previous = time_current
    end
end
---------------------------------------------------------РАДИАЦИЯ ARC-----------------------------------------------

function spawn_mervin()
    local obj = alife_create("esc_mervin", "l11_pripyat", vector():set(-161.866, -1.748, 67.668))
    obj.custom_data = "[logic]\ncfg = scripts\\new\\esc_mervin.ltx"
    alife():assign_story_id(obj.id, story_ids.esc_mervin)
end

function pda_priz_spawn()
    spawn_ai_location("pda_priz", vector():set(-304.193, -27.575, 205.831), "l07_military")
end

function mina_sclad()
    local h = hit()
    local pos = db.actor:position()
    local mina_sclad_particle = particles_object("explosions\\explosion_fuelcan")
    local mina_sclad_sound = sound_object([[weapons\t_rgd5_explosion]])
    h.draftsman = db.actor
    h.direction = vector():set(0, 0, 0)
    h:bone("bip01_spine")
    h.type = hit.explosion
    h.power = 0.6
    h.impulse = 500
    db.actor:hit(h)
    mina_sclad_particle:play_at_pos(pos)
    mina_sclad_sound:play_at_pos(db.actor, pos, 0)
    level.add_pp_effector("amk_shoot.ppe", 2011, false)
end

function spawn_desant()
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil", "heli_desant_move")
    spawn_patrol("valet_mil_master", "heli_desant_move")
    spawn_patrol("valet_mil_master", "heli_desant_move")
    spawn_patrol("valet_mil_master", "heli_desant_move")
    spawn_patrol("valet_mil_master", "heli_desant_move")
end

function ucen_electro()
    local obj = spawn_patrol("electro_chimera", "electro_chimera_ucen_walk")
    obj.custom_data = "[logic]\ncfg = scripts\\new\\electro_chimera_ucen.ltx"
end

function mini_time(actor, npc)
    return level.get_time_hours() >= 3 and level.get_time_hours() < 5
end

function is_night(actor, npc)
    return level.get_time_hours() >= 0 and level.get_time_hours() < 6
end

function is_day(actor, npc)
    return level.get_time_hours() >= 6 and level.get_time_hours() < 21
end

function drink_vodka()
    db.actor:eat(db.actor:object("vodka"))
end

function drink_adulin()
    db.actor:eat(db.actor:object("adulin"))
end

function set_lapsha(first_speaker, second_speaker)
    second_speaker:set_relation(game_object.enemy, first_speaker) 
end

function super_krovosos_spawn()
    local obj = spawn_patrol("bloodsucker_super_strong", "super_krovosos_walk")
    alife():assign_story_id(obj.id, story_ids.super_krovosos)
end

function monach_spawn()
    spawn_patrol("monach_flame1", "monach_flame_walk")
    spawn_patrol("monach_flame2", "monach_flame_walk")
    spawn_patrol("monach_flame3", "monach_flame_walk")
    spawn_patrol("monach_flame4", "monach_flame_walk")
    spawn_patrol("monach_tele1", "monach_tele_walk")
    spawn_patrol("monach_tele2", "monach_tele_walk")
    spawn_patrol("monach_tele3", "monach_tele_walk")
    spawn_patrol("monach_tele4", "monach_tele_walk")
end

function black_box_spawn()
    spawn_ai_location("box_black", vector():set(352.86376953125, -45.480, -196.2610168457), "l10_radar")
end

function prizrak_pda()
    db.actor:give_info_portion("prizrak_about_pda_start")
end

function krest_info()
    db.actor:give_info_portion("krest_work_have")
end

function set_pri_priz()
    local obj = level_object_by_sid(story_ids.new_prizrak)
    if obj then
        obj:set_relation(game_object.friend, db.actor)
    end
end

function create_re_restr()
    local sim = alife()
    for a, obj in alife():objects() do
        if obj and obj:name() == "pri_prizrak_restr" then
            obj.custom_data = "[logic]\ncfg = scripts\\new\\restr\\pri_prizrak_restr_new.ltx"
        end
    end
end

function sms_amulet()
    db.actor:give_info_portion("almaz_talk")
    news_manager.send_tip(db.actor, game.translate_string("sms_amulet"))
end

function amulet_effect()
    level.add_pp_effector("teleport.ppe", 2006, false)
end

function create_final_restr()
    local obj = alife_create("space_restrictor", "l12u_control_monolith", vector():set(0.054, -34.355, 17.672))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\final_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_x16_restr()
    local obj = alife_create("space_restrictor", "l08_yantar", vector():set(-66.073, -19.088, -158.844))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\x16_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function set_povodyr()
    local sim = alife()
    for a, obj in alife():objects() do
        if obj:section_name() == "dog_povodyr" then
            level_tasks.add_location_by_id(obj.id, "blue_location", game.translate_string("set_povodyr"))
            return
        end
    end
end

function create_lesnik_restr()
    local pp = patrol("lesnik_walk1")
    local obj = alife():create("space_restrictor", pp:point(6), pp:level_vertex_id(6), pp:game_vertex_id(6))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30159|]] .. obj:name() .. [[|nil %+lesnik_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_vasil_restr()
    local pp = patrol("vasil_walk2")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30148|]] .. obj:name() .. [[|nil %+vasil_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_zombi_restr()
    local pp = patrol("vasil2_walk1")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30161|]] .. obj:name() .. [[|nil %+pomog_zombi%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_vasil2_restr1()
    local pp = patrol("vasil2_walk2")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30161|]] .. obj:name() .. [[|nil %+vasil_dovel%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_skit_restr()
    local pp = patrol("postovoy_walk1")
    local obj = alife():create("space_restrictor", pp:point(7), pp:level_vertex_id(7), pp:game_vertex_id(7))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30162|]] .. obj:name() .. [[|nil %+skit_prishli%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_postovoy_restr()
    local pp = patrol("postovoy_walk2")
    local obj = alife():create("space_restrictor", pp:point(6), pp:level_vertex_id(6), pp:game_vertex_id(6))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30162|]] .. obj:name() .. [[|nil %+postovoy_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_pripyat_restr()
    local obj = alife_create("space_restrictor", "l09_deadcity", vector():set(181.414, -2.876, -51.635))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\pripyat_restr.ltx"
    rewrite_restrictor(obj, custom, 3.0)
end

function bar_attak_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(40.715, -0.001, 238.610))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\bar_attak.ltx"
    rewrite_restrictor(obj, custom, 8.0)
end

function create_plichko_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(224.667, -5.448, 125.996))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30176|]] .. obj:name() .. [[|nil %+plichko_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_attak7_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(136.671, -4.825, 21.034))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30177|]] .. obj:name() .. [[|nil %+dolg_attak7_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_attak8_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(221.044, -0.011, -7.659))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30178|]] .. obj:name() .. [[|nil %+dolg_attak8_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_voronin_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(225.696, -5.248, 131.531))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30179|]] .. obj:name() .. [[|nil %+voronin_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_vstrecha_restr()
    local pp = patrol("barman_walk2")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30190|]] .. obj:name() .. [[|nil %+barman_strelka_prishel%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_grek_restr()
    local pp = patrol("grek_walk1")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30188|]] .. obj:name() .. [[|nil %+grek_mesto%]]
    rewrite_restrictor(obj, custom, 3.0)
end

function create_zahar_restr()
    local pp = patrol("zahar_walk2")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30195|]] .. obj:name() .. [[|nil %+zahar_mesto%]]
    rewrite_restrictor(obj, custom, 2.0)
end

function create_podmoga_restr()
    local obj = alife_create("space_restrictor", "l01_escape", vector():set(-17.474, 2.480, 64.866))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle] 
    on_npc_in_zone = 30197|]] .. obj:name() .. [[|nil %+podmoga_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_tolik_restr()
    local obj = alife_create("space_restrictor", "l01_escape", vector():set(6.284, 2.381, 63.295))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 9644|]] .. obj:name() .. [[|nil %+esc_tolik_help_have%]]
    rewrite_restrictor(obj, custom, 10.0)
end

function create_foster_restr()
    local pp = patrol("foster2_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30186|]] .. obj:name() .. [[|nil %+kapral_mesto%]]
    rewrite_restrictor(obj, custom, 5.0)
end

function create_brown_restr()
    local pp = patrol("brown1_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\brown_zvuk.ltx"
    rewrite_restrictor(obj, custom, 4.0)
end

function foster_zvuk_restr()
    local pp = patrol("foster1_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\foster_zvuk.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_rostok_restr()
    local obj = alife_create("space_restrictor", "l06_rostok", vector():set(-83.083, -15.536, -201.172))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\rostok_restr.ltx"
    rewrite_restrictor(obj, custom, 3.0)
end

function create_karina1_restr()
    local pp = patrol("karina2_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = [[[logic]
    active = sr_idle
    [sr_idle]
    on_npc_in_zone = 30189|]] .. obj:name() .. [[|nil %+karina_mesto%]]
    rewrite_restrictor(obj, custom, 1.0)
end

function create_povodyr_restr()
    local pp = patrol("dog_povodyr1_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\povodyr_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_antikvar_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(207.609, 0.430, 60.231))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\antikvar_restr.ltx"
    rewrite_restrictor(obj, custom, 4.0)
end

function create_cezar_restr()
    local obj = alife_create("space_restrictor", "l08_yantar", vector():set(29.068, -11.688, -280.074))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\cezar_restr.ltx"
    rewrite_restrictor(obj, custom, 4.0)
end

function create_graf_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(149.237, 0.428, 68.958))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\graf_restr.ltx"
    rewrite_restrictor(obj, custom, 2.1)
end

function create_mervin1_restr()
    local obj = alife_create("space_restrictor", "l11_pripyat", vector():set(-162.525, -1.755, 66.612))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin1_restr.ltx"
    rewrite_restrictor(obj, custom, 12.0)
end

function create_mervin2_restr()
    local obj = alife_create("space_restrictor", "l12u_sarcofag", vector():set(9.693, 56.273, 48.022))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin2_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_mervin3_restr()
    local obj = alife_create("space_restrictor", "l11_pripyat", vector():set(101.323, 4.003, 123.453))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\mervin3_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_prince_restr()
    local obj = alife_create("space_restrictor", "l10_radar", vector():set(659.836, -43.877, 168.970))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\prince_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_monolit_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(-25.688, 0.001, 691.280))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\monolit_restr.ltx"
    rewrite_restrictor(obj, custom, 30.0)
end

function create_dialog_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(-25.688, 0.001, 691.280))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\dialog_restr.ltx"
    rewrite_restrictor(obj, custom, 2.0)
end

function create_chaes2_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(116.323, -0.080, 523.742))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\chaes2_restr.ltx"
    rewrite_restrictor(obj, custom, 180.0)
end

function create_sled2_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(4.635, 5.119, 70.967))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\sled2_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_kristall_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(-31.369, 20.150, 646.914))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\kristall_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_strelok_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(405.769, 36.877, 122.832))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\strelok_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_ugroza_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(105.086, 38.402, 144.396))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\ugroza_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_tele9_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(578.559, 18.205, 294.443))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\tele9_restr.ltx"
    rewrite_restrictor(obj, custom, 8.0)
end

function create_end_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(444.978, 10.149, 152.687))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\end_restr.ltx"
    rewrite_restrictor(obj, custom, 8.0)
end

function create_rule_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(554.277, 150.700, 202.080))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\rule_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_sarfinal_restr()
    local obj = alife_create("space_restrictor", "l12u_sarcofag", vector():set(11.325, 55.594, 28.993))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\sarfinal_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_vano_restr()
    local pp = patrol("vano_walk")
    local obj = alife():create("space_restrictor", pp:point(0), pp:level_vertex_id(0), pp:game_vertex_id(0))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\vano_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_superfinal_restr()
    local obj = alife_create("space_restrictor", "l12_stancia_2", vector():set(885.711, 15.099, 123.097))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\superfinal_restr.ltx"
    rewrite_restrictor(obj, custom, 3.0)
end

function create_vhod_restr()
    local obj = alife_create("space_restrictor", "l13_deep", vector():set(-116.79, 1.37, 116.83))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\vhod_restr.ltx"
    rewrite_restrictor(obj, custom, 30.0)
end

function create_maroder_restr()
    local obj = alife_create("space_restrictor", "l13_deep", vector():set(90.66, 1.67, 545.49))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\maroder_restr.ltx"
    rewrite_restrictor(obj, custom, 3.0)
end

function create_maroder2_restr()
    local obj = alife_create("space_restrictor", "l13_deep", vector():set(-109.97, 1.44, 112.49))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\maroder2_restr.ltx"
    rewrite_restrictor(obj, custom, 2.0)
end

function create_antirostok_restr()
    local obj = alife_create("space_restrictor", "l05_bar", vector():set(40.096, -0.567, 140.467))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\antirostok_restr.ltx"
    rewrite_restrictor(obj, custom, 5.0)
end

function create_iuda_restr()
    local obj = alife_create("space_restrictor", "l12u_sarcofag", vector():set(59.567, 12.359, 7.120))
    local custom = "[logic]\ncfg = scripts\\new\\restr\\iuda_restr.ltx"
    rewrite_restrictor(obj, custom, 1.0)
end

function assing_cd_and_sid(sobj, cd, sid)
    sobj.custom_data = cd
    if sid then
        alife():assign_story_id(sobj.id, sid)
    end
end

function spawn_ai_location(section, pos, lvid_or_lname, gvid)
    if type(pos) == "table" then
        pos = vector():set(unpack(pos))
    end
    local obj
    if type(lvid_or_lname) == "string" then
        obj = alife_create(section, lvid_or_lname, pos)
    else
        obj = alife():create(section, pos, lvid_or_lname, gvid)
    end
    alife():use_ai_locations(obj, false)

    return obj
end

function give_supplies_to_actor(first_speaker, second_speaker)
	if not db.actor:object("device_torch") then
		dialogs.relocate_item_section(first_speaker, "device_torch", "in")
	end
	if not db.actor:object("wpn_knife") then
		dialogs.relocate_item_section(first_speaker, "wpn_knife", "in")
	end
	if not db.actor:object("wpn_binoc") then
		dialogs.relocate_item_section(first_speaker, "wpn_binoc", "in")
	end
end

function actor_has_money_2000()
    return db.actor:money() >= 2000
end

function actor_has_money_3000()
    return db.actor:money() >= 3000
end

function actor_has_money_10000()
    return db.actor:money() >= 10000
end

function actor_has_money_15000()
    return db.actor:money() >= 15000
end

function actor_has_money_100000()
    return db.actor:money() >= 100000
end

function give_money_2000(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, 2000, "out")
end

function give_money_3000(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, 3000, "out")
end

function give_money_10000(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, 10000, "out")
end

function give_money_15000(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, 15000, "out")
end

function give_money_100000(t1, t2)
    local npc = t1
    if npc:id() == db.actor:id() then
        npc = t2
    end
    dialogs.relocate_money(npc, 100000, "out")
end

local function on_item_to_slot(obj, sobj)
    if db.actor:has_info("agro_varayg_four_done") or not db.actor:has_info("agro_varayg_one_start") then return end

    if not string.find(obj:section(), "wpn_knife")
    and not string.find(obj:section(), "wpn_binoc")
    and not string.find(obj:section(), "device_pda")
    and not string.find(obj:section(), "device_torch") then
        db.actor:give_info_portion("agro_varayg_fail")
    end
end

function attach(sm)
	sm:subscribe({signal = "on_first_update",  fun = on_first_update})
	sm:subscribe({signal = "on_info",          fun = on_info})
	sm:subscribe({signal = "on_take",          fun = on_take})
	sm:subscribe({signal = "on_update",        fun = on_update})
	sm:subscribe({signal = "on_item_to_slot",  fun = on_item_to_slot})
end
