--[[

File:  restriction_stock .script
Created:  28.05.2008
Copyright:  © 2008 AMK team
Version:  3.1.0.1 

--]]


------------------------
InvStat = 0
InvMax = 1000
------------------------
IdPistol = 0
IdAutomat = 0
IdOutfit = 0
------------------------
Medk = 1  	
Arts = 1   
Reps = 3	
OutA = 10  	
OutB = 20  	
WpnA = 10  
WpnB = 6  	
WpnC = 8  	
WpnD = 15 
------------------------

TableWpnOutf = {	
		---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		WeaponsA = {"wpn_abakan","wpn_g36","wpn_ak74","wpn_l85","wpn_groza","wpn_lr300","wpn_val","wpn_fn2000","wpn_sig220","wpn_sig_m1"  },		
		WeaponsB = {"wpn_desert_eagle","wpn_fort","wpn_hpsa","wpn_walther","wpn_usp","wpn_beretta","wpn_colt","wpn_pm","wpn_pb","wpn_mp5",
					"wpn_eagle_m1","wpn_bm16","wpn_ak74u"																				  },	    							  			
		WeaponsC = {"wpn_winchester_m1","wpn_wincheaster1300","wpn_spas12"																  },
		WeaponsD = {"wpn_svu","wpn_svd","wpn_vintorez","wpn_gauss","wpn_toz34","wpn_rg-6","wpn_rpg7"									  },
		OutfitsA = {"novice_","bandit_","killer_","monolit_","svoboda_light","dolg_ou","ecolog_","neytral_novice_","svoboda_m1","dolg_gaz"},
		OutfitsB = {"soldier_","specops_","military_","scientific_","stalker_","exo_","svoboda_heavy_","dolg_scientific_","protection_",
					"militaryspec_","svoboda_gaz_","neytral_gaz_","dolg_m1","_exoskeleton","nano_"} 
       ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			   }

-------------------------			   
function restriction_of_stock(ItemObj,Fix)
	local actor = db.actor
	local ItemName  = ItemObj:name()
	local msg = {
				------------------------------------------------------------------------------
				"Рюкзак полон под завязку!",
				"Ну, нет у меня уже в рюкзаке места.",
				"Придется мне это оставить, ибо рюкзак полон.",
				"Рюкзак-то не резиновый!",
				"Рюкзак переполнен.",
				"Мне это некуда положить!",
				"Чтобы это взять, надо что-то выложить."
				------------------------------------------------------------------------------
				}
	
	if actor and string.gfind(ItemName,"ammo") then
		if Fix == 0 then 
			InvStat = ItemsCalcV(ItemObj,1)
		elseif Fix == 1 then 
			InvStat = ItemsCalcV(ItemObj,2)
		end
	
		if InvStat - InvMax > 0 then
			amk.send_tip(msg[math.random(1, table.getn(msg))],nil,nil,5)
			amk.drop_item(actor,ItemObj)
			if isWeapon(ItemObj) then
				ammo_discharge(ItemObj)
			end
		end
	end
end

-------------------------
function InvStatCalc(Operacion,Number)
	if Operacion == 1 then
		local Stat = InvStat + Number
		return Stat 
	elseif Operacion == 2 then
		local Stat = InvStat - Number
		return Stat 
	end
end

-------------------------
function ItemsCalcV(ItemObj,Operacion)
	local actor = db.actor
	local ItemId 	= ItemObj:id()
	local ItemName  = ItemObj:name()
	if actor then
		local PistolSlot = db.actor:item_in_slot(1)
		if PistolSlot then
			IdPistol = PistolSlot:id()
		end
		
		local AutomaticSlot = db.actor:item_in_slot(2)
		if AutomaticSlot then
			IdAutomat = AutomaticSlot:id()
		end
		
		local OutfitSlot = db.actor:item_in_slot(6)
		if OutfitSlot ~= nil then
			IdOutfit = OutfitSlot:id()
		end
		
		
		if ItemId ~= IdPistol and ItemId ~= IdAutomat and ItemId ~= IdOutfit then

			if string.find(ItemName,"medkit") then
				InvStat = InvStatCalc(Operacion,Medk)
			elseif string.find(ItemName,"af") then
				InvStat = InvStatCalc(Operacion,Arts)
			elseif string.find(ItemName,"repbox") then
				InvStat = InvStatCalc(Operacion,Reps)
			end

			for kk,vv in pairs(TableWpnOutf) do
				for k,v in pairs(vv) do
					if     kk == "WeaponsA"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,WpnA) 
						break
					elseif kk == "WeaponsB"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,WpnB) 
						break
					elseif kk == "WeaponsC"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,WpnC) 
						break
					elseif kk == "WeaponsD"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,WpnD) 
						break
					elseif kk == "OutfitsA"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,OutA) 
						break
					elseif kk == "OutfitsB"  and string.find(ItemName,v) then
						InvStat = InvStatCalc(Operacion,OutB) 
						break
					end
				end
			end		
		end
		return InvStat
	end
end

-------------------------
function ammo_discharge(wpn)
	local	name = wpn:name()
	local	ammo_count = wpn:get_ammo_in_magazine()
	local 	t = amk.get_weapon_data(alife():object(wpn:id()))
	local   ammoT = t.ammo_type
	local	section_ammo = weapons_ammo_sections(name,ammoT)
			wpn:unload_magazine()
			amk.spawn_ammo_in_inv(section_ammo, ammo_count, actor)	
end

-------------------------
function weapons_ammo_sections(name, ammoT)
	local	ammo_type		   = ""
	local 	ammo_table		   = {
			-------------------------------------------
			ammo_9x18          = {"wpn_pb","wpn_pm","wpn_fort"},
			ammo_9x19          = {"wpn_beretta","wpn_hpsa","wpn_mp5","wpn_walther"},
			ammo_43x23         = {"wpn_colt1911","wpn_desert_eagle","wpn_sig220","wpn_ups"},
			ammo_12x70         = {"wpn_bm16","wpn_spas12","wpn_toz34","wpn_wincheaster1300"},
			ammo_45x39         = {"wpn_abakan","wpn_ak74","wpn_ak74u"},
			ammo_9x39_1        = {"wpn_val","wpn_vintorez"},
			ammo_9x39_2        = {"wpn_groza"},
			ammo_56x45         = {"wpn_fn2000","wpn_g36","wpn_l85","wpn_lr300","wpn_sig550"},
			ammo_62x54	       = {"wpn_svd","wpn_svu"}
		    -------------------------------------------
							     } 
								 
	for kk,vv in pairs(ammo_table) do
		for k,v in pairs(vv) do 
			if string.find(name,v) then
				ammo_type = kk
				break
			end
		end
	end	
	
	local	ammo_categories	   = {
			-------------------------------------------
			ammo_9x18          = {"ammo_9x18_fmj","ammo_9x18_pmm"},
			ammo_9x19          = {"ammo_9x19_pbp","ammo_9x19_fmj"},
			ammo_43x23         = {"ammo_11.43x23_fmj","ammo_11.43x23_hydro"},
			ammo_12x70         = {"ammo_12x76_dart","ammo_12x76_zhekan","ammo_12x70_buck"},
			ammo_45x39         = {"ammo_5.45x39_ap","ammo_5.45x39_fmj"},
			ammo_9x39_1        = {"ammo_9x39_sp5","ammo_9x39_ap","ammo_9x39_pab9"},
			ammo_9x39_2        = {"ammo_9x39_pab9","ammo_9x39_sp5", "ammo_9x39_ap"},
			ammo_56x45         = {"ammo_5.56x45_ap","ammo_5.56x45_ss190"},
			ammo_62x54	       = {"ammo_7.62x54_7h14","ammo_7.62x54_ap","ammo_7.62x54_7h1"}
			-------------------------------------------
							     }
								 							 
	for kk,vv in pairs(ammo_categories) do 
		if kk == ammo_type then
			if     ammoT == 0 then
				return vv[1]	
				
			elseif ammoT == 1 then
				return vv[2]
				
			elseif ammoT == 2 then
				return vv[3]
			end
		end
	end	
end

