--Vergas разгрузка
class "cheat" (CUIScriptWnd)

function cheat:__init(owner) super()
	self.owner = owner
	self:InitControls()
	self:InitCallBacks()
end

function cheat:InitControls()
	-- Положение и размеры окна
	self:Init(688,257,304,196)
	-- файл-описатель элементов
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_cheat_razgruzka.xml")
	
	xml:InitStatic("background", self)   --Собственно рамка
	xml:InitStatic("background_2", self)  --надпись РАЗГРУЗКА
	xml:InitStatic("background_3", self)                            -- Кнопка Выкл
	self:Register(xml:Init3tButton("btn_stop", self),"btn_stop")	-- Кнопка Выкл
	
	local sl_1 = razgruzka_v.return_ammo(1)
	local sl_2 = razgruzka_v.return_ammo(2)
	local sl_3 = razgruzka_v.return_ammo(3)
	local sl_4 = razgruzka_v.return_ammo(4)
	
	-- Первый слот
	local volume_wnd_1 = nil
	volume_wnd_1 = CUIStatic()
	volume_wnd_1:SetAutoDelete(true)
	self:AttachChild(volume_wnd_1)
	volume_wnd_1:SetWndRect(217, 39, 50, 20)        -- 16 20
	volume_wnd_1:SetFont(GetFontLetterica18Russian())
	volume_wnd_1:SetTextColor(255, 231, 153, 22)
	volume_wnd_1:SetText(""..tostring(sl_1))

	--Второй слот
	local volume_wnd_2 = nil
	volume_wnd_2 = CUIStatic()
	volume_wnd_2:SetAutoDelete(true)
	self:AttachChild(volume_wnd_2)
	volume_wnd_2:SetWndRect(217, 70, 50, 20)
	volume_wnd_2:SetFont(GetFontLetterica18Russian())
	volume_wnd_2:SetTextColor(255, 231, 153, 22)
	volume_wnd_2:SetText(""..tostring(sl_2))
	
	-- Аптечки
	local volume_wnd_3 = nil
	volume_wnd_3 = CUIStatic()
	volume_wnd_3:SetAutoDelete(true)
	self:AttachChild(volume_wnd_3)
	volume_wnd_3:SetWndRect(217, 102, 50, 20)
	volume_wnd_3:SetFont(GetFontLetterica18Russian())
	volume_wnd_3:SetTextColor(255, 231, 153, 22)
	volume_wnd_3:SetText(""..tostring(sl_3))
	
	--Бинты
	local volume_wnd_4 = nil
	volume_wnd_4 = CUIStatic()
	volume_wnd_4:SetAutoDelete(true)
	self:AttachChild(volume_wnd_4)
	volume_wnd_4:SetWndRect(217, 121, 50, 20)
	volume_wnd_4:SetFont(GetFontLetterica18Russian())
	volume_wnd_4:SetTextColor(255, 231, 153, 22)
	volume_wnd_4:SetText(""..tostring(sl_4))
end

function cheat:InitCallBacks()
	self:AddCallback("btn_stop", ui_events.BUTTON_CLICKED, self.btn_stop, self)
end


function cheat:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		-- на выход повесим Esc
		if dik == DIK_keys.DIK_ESCAPE then
			self:on_quit()
		end
	end
	return true
end

function cheat:on_quit()
	razgruzka_v.spawn_item_in_inv("razgruzka")
	self:GetHolder():start_stop_menu (self,true)
end

function cheat:btn_stop()					-- Кнопка Выкл
		self:on_quit()
end


