-- Меню настроек клавиатуры. Используется скриптом ui_mm_opt_main.script

class "opt_controls"(CUIWindow)
function opt_controls:__init()
    super()
end

function opt_controls:__finalize()
end

function opt_controls:InitControls(xml, handler)
    xml:InitKeyBinding("tab_controls:key_binding", self)

    local btn = xml:Init3tButton("tab_controls:btn_default", self)
    handler:Register(btn, "btn_default")
end
