function normal(shader, t_base, t_second, t_detail)
	shader:add_shader_options("USE_BUMP", "1")
	shader:add_shader_options("WPN_ANOMALY_EFFECT", "2")
	shader:begin("deffer_base_hud_bump", "models_anomaly_weapons")
		:fog(false)
	local t_bump = get_bump_name(t_base)
	shader:dx10texture("s_base", t_base)
	shader:dx10texture("s_bump", t_bump)
	shader:dx10texture("s_bumpX", t_bump .. "#")
	shader:dx10texture("s_hud_rain", "fx\\hud_rain")
	shader:dx10sampler("smp_base")
	shader:dx10stencil(true, cmp_func.always, 255 , 127, stencil_op.keep, stencil_op.replace, stencil_op.keep)
	shader:dx10stencil_ref(1)
	shader:clear_shader_options()
end