function element_0(shader, t_base, t_second, t_detail)
	shader:begin("stub_screen_space", "ogsr_rain_drops")
		:fog(false)
		:zb(false, false)
		:blend(true,blend.srcalpha,blend.invsrcalpha)
	shader:dx10texture("s_image", "$user$generic0")
	shader:dx10texture("s_mask_wipe", "shaders\\gasmasks\\mask_wipe")
	shader:dx10texture("s_noise", "shaders\\gasmasks\\mask_noise")
	shader:dx10sampler("smp_nofilter")
	shader:dx10sampler("smp_rtlinear")
	shader:dx10sampler("smp_linear")
end