local t = {}

function load_job(sj, gname, type, squad, groups)
    -- ' Boars nest (to Dolg)
    if type == "gar_boars_nest" then
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {0},
            online = false,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)

        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest",
            idle = 0,
            prior = 5,
            state = {1},
            online = true,
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)

        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_boars_nest_rush",
            idle = 0,
            prior = 5,
            state = {2},
            online = true,
            position_threshold = 300,
            in_rest = "",
            out_rest = "gar_boars_rush"
        }
        table.insert(sj, t)
    end

    -- ' Flesh nest
    if type == "gar_nest_flesh" then
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
        t = {
            section = "logic@gar_nest_flesh",
            idle = 0,
            prior = 5,
            state = {0},
            in_rest = "",
            out_rest = ""
        }
        table.insert(sj, t)
    end
end

function load_states(gname, type)
    if type == "gar_boars_nest" then
        return function(gulag)
            return 0
        end
    end

    if type == "gar_nest_flesh" then
        return function(gulag)
            return 0
        end
    end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
    return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
    return false
end

function checkMonster(npc_community, gulag_type)
    if gulag_type == "gar_boars_nest" then
        return npc_community == "boar"
    end

    if gulag_type == "gar_nest_flesh" then
        return npc_community == "flesh"
    end
    return false
end
